### ISSUE TITLE
NexeError: python ./configure.py --dest-cpu=x64 exited with code: 1

### ISSUE THREAD

**Issue by SDAdham** [nexe/nexe#1007]
Hello, I am getting the following error:
```
NexeError: python ./configure.py --dest-cpu=x64 exited with code: 1
    at ChildProcess.<anonymous> (/<proj-dir>/node_modules/nexe/lib/compiler.js:179:28)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.onexit (internal/child_process.js:288:5)
```

node: `v16.15.0`
nexe: `^4.0.0-rc.1`
image used for building: `node:16.15.0`

Here is what happens:

```bash
apt update && apt install -y python3 g++ make python3-pip msitools
npm config set msvs_version 2019
npm config set python python3.8
```
I also tried v2.7:
```bash
apt update && apt install -y python g++ make python-pip msitools
npm config set msvs_version 2019
npm config set python python2.7
```
Then the following ts runs:
```ts
const nodeVersion = '16.15.0';
const targets = [
      {
        arch: 'x64',
        platform: 'windows',
        version: nodeVersion,
      },
      {
        arch: 'x86',
        platform: 'windows',
        version: nodeVersion,
      },
      {
        arch: 'x64',
        platform: 'linux',
        version: nodeVersion,
      },
      {
        arch: 'x86',
        platform: 'linux',
        version: nodeVersion,
      },
      // {
      //   arch: 'x64',
      //   platform: 'mac',
      //   version: nodeVersion,
      // },
    ];
for (const target of targets)
await compile(
        {
          cwd: '<path>',
          input: 'path-to-intro.js',
          resources: [`<path>/node_modules/**/*`, `./**/*.js`],
          build: true,
          targets: [target],
          output: `path-${target.platform}-${target.arch}`,
          temp: `<path>/.nexe/cache`,
          verbose: false,
          ico: `path-to.ico`,
        },
        (err) => {
          if (err) {
            console.error(err);
          }
        },
      );
```

**Comment by calebboyd** [comment]
Try passing `python: '<path to python3>'`. Also note that `build: true` will only build for your configured/current platform/arch.

**Comment by SDAdham** [comment]
i added `python: '/usr/bin/python3.7',` and now testing but with `build: false`

**Comment by SDAdham** [comment]
Here is what I get if I set the build to false:

```
NexeError: https://github.com/nexe/nexe/releases/download/v3.3.3/linux-x64-16.15.0 is not available, create it using the --build flag
    at /builds/<proj-dir>/node_modules/nexe/lib/steps/download.js:47:23
    at Generator.throw (<anonymous>)
    at rejected (/builds/<proj-dir>/nexe/lib/steps/download.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SDAdham** [comment]
Upon checking the list, I can't find the version that I need: https://github.com/nexe/nexe/releases

**Comment by SDAdham** [comment]
It's working with that version and `build: false`, how can I get the latest version of nodejs?

**Comment by SDAdham** [comment]
@calebboyd can you please help?

**Comment by NexZhu** [comment]
Same issue with Node.js v19.0.1
```
Error: python ./configure.py --dest-cpu=x64 exited with code: 1
```

**Comment by ShovitDutta** [comment]
Error: /usr/bin/python ./configure.py --dest-cpu=x64 exited with code: 1
So we can't use WSL and nodejs 21
what am i supposed to do ?
