### ISSUE TITLE
Using SetTimeout with nexe

### ISSUE THREAD

**Issue by hgleam** [nexe/nexe#1042]
**What happened**:
Error: Cannot find module 'timers/promises'
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'timers/promises'
Require stack:
- E:\develop\xxxxxxxx\sleep-test\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\develop\xxxxxxxx\sleep-test\main.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'E:\\develop\\xxxxxxxx\\sleep-test\\main.js' ]
}
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
main.ts
```
import { setTimeout } from "timers/promises";

async function test() {
    const isRunning = true
    while (isRunning) {
        console.log('Running...')
        await setTimeout(10000)
    }
}
test()
```
compile
```tsc```

build
```
nexe main.js -t windows-x64-14.15.3
```
**Anything else we need to know?**:
Nothing.

**Environment**:
- Platform(OS/Version):Windows 10 Pro 64bit
- Nexe version:4.0.0-rc.2

**Comment by bruce-one** [comment]
`timers/promises` was only added to Node in v15/v16 by the look of the docs - https://nodejs.org/api/timers.html#timers-promises-api

So you'd need to target a newer version of node (i.e. `-t 18.15.0` for example), which would also mean you'd need to use the `--build` argument (harder) or use prebuilt artefacts from a source like https://github.com/urbdyn/nexe_builds (e.g. it looks to have `windows-x64-16.19.0` - _although when I tried it it looked to have a bug with those builds_)
