### ISSUE TITLE
Invalid syntax Error: python ./configure.py --dest-cpu=x64

### ISSUE THREAD

**Issue by abhisheksurve45** [nexe/nexe#1047]
**What happened**:
Error:

```
docker-compose up --build --force-recreate
[+] Building 163.6s (17/20)                                                                   
 => [internal] load build definition from Dockerfile                                     0.0s
 => => transferring dockerfile: 717B                                                     0.0s
 => [internal] load .dockerignore                                                        0.0s
 => => transferring context: 2B                                                          0.0s
 => [internal] load metadata for docker.io/library/node:16                               2.0s
 => [internal] load metadata for docker.io/library/alpine:latest                         1.8s
 => CACHED https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_x  1.9s
 => [build 1/8] FROM docker.io/library/node:16@sha256:051b68ed341fee26f4c08b15815ac4bff  0.0s
 => [internal] load build context                                                        0.0s
 => => transferring context: 65.91kB                                                     0.0s
 => [stage-1 1/6] FROM docker.io/library/alpine@sha256:124c7d2707904eea7431fffe91522a01  0.0s
 => CACHED [stage-1 2/6] RUN apk add --no-cache libstdc++ libgcc                         0.0s
 => CACHED [stage-1 3/6] WORKDIR /usr/src/app                                            0.0s
 => CACHED [build 2/8] WORKDIR /usr/src/app                                              0.0s
 => CACHED [build 3/8] COPY package*.json ./                                             0.0s
 => CACHED [build 4/8] RUN npm install --omit=dev                                        0.0s
 => [build 5/8] COPY . .                                                                 0.1s
 => [build 6/8] RUN apt-get -y update && apt-get -y install python3                      5.0s
 => [build 7/8] RUN npm install nexe -g                                                 28.5s
 => ERROR [build 8/8] RUN [ "nexe", "index.js", "--build", "-o test.exe", "--python p  127.9s
------
 > [build 8/8] RUN [ "nexe", "index.js", "--build", "-o test.exe", "--python python3", "--verbose" ]:
#0 1.003 - Starting...
#0 1.003 ℹ nexe 4.0.0-rc.2
#0 1.634 - nexe 4.0.0-rc.2
#0 93.07 ✔ Downloading Node: 100%...
#0 93.07 - Extracting Node...
#0 127.1 ✔ Extracting Node...
#0 127.1 - Node source extracted to: /root/.nexe/16.20.0
#0 127.1 - Node source extracted to: /root/.nexe/16.20.0
#0 127.1 ✔ Compiling result
#0 127.1 - Configuring node build: --dest-cpu=x64
#0 127.1   Configuring node build: --dest-cpu=x64
#0 127.2 Traceback (most recent call last):
#0 127.2   File "./configure.py", line 30, in <module>
#0 127.2     from gyp.common import GetFlavor
#0 127.2   File "tools/gyp/pylib/gyp/__init__.py", line 188
#0 127.2     return f"{opt}={value}"
#0 127.2                           ^
#0 127.2 SyntaxError: invalid syntax
#0 127.2 - Configuring node build: --dest-cpu=x64
#0 127.3 ✔ Configuring node build: --dest-cpu=x64
#0 127.3 - Finished in 126.25s
#0 127.3 ✔ Finished in 126.25s
#0 127.3 
#0 127.3 Error: python ./configure.py --dest-cpu=x64 exited with code: 1
#0 127.3 
#0 127.3 See nexe -h for usage..
#0 127.3 
------
failed to solve: executor failed running [nexe index.js --build -o test.exe --python python3 --verbose]: exit code: 1
```

**What you expected to happen**:
App gets bundled into binary and runs in docker container

**How to reproduce it (as minimally and precisely as possible)**:

Example simple node js express app

https://github.com/abhisheksurve45/nexe-test

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Mac OS 13.2.1 (22D68)
- Host Node Version: v16.16.0
- Target Node Version: v16.16.0
- Nexe version: 4.0.0-rc.2
- Python Version:

**Comment by abhisheksurve45** [comment]
Refer github action pipeline

https://github.com/abhisheksurve45/nexe-test/actions

**Comment by abhisheksurve45** [comment]
@calebboyd @bruce-one can someone please help?

**Comment by calebboyd** [comment]
You could try `--python=$(which python3)`

**Comment by abhisheksurve45** [comment]
Little bit confused about the python version, is it fine if I keep it above 3.6? @calebboyd

**Comment by abhisheksurve45** [comment]
@calebboyd I tried executing it with alpine image

https://github.com/abhisheksurve45/nexe-test/actions/runs/4622281135/jobs/8174763182

Getting this error now

```
m64 -Wall -O3 -Wno-missing-field-initializers -Wno-old-style-declaration -O3 -fno-omit-frame-pointer  -MMD -MF /root/.nexe/16.20.0/out/Release/.deps//root/.nexe/16.20.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/mem_sec.o.d.raw   -c
#20 608.6 ../deps/openssl/openssl/crypto/mem_sec.c:33:13: fatal error: linux/mman.h: No such file or directory
#20 608.6    33 | #   include <linux/mman.h>
#20 608.6       |             ^~~~~~~~~~~~~~
#20 608.6 compilation terminated.
#20 608.6 make[1]: *** [deps/openssl/openssl.target.mk:876: /root/.nexe/16.20.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/mem_sec.o] Error 1
#20 608.6 make: *** [Makefile:113: node] Error 2
#20 608.6 - Compiling Node...
#20 608.6 ✔ Compiling Node...
#20 608.6 - Finished in 608.162s
#20 608.6 ✔ Finished in 608.162s
#20 608.6 
#20 608.6 Error: make  exited with code: 2
```

**Comment by calebboyd** [comment]
It looks like some build dependencies are missing. If you're having trouble creating your own base builds you could look at using these remote builds https://github.com/urbdyn/nexe_builds

**Comment by bruce-one** [comment]
https://github.com/openssl/openssl/issues/7207#issuecomment-464515182 implies that `apk add linux-headers` might be what you're after; the builds in here use `apk add --no-cache curl make gcc g++ binutils-gold python linux-headers paxctl libgcc libstdc++ git vim tar gzip wget` if you wanted to try a bigger hammer and see if that gets it going (some of those won't be needed, but you could try adding them all, confirm if it works, and then remove things that aren't necessary)

But using the remote builds would be simpler :-)
