### ISSUE TITLE
node exe is unable find sqlite3

### ISSUE THREAD

**Issue by abhijitpatil181171** [nexe/nexe#1076]
**What happened**:
i have node backend with sqlite and when i create executable from that using nexe -i "server.js" -r "node_modules/**/*" -o "server.exe" -t x64-14.15.3 and run i get this issue

D:\backend-exe\Exe-debugger\bin\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → D:\backend-exe\Exe-debugger\build\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\build\Debug\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\build\Release\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\out\Debug\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\Debug\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\out\Release\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\Release\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\build\default\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\compiled\14.15.3\win32\x64\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\addon-build\release\install-root\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\addon-build\debug\install-root\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\addon-build\default\install-root\node_sqlite3.node
 → D:\backend-exe\Exe-debugger\lib\binding\node-v83-win32-x64\node_sqlite3.node
    at bindings (D:\backend-exe\Exe-debugger\bin\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (D:\backend-exe\Exe-debugger\bin\node_modules\sqlite3\lib\sqlite3-binding.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\backend-exe\Exe-debugger\bin\node_modules\sqlite3\lib\sqlite3.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    'D:\\backend-exe\\Exe-debugger\\build\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\build\\Debug\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\build\\Release\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\out\\Debug\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\Debug\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\out\\Release\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\Release\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\build\\default\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\compiled\\14.15.3\\win32\\x64\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\addon-build\\release\\install-root\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\addon-build\\debug\\install-root\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\addon-build\\default\\install-root\\node_sqlite3.node',
    'D:\\backend-exe\\Exe-debugger\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node'
  ]
}
**What you expected to happen**:
my exe is running in project folder but when i run in other folder location it is not running .so i want to run it at any temp location

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version):windows 
- Host Node Version:v18.12.0
- Target Node Version:v18.12.0
- Nexe version:4.0.0-rc.4
- Python Version:Python 3.10.6

**Comment by bruce-one** [comment]
Just confirming, are you distributing the relevant native module alongside the executable? It doesn't look like you are, but it's a requirement for native modules (https://github.com/nexe/nexe?tab=readme-ov-file#native-modules)

**Comment by rafa-br34** [comment]
Same problem here.
> Just confirming, are you distributing the relevant native module alongside the executable? It doesn't look like you are, but it's a requirement for native modules (https://github.com/nexe/nexe?tab=readme-ov-file#native-modules)
How would I go about doing that? I mean I have `--build -r "node_modules/**/*"` in the command for the build, but it didn't help with anything other than adding ~80mb for absolutely nothing.
The readme doesn't clarify where I can find the modules I should be redistributing.
