### ISSUE TITLE
Duplicate Data in Object Literal

### ISSUE THREAD

**Issue by kjlaw89** [nexe/nexe#124]
I managed to get my application to compile with nexe, but when I attempt to run it I'm treated with this error:

![nim_run_error](https://cloud.githubusercontent.com/assets/4183007/8781574/e3bf3944-2edd-11e5-881d-09a215003b06.png)

Here are the dependencies my application has:
- bhttp
- ini
- moment
- semver

I've had issues trying to get bhttp to work with certain things, so I'm guess it is the cause, but I'm not exactly sure why. Any help would be appreciated!

**Comment by jaredallard** [comment]
Seems to have something to do with unihandecode.js maybe? Not sure, could you please post some code you use? (feel free to jump on the gitter and PM me, if it needs to be private!)

**Comment by kjlaw89** [comment]
Definitely appears to be bhttp. Start a project and "npm install bhttp", then use this for your index.js:

    var bhttp = require ("bhttp");

    bhttp.get ("https://www.google.com", {}, function (err, response) {
        console.log (response.body.toString ());
    }

When you compile with nexe you'll get the error in the screenshot above.

**Comment by jaredallard** [comment]
Awesome, will look into tomorrow!

**Comment by kjlaw89** [comment]
Thanks! I look forward to a fix. Let me know if you need anything else

**Comment by jaredallard** [comment]
@kjlaw89 What command line do you use to invoke nexe, flags & etc. Also, what version of nexe? I presume the latest npm version, right?

**Comment by kjlaw89** [comment]
GIT repository version on nexe and the very basic: nexe -i index.js -o ./test

I've been trying to build on Linux, mostly Debian-based systems.

**Comment by jaredallard** [comment]
Alright, I reproduced it. It'll be quite the debugging, as I literally have no clue what's causing this. Will keep this thread posted on progress!

**Comment by kjlaw89** [comment]
@jaredallard have you had any luck so far? If I get a free moment I'll try to strip various parts of the bhttp library and see if I can narrow down the problem

**Comment by jaredallard** [comment]
Apologises, I was teaching a class the past week so I was a bit busier than I thought. That's over now, so I should have more time to dedicate. I've narrowed it down a bit more.

**Comment by kjlaw89** [comment]
It's no problem. Thanks for looking at it!

**Comment by kjlaw89** [comment]
@jaredallard It appears to be caused by the string.js (http://stringjs.com/) library, which surprisingly enough wasn't actually being used in BHTTP it appears. Not 100% on that just yet, but I'm not getting any errors associated with that. I did run into an issue where the errors library was relying on static content, but once I located that and put it in my root folder that error went away.

Now I'm left with a different exception: 

nexe.js:22502
                ? makeNodePromisified(key, THIS, key, fn, suffix)
                  ^
TypeError: undefined is not a function
    at promisifyAll (nexe.js:22502:19)
    at Function.Promise.promisifyAll (nexe.js:22548:13)
    at Array.call.C:\Users\Kevin\Documents\Work\NmmBroker\Message Broker\Node\node_modules\bhttp\node_modules\stream-length\lib\stream-length.js.fs (nexe.js:9602:14)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.C:\Users\Kevin\Documents\Work\NmmBroker\Message Broker\Node\node_modules\bhttp\node_modules\stream-length\index.js../lib/stream-length (nexe.js:9596:18)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.C:\Users\Kevin\Documents\Work\NmmBroker\Message Broker\Node\node_modules\bhttp\node_modules\form-data2\node_modules\combined-stream2\lib\combined-stream2.js.stream (nexe.js:5616:16)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.C:\Users\Kevin\Documents\Work\NmmBroker\Message Broker\Node\node_modules\bhttp\node_modules\form-data2\node_modules\combined-stream2\index.js../lib/combined-stream2 (nexe.js:5605:18)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call.C:\Users\Kevin\Documents\Work\NmmBroker\Message Broker\Node\node_modules\bhttp\node_modules\form-data2\lib\form-data2.js.path (nexe.js:5447:19)
    at initModule (nexe.js:29:11)

I'm looking into that one right now...

**Comment by jaredallard** [comment]
I ran into that originally. Hm. This is interesting.

**Comment by jaredallard** [comment]
Relevant lines in nexe.js:

```js
--23250--
var makeNodePromisified = canEvaluate
    ? makeNodePromisifiedEval
    : makeNodePromisifiedClosure;

function promisifyAll(obj, suffix, filter, promisifier) {
    var suffixRegexp = new RegExp(escapeIdentRegex(suffix) + "$");
    var methods =
        promisifiableMethods(obj, suffix, suffixRegexp, filter);

    for (var i = 0, len = methods.length; i < len; i+= 2) {
        var key = methods[i];
        var fn = methods[i+1];
        var promisifiedKey = key + suffix;
        obj[promisifiedKey] = promisifier === makeNodePromisified
                ? makeNodePromisified(key, THIS, key, fn, suffix)
                : promisifier(fn, function() {
                    return makeNodePromisified(key, THIS, key, fn, suffix);
                });
    }
    util.toFastProperties(obj);
    return obj;
}
--23271--
```

**Comment by jaredallard** [comment]
So, while expirementing with using browserify for stuff, simply -- I got it to work. However, it still needs those static files. What I'm going to introduce soon is the ability to wrap fs calls so that files could be, say, read from the embeded area. This could this sort of issue.

Keep a lookout for this, and when/if browserify is being used as the bundler. Until then, I suggest writing some code to create the files, and then also using browserify to generate your application i.e

```sh
browserify --node index.js > my-final-combined-file.js
nexe -i my-final-combined-file.hs -o ./app
./app # Yay, it runs, and everyone is happy for now
```

**Comment by jaredallard** [comment]
browserify is fully functional in the branch browserify, so you can use that, but it can't package nexe itself right now. But, like I said, it builds your application so that's something for now

**Comment by kjlaw89** [comment]
Interesting... well, I'll give it a shot and let you know how it turns out! Thanks for looking into this for me!

Just to note, nexe compiled another project I worked on with a native module and everything worked great - thanks for all of the work you put into this!

**Comment by jaredallard** [comment]
Hm, how'd it handle the native module? That's awesome to hear though! :smile:

**Comment by kjlaw89** [comment]
Well, in this case it was a native module I wrote. I just specified the path to my native module as being in the same directory as the main application, so as long as I package the .node files with it everything works fine. Probably doesn't hold up for everything, but it did for my use-case.

**Comment by jaredallard** [comment]
I'm glad that worked! When I find the timeframe I need I'll start working on native module built-in packaging. But the bigger issue right now is why doesn't some stuff work ;)

**Comment by deployable** [comment]
The browserify command above didn't quite fix my issue
```
browserify --node index.js > my-final-combined-file.js
nexe -i my-final-combined-file.hs -o ./app
```
This is fine and the binary works when executed in place but it appears to only pack `node_modules`. Relative includes like `require('./lib/a-module') look the still be referencing the files on disk. When I move the binary, it stop's working. 

Is there a way to tell browserify to include everything?

**Comment by deployable** [comment]
The `./lib` problem was down to using a `whatever = require('./lib/whatever').getSomething()` call.

Separating it out into two `Whatever = require('./lib/whatever'); whatever = Whatever.getSomething()` lines fixed the issue. 

Interesting to note, as that require+call setup is the standard work around for circular dependencies in node. It looked to be working with nexe's bundler as well.

**Comment by jaredallard** [comment]
Interesting. Hm.

**Comment by joepie91** [comment]
> @jaredallard It appears to be caused by the string.js (http://stringjs.com/) library, which surprisingly enough wasn't actually being used in BHTTP it appears.

Hi, `bhttp` developer here :)

`bhttp` does indeed use the string.js library, but only in one or two places. Did this end up being an issue with `bhttp` or string.js in the end? If so, I can have a look at getting it fixed.

**Comment by calebboyd** [comment]
Closing due to inactivity
