### ISSUE TITLE
import sys; print sys.byteorder + ReferenceError: pv is not defined

### ISSUE THREAD

**Issue by Grenadingue** [nexe/nexe#237]
Hi, I tried to install and use `nexe` for the first time today. While doing this steps I got the following errors:

```
$ sudo npm install -g nexe
```

```
$ cat index.js 
console.log('hello');
```

```
$ nexe -i ./index.js -o ./test --python /bin/python2.7
----> set python as /bin/python2.7
----> framework => nodejs
----> downloading https://nodejs.org/dist/node-latest.tar.gz
[====================================================================================================]
----> extracting the node source [native tar]
----> tar -xf /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/nodejs-latest.tar.gz -C /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest
----> embedResources undefined
----> resource -> /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/lib/nexeres.js
----> bundle /run/media/nicolas/TAF/test/node_compilation/index.js
----> executing browserify via API
----> monkey patch /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/node.gyp
....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'
----> monkey patch /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/lib/internal/bootstrap_node.js
----> monkey patch /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/lib/child_process.js
----> make
  File "<string>", line 1
    import sys; print sys.byteorder
                        ^
SyntaxError: invalid syntax
gyp: Call to 'python -c "import sys; print sys.byteorder"' returned exit status 1 while in /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/deps/v8/tools/gyp/v8.gyp. while loading dependencies of /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/node.gyp while trying to load /run/media/nicolas/TAF/test/node_compilation/tmp/nexe/nodejs/latest/node-v6.2.2/node.gyp
Error running GYP
creating  ./icu_config.gypi
* Using ICU in deps/icu-small
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'gas_version': '2.26',
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt57l.dat',
                 'icu_data_in': '../../deps/icu-small/source/data/in/icudt57l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '57',
                 'node_byteorder': 'little',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'false',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'target_arch': 'x64',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'false',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating  ./config.gypi
creating  ./config.mk
----> preparing python
----> patching Makefile
/usr/lib/node_modules/nexe/lib/exe.js:534
                pv = undefined;
                   ^

ReferenceError: pv is not defined
    at /usr/lib/node_modules/nexe/lib/exe.js:534:20
    at Array.forEach (native)
    at _loop (/usr/lib/node_modules/nexe/lib/exe.js:515:18)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nexe/lib/exe.js:580:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

```
$ /bin/python2.7 --version
Python 2.7.11
```

```
$ node-gyp --version
v3.3.1
```

```
$ uname -srm
Linux 4.6.2-1-ARCH x86_64
```

**Comment by jaredallard** [comment]
Weird, clearly something to do with either your python install or nodejs

**Comment by Grenadingue** [comment]
I got rid of the python error using this
```
$ find -type f -exec sed \
     -e 's_^#!/usr/bin/env python$_&2_' \
     -e 's_^\(#!/usr/bin/python2\).[45]$_\1_' \
     -e 's_^#!/usr/bin/python$_&2_' \
     -e 's_^\( *exec \+\)python\( \+.*\)$_\1python2\2_'\
     -e 's_^\(.*\)python\( \+-c \+.*\)$_\1python2\2_'\
     -e "s_'python2'_'python2'_" -i {} \;
$ find test/ -type f -exec sed 's_python _python2 _' -i {} \;
$ export PYTHON=python2
```
Found in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nodejs-git) file of the Archlinux `nodejs-git` package that build it from source

**Comment by x0x7** [comment]
Can confirm.  I ran with `-r6.3.0 -p /usr/bin/python2`

Interestingly the `pv` is used no where else in the file.  It may be a typo for `py`, but would still be an irrelevant line.  I commented it out and it ran without at least that issue.

The pv issue is unrelated to python or node version used because it is located in /usr/lib/node_modules/nexe/lib/exe.js.  It is a legitimate coding error.

The `import sys; print sys.byteorder` is a seperate issue.  It seems to relate to python3 being installed so the `-p` isn't being enforced.

Could I request, oh so nicely, that the python print statements be python3 compatable.  I'm willing to do the leg work if you'll accept the merge request.  It's been 8 years since python3 came out and new software hasn't been adopted almost purely over some parenthasises.  Then there will be less rush to fix the `-p` enforcement.

Just give me the go ahead.

**Comment by jaredallard** [comment]
@x0x7 That's actually node's issue, they're sticking with Python 2. I've fixed a lot of python issues in v2, sine we have to do a lot of "magic" to support custom version, so It'll be fixed eventually.

**Comment by Denommus** [comment]
I solved it by activating a virtualenv that uses Python 2.7

**Comment by jonataswalker** [comment]
I solved it by:

```shell
$ mkdir ~/bin
$ ln -s /usr/bin/python2 ~/bin/python
$ ln -s /usr/bin/python2-config ~/bin/python-config
```

**Comment by calebboyd** [comment]
Fixed in `nexe@beta`
