### ISSUE TITLE
"config" module can not work with "No such native module" error

### ISSUE THREAD

**Issue by hfcorriez** [nexe/nexe#242]
``` shell
> ./kb

nexe.js:20801
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/Users/hfcorriez/Code/lb-kb/config/default.js': Error: No such native module /Users/hfcorriez/Code/lb-kb/config/default.js
    at util.parseFile (nexe.js:20801:11)
    at nexe.js:20600:28
    at Array.forEach (native)
    at nexe.js:20596:14
    at Array.forEach (native)
    at util.loadFileConfigs (nexe.js:20595:13)
    at new Config (nexe.js:20033:27)
    at Object.__dirname.91.../defer (nexe.js:21614:31)
    at s (nexe.js:1:316)
    at nexe.js:1:367
```

**Comment by calebboyd** [comment]
This seems to work in 2.0 if the file is present. Please open a new issue if you have trouble using v2

**Comment by hfcorriez** [comment]
great!
