### ISSUE TITLE
No such native module jade

### ISSUE THREAD

**Issue by JoseExposito** [nexe/nexe#250]
Hi,

I'm having some issues compiling an Express.js app that uses Jade as the template engine.

First, the versions:

```
$ node --version
v6.4.0
$ nexe --version
1.1.2
$ python --version
Python 2.7.10

OS X El Capitan 10.11.6
```

I am using the same package.json configuration that is in the example: 
https://github.com/jaredallard/nexe/blob/master/test/express-test/package.json#L17

And compile my project by running:

```
$ nexe
```

When I run my application and load a page that should be rendered by Jade, I get this error in my browser:

```
Error: No such native module jade
   at NativeModule.require (bootstrap_node.js:435:13)
   at s (nexe.js:1:176)
   at nexe.js:1:367
   at new View (nexe.js:8220:30)
   at EventEmitter.render (nexe.js:4985:12)
   at ServerResponse.render (nexe.js:6709:7)
   at nexe.js:52:9
   at Layer.handle_error (nexe.js:7521:5)
   at trim_prefix (nexe.js:7113:13)
   at nexe.js:7083:7
```

And if I try to require('jade') as in the example project: 
https://github.com/jaredallard/nexe/blob/master/test/express-test/app.js#L7

I get this error in the command line when I try to run the server:

```
$ ./out.nex 
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at load_global (nexe.js:49633:30)
    at Array.forEach (native)
    at Object.<anonymous> (nexe.js:49659:7)
    at Object.__dirname.241.fs (nexe.js:49786:4)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.228../shared (nexe.js:47088:16)
    at s (nexe.js:1:316)
```

Any idea of why this could be happening?
Thank you very much in advance

**Comment by JoseExposito** [comment]
OK, I managed to Nexe using my package.json, this is the output:

```
----> make
creating  ./icu_config.gypi
* Using ICU in deps/icu-small
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'debug_devtools': 'node',
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt57l.dat',
                 'icu_data_in': '../../deps/icu-small/source/data/in/icudt57l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '57',
                 'llvm_version': 0,
                 'node_byteorder': 'little',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 48,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'true',
                 'node_use_etw': 'false',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'node_use_v8_platform': 'true',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': '48.dylib',
                 'target_arch': 'x64',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'true',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_inspector': 'true',
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0,
                 'xcode_version': '7.3'}}
creating  ./config.gypi
creating  ./config.mk
```

OS X El Capitan 10.11.6

If I try to load Jade dynamically, I get:

```
let jadeModuleName = 'jade'
let jade    = require(jadeModuleName)

bootstrap_node.js:435
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module jade
    at NativeModule.require (bootstrap_node.js:435:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.<anonymous> (nexe.js:10:15)
    at Object.__dirname.1../routes/index (nexe.js:61:4)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.2.../app (nexe.js:64:13)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)

```

**Comment by JoseExposito** [comment]
I can confirm that the same problem affects the express test example. Steps to reproduce it:

```
$ git clone https://github.com/jaredallard/nexe.git
$ cd nexe/test/express-test
$ vim bin/www # Remove the 2 final lines or the app will exit
# - process.stdout.write('true');
# - process.exit(0);
$ nexe
$ ./test.nex
```

When loading http://127.0.0.1:3000/ the web page will show:

```
Error: No such native module jade
   at NativeModule.require (node.js:337:13)
   at s (nexe.js:1:176)
   at nexe.js:1:367
   at new View (nexe.js:20509:30)
   at EventEmitter.render (nexe.js:17274:12)
   at ServerResponse.render (nexe.js:18998:7)
   at nexe.js:56:7
   at Layer.handle_error (nexe.js:19810:5)
   at trim_prefix (nexe.js:19402:13)
   at nexe.js:19372:7
```

**Comment by qlux** [comment]
Do you install packages `npm install` before running nexe ?

**Comment by JoseExposito** [comment]
Yes, I forgot to put that command in the steps to reproduce the issue.

I can confirm that the issue is present with all the template engines I tried: Jade, Pug and EJS

**Comment by qlux** [comment]
In my express app, I only have those lines and 'ejs' seems correctly packed:
```
var express = require('express');
require('ejs');
var app = express();
```
Dynamic require is not supported, have you tried just adding a require(__package__) in your main file. Maybe there is an issue because jade is called pug now ?

**Comment by JoseExposito** [comment]
Yes, still doing that I'm not able to fix the issue. I found a workaround though:
https://github.com/jaredallard/nexe/pull/252

**Comment by anmonteiro** [comment]
Aren't all your problems above already described in the Readme?!
- [Nexe doesn't support dynamic requires](https://github.com/jaredallard/nexe#doesnt-support-dynamic-require-statements)
- [require issues](https://github.com/jaredallard/nexe#browserify-require-issues)
