### ISSUE TITLE
LinvoDb3 error

### ISSUE THREAD

**Issue by michelem09** [nexe/nexe#260]
I can compile my code but when I execute the output file I have this error:

```
nexe.js:26163
    Error.captureStackTrace(this, arguments.callee)
                                           ^

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Error.CustomError (nexe.js:26163:44)
    at createError (nexe.js:26187:43)
    at ce (nexe.js:26193:12)
    at module.exports (nexe.js:26197:25)
    at Object.__dirname.97../custom (nexe.js:26514:44)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.95.errno (nexe.js:26128:21)
    at s (nexe.js:1:316)
    at nexe.js:1:367
```

Code `Error.captureStackTrace(this, arguments.callee)` come from [linvodb3](https://github.com/Ivshti/linvodb3) module

**Comment by jaredallard** [comment]
Seems like some issues with strict mode being globally enabled, not much that can be done right here, and may be browserify or not. Hard to tell.

**Comment by calebboyd** [comment]
closing, v2 beta has bring your own bundler to work around issues like this
