### ISSUE TITLE
No Such Native Module, compiling on Windows 10.

### ISSUE THREAD

**Issue by felanor** [nexe/nexe#282]
```js
bootstrap_node.js:461
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module C:\CascadeStation\node_modules\sqlite3\package.json
    at NativeModule.require (bootstrap_node.js:461:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.exports.find (nexe.js:131553:23)
    at Object.<anonymous> (nexe.js:131105:27)
    at Object.__dirname.393../trace (nexe.js:131292:4)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.477.aws-sdk (nexe.js:141986:15)
    at s (nexe.js:1:316)
```

Would be happy to help try and figure out what is causing this. Let me know what you need!

Andrew

**Comment by calebboyd** [comment]
He @felanor Please see the convo in #287
