### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by mavrick** [nexe/nexe#296]
Hey, I'm trying to load the file inside an Electron app and I'm getting this error:

```
App threw an error during load
Error: %1 is not a valid Win32 application.
\\?\C:\app\app.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\app\module.js:10:9)
```

My ``package.json`` has the ``nexe`` object:

```javascript
"nexe": {
    "input": "./index.js",
    "output": "./app.node",
    "temp": "/tmp",
    "browserify": {
        "requires": [],
        "excludes": [],
        "paths": []
    },
    "runtime": {
        "framework": "nodejs",
        "version": "6.9.4",
        "js-flags": "--use_strict",
        "ignoreFlags": true,
        "nodeVCBuildArgs": ["release","x64"]
    }
  }
```

I can't find any documentation on how to load the compiled binary properly.

If I just try to load it from node directly I get:

```
C:\app>node test
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\C:\app\app.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\app\test.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Any help would be greatly appreciated, cheers.

**Comment by calebboyd** [comment]
What is the code in `test`?

**Comment by mavrick** [comment]
@calebboyd 

```javascript
require("./app.node")
```

**Comment by calebboyd** [comment]
@mavrick Nexe builds an executable eg. The node runtime. 
It might not be the tool you're looking for

You're effectively doing `node -e "require('node.exe')"`
if `'node.exe'` were the result of running `C:\> where node`

The `dl.open` error occurs because the extension `.node` is used by require to load native node addons.

**Comment by CKarper** [comment]
Electron also has a packager you might be interested in.
https://github.com/electron-userland/electron-packager

**Comment by calebboyd** [comment]
If you're trying to execute a project built with nexe from within you're electron app, you can use the `child_process` module, methods `spawn` and friends.

**Comment by mavrick** [comment]
Thanks @CKarper 

@calebboyd I see, I think the ``child_process`` might be the way to go. 

The goal was to have core app functionality pre-compiled then bundled with the Electron app to provide some form of code obfuscation.

**Comment by calebboyd** [comment]
Ahh, I see, I'd note that code obfuscation it is not currently a goal of nexe. (it doesn't provide any, just a little obscurity)

**Comment by mavrick** [comment]
Thanks, I understand. 

Obscurity is definitely the better word for it. :) ``.asar`` files can be easily extracted so that's why I took an interest in ``nexe``
