### ISSUE TITLE
error when creating exe file

### ISSUE THREAD

**Issue by balasivagnanam** [nexe/nexe#305]
I am not able to execute the command and create an exe. not sure what is happening here.

```
C:\Codes\momtest0.5-enclose>nexe -i server.js -o dxd
----> framework => nodejs
----> downloading https://nodejs.org/dist/node-latest.tar.gz
[====================================================================================================]
----> extracting the node source [node-tar.gz]
----> extraction finished
----> embedResources undefined
----> resource -> C:\Codes\momtest0.5-enclose\tmp\nexe\nodejs\latest\node-v7.5.0\lib\nexeres.js
----> bundle C:\Codes\momtest0.5-enclose\server.js
----> executing browserify via API
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'v8-profiler' from 'C:\Codes\momtest0.5-enclose\node_modules\pm2\lib'
    at C:\Users\balas\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:47:17
    at process (C:\Users\balas\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:174:43)
    at ondir (C:\Users\balas\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:189:17)
    at load (C:\Users\balas\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:70:43)
    at onex (C:\Users\balas\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:93:31)
    at C:\Users\balas\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:23:47
    at FSReqWrap.oncomplete (fs.js:111:15)
```

**Comment by calebboyd** [comment]
The v8-profiler is a native module which isn't supported out of the box. You might have success following the suggestions in #287
