### ISSUE TITLE
ENOENT: no such file or directory, nexe.js?

### ISSUE THREAD

**Issue by maxgalbu** [nexe/nexe#324]
This is a
 - Bug Report

<br/>

Compiling a file, then running it, output this:

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/vagrant/deploy-front-ansible/library/../nexe.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (nexe.js:8:19)
    at Object.__dirname.1.fs (nexe.js:113:4)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:531:7)
    at Function.NativeModule.require (bootstrap_node.js:472:18)
    at Function.Module._load (module.js:427:25)
```

Nexe is run with `nexe -i versioning -o versioning-cli`

<br/>
Please also provide: 

- Platform(OS/Version): Centos 7
- Host Node Version: 6.10.1
- Target Node Version: 7.9.0
- Nexe version: 1.1.2
- Python Version: Python 2.7.5

**Comment by calebboyd** [comment]
Please try the latest version (2.0.0-rc.2)

**Comment by calebboyd** [comment]
Closing since, If you have an issue with the latest version please open a new issue
