### ISSUE TITLE
nexe Express4 

### ISSUE THREAD

**Issue by nareshtank001** [nexe/nexe#326]
This is a
 - [ ] Bug Report

I am getting this error on run build file.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Function.pkginfo.find (nexe.js:103704:16)
    at Function.pkginfo.read (nexe.js:103731:17)
    at module.exports (nexe.js:103681:21)
    at Object.__dirname.145../winston/common (nexe.js:44060:19)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.143.chalk (nexe.js:27593:15)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.601.../server/helpers/APIError (nexe.js:124963:24)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.1../server/server (nexe.js:4:13)
    at s (nexe.js:1:316)

<br/>
If this is a bug report, What are the steps to reproduce?

```
//provide configuration here
```

<br/><br/>

- Platform(OS/Version): Ubuntu
- Host Node Version: 6.3.0
- Target Node Version: 6.3.0
- Nexe version:1.1.2
- Python Version:2.7.6

**Comment by calebboyd** [comment]
Closing due to inactivity, Open a new issue with more detail if you're still having issues
