### ISSUE TITLE
typeerror: require is not a function

### ISSUE THREAD

**Issue by abdulazizjs** [nexe/nexe#329]
TypeError: require is not a function
    at Object.<anonymous> (D:\Davron aka\node\lesson7\routes\user.js:4:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Davron aka\node\lesson7\server.js:51:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

<br/>
var passportConf = require('../config/pass');
                   ^

```

var router = require('express').Router();
var User = require('../models/user');
var require = require('passport');
var passportConf = require('../config/pass');

router.get('/login', function(req, res){
  if(req.user) return res.redirect('/');
  res.render('accounts/login', { message: req.flash('loginMessage')});
});

router.post('/login', passport.authenticate('local-login', {
  successRedirect: '/profile',
  failureRedirect: '/login',
  failureFlash: true
}));
```

<br/><br/>

**Comment by calebboyd** [comment]
`var require = require('passport');`

^ require is not a function after you re-assign it to `require('passport')`

**Comment by abdulazizjs** [comment]
sorry as you said there was var require passport but still did not work

**Comment by calebboyd** [comment]
Please ensure your application runs with node.
