### ISSUE TITLE
iconv-lite warning: javascript files are loaded not with utf-8 encoding.

### ISSUE THREAD

**Issue by thbl** [nexe/nexe#334]
After complinig i get this error when running the app

```
iconv-lite warning: javascript files are loaded not with utf-8 encoding. See https://github.com/ashtuchkin/iconv-lite/wiki/Javascript-source-file-encodings for more info.
connected
nexe.js:19063
        throw new Error("Encoding '"+codecOptions.type+"' has incorrect 'chars' (must be of len 128 or 256)");
        ^

Error: Encoding '_sbcs' has incorrect 'chars' (must be of len 128 or 256)
    at new SBCSCodec (nexe.js:19063:15)
    at Object.getCodec (nexe.js:21799:25)
    at Object.getDecoder (nexe.js:21821:23)
    at Object.decode (nexe.js:21739:25)
    at nexe.js:71635:22
    at nexe.js:70277:9
    at Parser.awaitData (nexe.js:69988:9)
    at Parser.readBuffer (nexe.js:70274:12)
    at readChars (nexe.js:71634:19)
    at nexe.js:71445:20
```

i have converted all files to utf-8  but same error, what to do.. :s

**Comment by reinaldorauch** [comment]
I also have this issue. I thinl that when nexe packs the files it does not keep the utf8 encoding of them and thereof scrambles the way iconv-lite works as he keeps the non ascii characters on his source code.

**Comment by thbl** [comment]
try #304
solved my utf-8 issue

**Comment by calebboyd** [comment]
This should be resolved in v2. Please try -- open a new issue if you still have issues
