### ISSUE TITLE
Cannot get native modules to work with compiled app on Windows

### ISSUE THREAD

**Issue by JamesMGreene** [nexe/nexe#335]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

Try to build an application with `nexe` that requires the native module `zmq` (and thereafter sideload it).
Result: epic failures at runtime.

```
C:\git\Observer\Node\ObsNode>ObsNode.exe
nexe.js:3528
        throw e
        ^

Error: No such native module C:\git\Observer\Node\ObsNode\build\zmq.node
    at NativeModule.require (node.js:971:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at bindings (nexe.js:3521:44)
    at Object.__dirname.156.157.p.532.bindings (nexe.js:146691:30)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.156.157.p.531../lib (nexe.js:146684:18)
    at s (nexe.js:1:316)
    at nexe.js:1:367
```

Notable, you can also see that the path tried above by the nexe internals was "./build/zmq.node" rather than something like "./node_modules/zmq/build/Release/zmq.node"... for some reason...?

<br/><br/>
Current config, from `"package.json"`:

```
  "nexe": {
    "input": "app.js",
    "output": "ObsNode.exe",
    "temp": "tmp",
    "runtime": {
        "framework": "nodejs",
        "version": "4.8.3",
        "ignoreFlags": true
    },
    "browserify": {
      "excludes": [
        "bufferutil",
        "utf-8-validate",
        "memcpy"
      ]
    }
  }
```

<br/><br/>
Please also provide: 

- Platform(OS/Version): Windows 10
- Host Node Version: `4.8.3`
- Target Node Version: `4.8.3`
- Nexe version: `1.1.2`
- Python Version: `2.7.11`

<br/><br/>

### Attempted Workarounds

 1.  Excluding it from browserify in the `"nexe.browserify.excludes"` array in the `"package.json"` file
     - Build: success :+1:
     - Runtime: failure :-1:
```
C:\git\Observer\Node\ObsNode>ObsNode.exe
node.js:971
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module zmq
    at NativeModule.require (node.js:971:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.__dirname.155.156.p.488../http-status-messages (nexe.js:135805:11)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.155.156.p.540.../config (nexe.js:149103:21)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.155.156.p.550.../common/constants (nexe.js:150220:11)
```

 2. Changing the `require('zmq')` to `global.require('zmq')`
     - Build: success :+1:
     - Runtime: failure :-1:
```
C:\git\Observer\Node\ObsNode>ObsNode.exe
C:\git\Observer\Node\ObsNode\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: %1 is not a valid Win32 application.
\\?\C:\git\Observer\Node\ObsNode\node_modules\zmq\build\Release\zmq.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (C:\git\Observer\Node\ObsNode\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\git\Observer\Node\ObsNode\node_modules\zmq\lib\index.js:6:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

 3. Changing the `require('zmq')` to `global.require('zmq')` **AND** excluding it from browserify in the `"nexe.browserify.excludes"` array in the `"package.json"` file
     - Build: success :+1:
     - Runtime: failure :-1:
```
C:\git\Observer\Node\ObsNode>ObsNode.exe
C:\git\Observer\Node\ObsNode\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: %1 is not a valid Win32 application.
\\?\C:\git\Observer\Node\ObsNode\node_modules\zmq\build\Release\zmq.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (C:\git\Observer\Node\ObsNode\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\git\Observer\Node\ObsNode\node_modules\zmq\lib\index.js:6:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

 4. Changing the `require('zmq')` to a dynamic require per the README, e.g. `var m = 'zmq'; if ( Math.random() > 1 ) { m = 'FAKE'; } var zmq = require(m);`
     - Build: success :+1:
     - Runtime: failure :-1:
```
C:\git\Observer\Node\ObsNode>ObsNode.exe
node.js:971
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module zmq
    at NativeModule.require (node.js:971:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.__dirname.155.156.p.488../http-status-messages (nexe.js:135808:11)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.155.156.p.540.../config (nexe.js:149107:21)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.155.156.p.550.../common/constants (nexe.js:150224:11)
```

So, suffice to say, I'm currently at a total loss on how to supposedly get side-loaded native modules working with a `nexe`-compiled application.  Please help!  Thanks in advance.

**Comment by calebboyd** [comment]
@JamesMGreene Wow! great details on what you tried. I'll defer to my comment in #308 for what is currently being done about this issue in general. 

To help you where you're at... You can combine your tries 2 and 6 and you should have success. Please let me know if you dont!

**Comment by JamesMGreene** [comment]
@calebboyd: So that still did not do the trick. I again end up with the error:

```
C:\git\Observer\Node\ObsNodeExe>ObsNode.exe
C:\git\Observer\Node\ObsNodeExe\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: %1 is not a valid Win32 application.
\\?\C:\git\Observer\Node\ObsNodeExe\node_modules\zmq\build\Release\zmq.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (C:\git\Observer\Node\ObsNodeExe\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\git\Observer\Node\ObsNodeExe\node_modules\zmq\lib\index.js:6:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

But then it dawned on me that I don't _**WANT**_ it to be a valid 32-bit application... I want it to be a valid 64-bit application!

I tried adding the following (which I swear I saw somewhere in the docs/issue tracker but cannot seem to find now) into my `nexe` config in the "package.json" file but it also did not seem to have a sufficient enough (if any) effect:

```
"nodeVCBuildArgs": [ "x64" ]
```

Finally, I manually hacked `"x64"` as a final entry on nexe's arguments to vcBuild in the ["exe.js" file](https://github.com/nexe/nexe/blob/v1.0.6/lib/exe.js#L423) (added right after the `"release"` argument).

And _that_ did the trick!

So, that leads me to the next question: how can I achieve this result with my 64-bit application build without hacking nexe?  It looks like you have added exactly this capability into the current "master" branch with the [new `vcBuild` option](https://github.com/nexe/nexe/blob/cac2759d3a0f672e38676c61618176e7703e6f41/README.md#options) but that is, as of yet, unpublished, even as a beta.  I'd rather not point to a given SHA/master branch of nexe for installation.  Do you have an ETA on a beta release?

**Comment by JamesMGreene** [comment]
Additional question:
We are lucky in that our product currently only has a dependency on a single native module (zmq), and that we directly reference that in our app.

If a native module was indirectly required, i.e. by some dependency of ours beyond our control, how would we get it to compile correctly if their code did not already use `global.require` (which is highly unlikely)?

**Comment by calebboyd** [comment]
> Do you have an ETA on a beta release?

A beta release would break your current build in different ways. See below. 
I'm surprised the nodeVCBuildArgs option did not work. I'd **try deleting the source and temp files** and running it with the options: `['release', 'nosign', 'x64']`

Great questions. I'm glad you figured out the build option. I'm sorry I didn't make note of the default ia32 build configuration. I think i'll add x64 as a default in the mainline... I've noticed its a common theme when helping with these issues.

So in 2.0, bundling will be decoupled. This is to allow for choice, maybe someone uses rollup, or webpack. Right now the built in bundler in 1.X uses browserify, in 2.0 (master) uses webpack, which breaks your global.require workaround.

My plan is to switch bundlers yet again, to use fuse-box. It has a pretty flexible plugin api that will allow detecting usages of the `bindings` module (within any module), and dynamically rewrite it to a raw require statement.

An additional plugin will load any `.node` file that is required into memory, which will be written alongside process.execPath at runtime, and then loaded via the normal dlopen method in node.

This approach does not work for instant builds across platforms, so I'll have to have a way to pass a pre-built binary for a specific native module so we can keep this feature with instant builds.

So the end state i'm working towards (whenever I have enough free time) is 
`nexe --native zmq`

This should deliver a mechanism that just works for native modules.

**Comment by calebboyd** [comment]
Also, nice to here you're delivering a product with nexe. Some of the alternatives to this project don't allow you to sign the executable, which is fine for development. but hazardous in the wild

**Comment by JamesMGreene** [comment]
@calebboyd: Which alternatives have issues with signing?  The only notable one I've seen is [`pkg`'s issue with signing, limited to MacOSX](https://github.com/zeit/pkg/issues/66)... I'm only distributing for Windows, so I can conveniently ignore that particular issue. 😊

**Comment by calebboyd** [comment]
(xbin)[github.com/calebboyd/xbin] and pkg (and enclose) all use a similar method that basically concatenates the code or heap onto the end of a compiled node runtime. The result is fast builds, but the file headers are inherently incorrect since the length is longer than it is supposed to be. (something that is basically asserted when signing)

I've observed that sometimes the code or payload would just drop off the binary, leaving you with an empty runtime.

**Comment by calebboyd** [comment]
pending https://github.com/fuse-box/fuse-box/issues/648

**Comment by calebboyd** [comment]
@JamesMGreene I think i'll work on getting the beta released without built in bundling, and provide a suggested configuration, prior to having it baked in

**Comment by calebboyd** [comment]
@JamesMGreene The examples/native-build should provide everything you need to get going :)

**Comment by JamesMGreene** [comment]
FYI for anyone else looking, @calebboyd means this: [examples/native-build/](https://github.com/nexe/nexe/tree/master/examples/native-build)

**Comment by JamesMGreene** [comment]
@calebboyd: So I was thinking it would be lovely if we could make nexe auto-detect native modules.  I know that some may still require additional configuration if they need to chain-load other DLLs and such but others would not.

Seems like we could use something like the [logic from inside of the `native-modules` module](https://github.com/juliangruber/native-modules/blob/1c8729403b01ab706729634fec34374980bec38b/index.js) to auto-detect all of the native modules installed and do some first-round configuration with that info.

**Comment by calebboyd** [comment]
Yeah that is a logical evolution of this. like you observed its slightly more complicated with something like `zmq` because of the external dll dependency -- but perhaps that can be derived from the binding.gyp file...

**Comment by calebboyd** [comment]
@JamesMGreene Let me know if we can close this. We can add a new issue (or PR 😉 ) for the feature request

**Comment by JamesMGreene** [comment]
I should be able to test this out some time next week if not sooner.

**Comment by JamesMGreene** [comment]
No-go over here, @calebboyd. I used the "native-build" example directory and modified it a bit to work without being in `nexe` core but the resulting "app.exe" fails immediately on startup:

![image](https://user-images.githubusercontent.com/417751/28480639-40f58994-6e27-11e7-8eba-020e1430918d.png)

You can get all the files and more info on the process output on my new gist:  https://gist.github.com/JamesMGreene/70be6f28fc3fa6875270640c5bc41d82

**Comment by JamesMGreene** [comment]
On the plus side, it **does** seem like your FuseBox `NativeModulePlugin` does its job (the ZMQ assets were definitely bundled into the resulting "build.js" file).

**Comment by calebboyd** [comment]
Hey @JamesMGreene. Just getting back at it.
You should upgrade fuse-box to >=2.2.1 I think I jumped the gun on the version in the example.

Also remember that you need to build the correct node architecture with whatever native module is installed. eg. `--vcBuild x64 --vcBuild  release --vcBuild nosign` (if your hose node version installing/building zmq is 64 bit)

**Comment by JamesMGreene** [comment]
@calebboyd: I'm pretty sure your `fuse-box` version selection was accurate but I was already using the updated `2.2.1` version with the same issues resulting.  Again, AFAICT, the bundled output looks correct but the compiling is failing.

**Comment by calebboyd** [comment]
Is there any error output, how does it fail?

**Comment by JamesMGreene** [comment]
Only what I included in the original gist linked to above: https://github.com/nexe/nexe/issues/335#issuecomment-317103599

**Comment by calebboyd** [comment]
Okay, I think that my previous message applies then. (I'm sorry the example I created is so wrong -- But thats why we have a beta 😛 )

Change your npm `build-windows` script to: 
`"nexe --build -i app.js -o app.exe --vcBuild x64 --vcBuild nosign --vcBuild release"`

Before you build delete the temp directory first

**Comment by calebboyd** [comment]
TODO: document `native` configuration option
