### ISSUE TITLE
Cannot find module 'C:\Users\sttc\AppData\Roaming\npm\node_modules\nexe\index.js'

### ISSUE THREAD

**Issue by Tchoumi** [nexe/nexe#353]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

I was trying to build with:
```javascript
log4js = require('log4js');
log4js.configure({
    appenders:{ startBroker:{type:'file',filename:'Mosca.log'}},
    categories:{default:{appenders:['startBroker'],level:'info'}}
})
logger = log4js.getLogger('start apps');
logger.info('hello apps');
```
with this CLI: 
```sh
nexe -i indexe.js -o logging.exe --version 8.0.0.
```
but i am getting:
```sh
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\sttc\AppData\Roaming\npm\node_modules\nexe\index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Please also provide: 

- Platform(OS/Version): Windows 10
- Host Node Version: v8.2.1
- Target Node Version:
- Nexe version: beta
- Python Version: 2.7

**Comment by calebboyd** [comment]
> `nexe -i indexe.js -o logging.exe --version 8.0.0.`

did you mean `index.js`?  -- also `8.0.0.` isn't a valid version (`8.0.0` is)

**Comment by calebboyd** [comment]
Closing due to inactivity, If you're still having an issue with the latest rc, please comment what you see and I'll re-open
