### ISSUE TITLE
On win10 OS, error(module.js:472) when run exe

### ISSUE THREAD

**Issue by songhongjiang** [nexe/nexe#357]
E:\projects\svnprjs\SC>test1.exe
module.js:472
    throw err;
    ^

Error: Cannot find module './lib/BufferMaker'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at s ([eval]:1:114)
    at [eval]:1:305
    at Object.19 ([eval]:3186:18)
    at s ([eval]:1:254)
    at [eval]:1:305
    at Object.78.../codec ([eval]:15623:19)

Please help! Thanks in advance.

**Comment by calebboyd** [comment]
Please correctly fill out the issue template so I can help you better.

**Comment by calebboyd** [comment]
Closing, Please reopen if you want to continue troubleshooting
