### ISSUE TITLE
Error on module.js:471 when compiling 

### ISSUE THREAD

**Issue by gabrielsorsrg** [nexe/nexe#367]
I created a file with a small example that I would like to compile using NEXE, but I did not succeed.

No matter the way I run it always results in an error.

I installed NEXE using npm according to the documentation.

Example:

```
    C:\node>nexe -i index.js -o test.exe
module.js:471
    throw err;
    ^

Error: Cannot find module 'index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (C:\Users\gabri\AppData\Roaming\npm\node_modules\nexe\bin\nexe:101:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```
Node version:

```
C:\node>node --version
v6.11.2
```
What's missing for NEXE work? I'm working on windows 10.

Here is my index.js:
```

console.log("running...");

var a = 1;
var b = 2;
var c = a+b;
console.log(c);
```
And my package.json:

```
{
  "name": "",
  "version": "1.0.0",
  "description": "test..",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "programa",
    "testes"
  ],
  "author": "ninguem",
  "license": "ISC",
  "nexe": {
    "input": "./bin/nexe",
    "output": "nexe^$",
    "temp": "src",
    "browserify": {
        "requires": [],
        "excludes": [],
        "paths": []
    },
    "runtime": {
        "framework": "node",
        "version": "5.6.0",
        "js-flags": "--use_strict",
        "ignoreFlags": true
    }
  }
}
```
Any suggestion?

**Comment by calebboyd** [comment]
Please take a look at version 2 and let me know if you still have trouble

**Comment by gabrielsorsrg** [comment]
Yes, i'm install using "npm i nexe@beta -g" and it works, thanks!
