### ISSUE TITLE
Express - Cannot find module 'ms'

### ISSUE THREAD

**Issue by Grewamor** [nexe/nexe#379]
This is a
 - [x] Bug Report

```
console.log('log1');
const express = require('express');
console.log('log2');
```

```
log1
module.js:487
    throw err;
    ^

Error: Cannot find module 'ms'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at u (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:96230:1092)
    at f (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:96230:1430)
    at c (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:96230:2468)
    at w.require (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:96230:3065)
    at Number.<anonymous> (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:6475:20)
    at c (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:96230:3281)
```

Does anybody has an idea?
<br/><br/>

- Express: 4.15.4
- Platform(OS/Version): Win10 64
- Host Node Version: 8.2.1
- Target Node Version: 8.2.1
- Nexe version: 2.0.0-rc.4
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
Hmm.. `npm i` ?
I can't replicate this
![image](https://user-images.githubusercontent.com/5818726/30407256-c4d08f06-98bc-11e7-9260-568d5dadb057.png)

**Comment by Grewamor** [comment]
i deletet the .nexe und node_modules folder and the error was away.
Thank you again.

**Comment by ofarukcaki** [comment]
From where you deleted .nexe folder? I'm getting the same error
