### ISSUE TITLE
mssql - Error: Cannot find module 'process-nextick-args'

### ISSUE THREAD

**Issue by Grewamor** [nexe/nexe#382]
This is a
 - [x] Bug Report

<br/>
The hopfully last error in my project:<br/>
Package: https://www.npmjs.com/package/mssql (4.0.4) <br/><br/>

```
console.log('sql1');
const sql = require('mssql');
console.log('sql2');
```

```
sql1
module.js:487
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at u (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:88995:1092)
    at f (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:88995:1430)
    at c (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:88995:2468)
    at w.require (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:88995:3065)
    at Number.<anonymous> (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:84621:23)
    at c (C:\xampp\htdocs\Transaktionsserver2\ts2.exe:88995:3281)
```

<br/>
Can anybody help me again, please? :-)<br/><br/>

- Platform(OS/Version): Win10 64
- Host Node Version: 8.2.1
- Target Node Version: 8.2.1
- Nexe version: 2.0.0-rc.6
- Python Version:  2.7.13

**Comment by calebboyd** [comment]
I can't replicate this. Does it work if you run that file with `node` ?

**Comment by calebboyd** [comment]
![image](https://user-images.githubusercontent.com/5818726/30460986-29e02d84-9980-11e7-8028-3121fcbe8a8f.png)


Comment if you find its something else..
