### ISSUE TITLE
cannot find module 'request'

### ISSUE THREAD

**Issue by jokyme** [nexe/nexe#406]
This is a Bug Report

```Javascript
const request = require('request');
```
```
module.js:491
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Source_Code\crawler-updator\nexe_1507561837620.exe:1:177)
    at Module._compile (module.js:573:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:586:7)
    at Function.NativeModule.require (bootstrap_node.js:531:18)
    at bootstrap_node.js:92:22
```

- Platform(OS/Version): win10 x64
- Host Node Version: v8.4.0
- Target Node Version: v8.4.0
- Nexe version: 2.0.0-r11
- Python Version: 2.7

**Comment by calebboyd** [comment]
I don't have any issues using `nexe@beta`

**Comment by jokyme** [comment]
@calebboyd The problem seems to be gone. 
but another problem is, when i compile my project using `cat app.js | nexe -t x86-8.6.0` with PowerShell, and execute the 'app.exe', it's throw an error:
（i used async/await in my project）

```module.js:529
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Source_Code\crawler-node\app.exe:1:175)
    at Module._compile (module.js:624:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:595:7)
    at Function.NativeModule.require (bootstrap_node.js:540:18)
    at bootstrap_node.js:116:22```

and when i compile my project using `nexe app.js -t windows-x86-8.4.0` with cmd.exe, and execute the 'app.exe', it's throw another error:
``` app.exe:85795
                throw new DetailedError('No editions were specified:', { opts: opts });
                ^

Error: No editions were specified:
opts: { cwd: './',
  require:
   { [Function]
     main:
      Module {
        id: 'C:\\Source_Code\\crawler-node\\app.exe',
        exports: [Object],
        parent: null,
        filename: null,
        loaded: true,
        children: [Array],
        paths: [] } },
  package: 'crawler-node' }
    at new DetailedError (C:\Source_Code\crawler-node\app.exe:85654:109)
    at requireEditions (C:\Source_Code\crawler-node\app.exe:85795:9)
    at Object.requirePackage (C:\Source_Code\crawler-node\app.exe:85833:9)
    at Number.<anonymous> (C:\Source_Code\crawler-node\app.exe:85619:38)
    at c (C:\Source_Code\crawler-node\app.exe:85846:3281)
    at w.require (C:\Source_Code\crawler-node\app.exe:85846:3065)
    at Number.<anonymous> (C:\Source_Code\crawler-node\app.exe:85554:26)
    at c (C:\Source_Code\crawler-node\app.exe:85846:3281)
    at w.require (C:\Source_Code\crawler-node\app.exe:85846:3065)
    at Object.start (C:\Source_Code\crawler-node\app.exe:342:9) ```

**Comment by calebboyd** [comment]
stdin assumes you're piping a bundle.

**Comment by calebboyd** [comment]
If you want to look at the bundle output you can use `--debugBundle bundle.js`

**Comment by jokyme** [comment]
@calebboyd Thanks for your quick reply!
but it seems not work, i have tried `app.exe --debugBundle bundle.js` and `nexe app.js -t windows-x86-8.4.0 --debugBundle bundle.js`, and no bundle output

**Comment by calebboyd** [comment]
Hmm... you don't see a bundle.js emitted? I can't replicate that.

**Comment by jokyme** [comment]
@calebboyd well, I see the bundle.js now.
I delete the node_modules folder and reinstalled all the modules using `npm install`.
( I was install modules using `cnpm install`, may be it's not work well with nexe )

then, I rebuild my project with nexe. and execute the app.exe.
I get another error:

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'hoek'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at u (C:\Source_Code\crawler-node\app.exe:86264:1092)
    at f (C:\Source_Code\crawler-node\app.exe:86264:1430)
    at c (C:\Source_Code\crawler-node\app.exe:86264:2468)
    at w.require (C:\Source_Code\crawler-node\app.exe:86264:3065)
    at Number.<anonymous> (C:\Source_Code\crawler-node\app.exe:15093:14)
    at c (C:\Source_Code\crawler-node\app.exe:86264:3281)
```

it's my package.json:
```javascript
{
  "name": "crawler-node",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "crawler"
  ],
  "author": "joky",
  "license": "ISC",
  "dependencies": {
    "ali-oss": "^4.10.1",
    "async": "^2.5.0",
    "co": "^4.6.0",
    "getmac": "^1.2.1",
    "log4js": "^2.3.4",
    "phantom": "^4.0.5",
    "request": "^2.83.0",
    "superagent": "^3.6.3",
    "uuid": "^3.1.0"
  }
}
```

**Comment by calebboyd** [comment]
Did you find the issue?

**Comment by jokyme** [comment]
nope, I'm used the pkg to compile my project, and everything is ok now...

**Comment by dasDaniel** [comment]
same here, no issues with pkg, but the file size is rather large (more than double of nexe)

**Comment by calebboyd** [comment]
Pkg does not make an effort to statically analyze dependencies so instead of producing a bundle it includes the majority of the filesystem under node_modules (eg. `node_modules/**/**`). Most of the problems you'll run into with nexe will be related to bundling. Which can be customized using

`--bundle ./my-bundle-script`

**Comment by xileftenurb** [comment]
I got a similar issue. I have to manually install the module "hoek" for the executable to work.
my program work just fine without the compilation. after the compilation, if the module "hoek" is not there, the .exe fail. 

took some time to find out it was this module. the error was only showing in a console in a split of a second before closing.

somebody know what is this module and why it's needed in compiled version only?
