### ISSUE TITLE
Add possibility to require things from actual filesystem

### ISSUE THREAD

**Issue by mika-fischer** [nexe/nexe#408]
This is a
 - [ ] Bug Report
 - [X] Feature Request
 - [ ] Other

<br/>

We're currently bundling our application into a single js file but leave out all of node_modules.

Now I'd like to create an executable out of the js file with nexe and deploy that along with the node_modules folder.

Unfortunately, the executable does not look in the actual filesystem anymore, just inside the executable. Therefore this approach cannot work currently.

**Comment by calebboyd** [comment]
Hmmm.. This is actually a bug.

**Comment by calebboyd** [comment]
@mika-fischer A workaround for you:
`process.env.NODE_PATH = path.join(path.dirname(process.execPath), 'node_modules')`

**Comment by mika-fischer** [comment]
Unfortunately, that does not seem to work:
```js
const {statSync} = require('fs');
const {dirname, join} = require('path');
process.env.NODE_PATH = join(dirname(process.execPath), 'node_modules');
console.log(process.env.NODE_PATH);
console.log(statSync(join(process.env.NODE_PATH, 'source-map-support')).isDirectory());
require('source-map-support').install()
```
gives
```
C:\Users\mfischer\src\tests\nexe-nobundle>.\node_modules\.bin\nexe --no-bundle index.js && nexe-nobundle.exe
i nexe 2.0.0-rc.14
√ Compiling result
√ Entry: 'index.js' written to: nexe-nobundle.exe
√ Finished in 0.055s
C:\Users\mfischer\src\tests\nexe-nobundle\node_modules
true
module.js:529
    throw err;
    ^

Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\mfischer\src\tests\nexe-nobundle\nexe-nobundle.exe:12:1)
    at Module._compile (module.js:624:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:595:7)
    at Function.NativeModule.require (bootstrap_node.js:540:18)
    at bootstrap_node.js:116:22
```

**Comment by calebboyd** [comment]
Ahh, that workaround isn't working in combination with --no-bundle. I'll have to dig in a bit more to figure out the issue.
