### ISSUE TITLE
TypeError: require.resolve is not a function

### ISSUE THREAD

**Issue by Ciboulette** [nexe/nexe#410]
I am using nexe version 2.0.0-rc.11 and node v6.11.3. I have the error below with this require in my code: 
`const request = require('sync-request');`

Do you know how can i manage this ? 

```
let args = [require.resolve('./lib/legacy-worker')];
                    ^

TypeError: require.resolve is not a function
    at Number.<anonymous> (/Users/louiscibot/zenaton/zenaton-cli/test:24:21)
    at c (/Users/louiscibot/zenaton/zenaton-cli/test:363:3281)
    at w.require (/Users/louiscibot/zenaton/zenaton-cli/test:363:3065)
    at Number.<anonymous> (/Users/louiscibot/zenaton/zenaton-cli/test:7:17)
    at c (/Users/louiscibot/zenaton/zenaton-cli/test:363:3281)
    at Function.r.import (/Users/louiscibot/zenaton/zenaton-cli/test:363:3747)
    at /Users/louiscibot/zenaton/zenaton-cli/test:360:15
    at Object.<anonymous> (/Users/louiscibot/zenaton/zenaton-cli/test:363:1)
    at Module._compile (module.js:570:32)
    at _third_party_main.js:45:20
```

**Comment by calebboyd** [comment]
Hi @Ciboulette requires.resolve isn't supported (yet) However, taking a quick look at the code for this module -- it doesn't look like it would be able to work with a nexe executable anyway. The reason is that the module utilizes `spawnSync` on `process.execPath`. 

`process.execPath` is `~/bin/node` or `node.exe` normally, but in nexe this is _your_ executable. (eg. not node).

If you really need to perform a synchronous request I'd look at providing an alternate command to your application using execFileSync

```javascript
//my-app.js
function syncRequest (req) {
  return JSON.parse(child_process.execFileSync(process.execPath, ['sync-request', req]).toString())
}

if (process.argv[1] === 'sync-request') {
  request(...).then(x => {
    console.log(JSON.stringify(x))
    process.exit(0)
  })
} else {
 //normal application startup
}

```

**Comment by calebboyd** [comment]
Closing, and marking as wont-fix because of the above explanation. Let me know if you think it should be reopened.
