### ISSUE TITLE
Using log4js with nexe

### ISSUE THREAD

**Issue by tm1000** [nexe/nexe#414]
This is a Bug Report
```
npm install log4js
```

Add inside test.js
```
log4js = require('log4js');
log4js.configure({
    appenders:{ startBroker:{type:'file',filename:'Mosca.log'}},
    categories:{default:{appenders:['startBroker'],level:'info'}}
});
logger = log4js.getLogger('start apps');
logger.info('hello apps');
```

Build:
```
[root@machine node]# nexe test.js
ℹ nexe 2.0.0-rc.16
✔ Downloading...100%
✔ Entry: 'test.js' written to: test
✔ Finished in 15.118s
```

Results in strange errors
```
[root@machine node]# ./test
/usr/src/machine/zulu/node/test:340
      throw new Error(
      ^

Error: Problem reading log4js config { appenders: { startBroker: { type: 'file', filename: 'Mosca.log' } },
  categories: { default: { appenders: [Array], level: 'info' } } }. Error was "appenderList.forEach is not a function" (TypeError: appenderList.forEach is not a function
    at configureAppenders (/usr/src/machine/zulu/node/test:272:18)
    at configureOnceOff (/usr/src/machine/zulu/node/test:332:7)
    at Object.configure (/usr/src/machine/zulu/node/test:395:3)
    at Number.<anonymous> (/usr/src/machine/zulu/node/test:12:8)
    at c (/usr/src/machine/zulu/node/test:2684:3333)
    at Function.r.import (/usr/src/machine/zulu/node/test:2684:3857)
    at d (/usr/src/machine/zulu/node/test:2681:15)
    at Object.<anonymous> (/usr/src/machine/zulu/node/test:2684:1)
    at Module._compile (module.js:573:30)
    at _third_party_main.js:45:20)
    at configureOnceOff (/usr/src/machine/zulu/node/test:340:13)
    at Object.configure (/usr/src/machine/zulu/node/test:395:3)
    at Number.<anonymous> (/usr/src/machine/zulu/node/test:12:8)
    at c (/usr/src/machine/zulu/node/test:2684:3333)
    at Function.r.import (/usr/src/machine/zulu/node/test:2684:3857)
    at d (/usr/src/machine/zulu/node/test:2681:15)
    at Object.<anonymous> (/usr/src/machine/zulu/node/test:2684:1)
    at Module._compile (module.js:573:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:586:7)
```

<br/><br/>
Please also provide:

- Platform(OS/Version): CentOS 7
- Host Node Version: 8.4.0
- Target Node Version: 8.4.0
- Nexe version: 2.0.0-rc.16
- Python Version: 2.7.5

**Comment by calebboyd** [comment]
Change test.js to 

```javascript
log4js = require('log4js');
require('log4js/lib/appenders/file')
require('log4js/lib/appenders/stdout')
log4js.configure({
    appenders:{ startBroker:{type:'file',filename:'Mosca.log'}},
    categories:{default:{appenders:['startBroker'],level:'info'}}
});
logger = log4js.getLogger('start apps');
logger.info('hello apps');
```

And it should work for you.

**Comment by tm1000** [comment]
@calebboyd So what has to happen is I have to declare any child requires. EG if log4js requires something else then I have to require that higher up?

**Comment by calebboyd** [comment]
`log4js` dynamically requires its "appenders" based on the configuration. So there is no way to bundle that. Declaring it ahead of time (before configuration) causes it to be included in the bundle
