### ISSUE TITLE
[Bug] Acorn error: Invalid number

### ISSUE THREAD

**Issue by PMExtra** [nexe/nexe#417]
Error when compile the [keypress](https://www.npmjs.com/package/keypress).

Command: `npm run build && nexe build/main.js -o dist/main`, error log:

```
 nexe 2.0.0-rc.17
Acorn error: Invalid number (374:30)
File: /mosaic/node_modules/co-prompt/node_modules/keypress/index.js

372      var s = key.sequence;
373      var b = s.charCodeAt(3);
374      key.x = s.charCodeAt(4) - 040;
375      key.y = s.charCodeAt(5) - 040;
376
377      key.scroll = 0;
378

Acorn error: Invalid number (374:30)
File: /mosaic/node_modules/co-prompt/node_modules/keypress/index.js

372      var s = key.sequence;
373      var b = s.charCodeAt(3);
374      key.x = s.charCodeAt(4) - 040;
375      key.y = s.charCodeAt(5) - 040;
376
377      key.scroll = 0;
378


⠋ nexe 2.0.0-rc.17undefined
✔ Downloading...100%
✔ Entry: 'build/main.js' written to: dist/main
✔ Finished in 14.207s
```

When I run the `./dist/main`, the error output:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at u (/mosaic/dist/main:112:1092)
    at f (/mosaic/dist/main:112:1430)
    at c (/mosaic/dist/main:112:2520)
    at y.require (/mosaic/dist/main:112:3117)
    at Number.<anonymous> (/mosaic/dist/main:15:17)
    at c (/mosaic/dist/main:112:3333)
```

<br/><br/>
Please also provide:

- Platform(OS/Version): macOS 10.12
- Host Node Version: v6.11.1
- Target Node Version:
- Nexe version: 2.0.0-rc.17
- Python Version: 2.7.10

**Comment by LWTechGaming** [comment]
Getting this too on a different module, that being `mkdirp`.

**Comment by calebboyd** [comment]
@PMExtra It looks like there might be an open PR on keypress https://github.com/TooTallNate/keypress/pull/21

@LWTechGaming If you are able to update mkdirp the later versions support strict mode. Pinning it in your lockfile etc.
