### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by affanshahid** [nexe/nexe#419]
Building using
`nexe index.js`

```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at FileAnalysis.analyze (/Users/affan/.config/yarn/global/node_modules/fuse-box/dist/commonjs/analysis/FileAnalysis.js:101:24)
    at File.makeAnalysis (/Users/affan/.config/yarn/global/node_modules/fuse-box/dist/commonjs/core/File.js:230:23)
    at File.consume (/Users/affan/.config/yarn/global/node_modules/fuse-box/dist/commonjs/core/File.js:295:22)
    at ModuleCollection.<anonymous> (/Users/affan/.config/yarn/global/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:192:28)
    at Generator.next (<anonymous>)
    at /Users/affan/.config/yarn/global/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:7:71 code: 'MODULE_NOT_FOUND'
```

Does not crash the build, but is emitted in the beginning.
Running the compiled program emits:

```
Error: Cannot find module 'default/index.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

However, building using: `cat index.js | nexe` works and the compiled program runs as expected.

Node: v8.9.0
nexe: v2.0.0-rc.17
Installed using yarn: v1.2.1

**Comment by calebboyd** [comment]
Hi @affanshahid I'm going to roll this up into #418.... Sorry for the inconvenience

**Comment by affanshahid** [comment]
Any present workarounds?

**Comment by calebboyd** [comment]
Yeah, Installing typescript as a dev dependency should work for now. The current bundler is using it for transpilation
