### ISSUE TITLE
Cannot find module 'thrift'

### ISSUE THREAD

**Issue by airowgao** [nexe/nexe#421]
This is my index.js
```
var request = require('request');
var thrift = require('thrift');
request({
    url: 'https://www.baidu.com',
}, function (err, resp) {});
console.log('hello nexe');
```
Then nexe index.js 
And  ./index

Report this error
```
Error: Cannot find module 'thrift'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at u (/Users/gaomin/Desktop/ai_services_proxy_rpc/nodejs/srcs/aaa:41932:1092)
    at f (/Users/gaomin/Desktop/ai_services_proxy_rpc/nodejs/srcs/aaa:41932:1430)
    at c (/Users/gaomin/Desktop/ai_services_proxy_rpc/nodejs/srcs/aaa:41932:2520)
    at y.require (/Users/gaomin/Desktop/ai_services_proxy_rpc/nodejs/srcs/aaa:41932:3117)
    at Number.<anonymous> (/Users/gaomin/Desktop/ai_services_proxy_rpc/nodejs/srcs/aaa:17:14)
    at c (/Users/gaomin/Desktop/ai_services_proxy_rpc/nodejs/srcs/aaa:41932:3333)
```

node: v6.10.2
nexe: 2.0.0-rc.17

**Comment by calebboyd** [comment]
Not being able to bundle thrift is a result of not being able to bundle ws, which is related to

[this issue](https://github.com/fuse-box/fuse-box/issues/902)

Sorry there isn't much I can do to fix that right now
