### ISSUE TITLE
Add Proxy Support

### ISSUE THREAD

**Issue by reggi** [nexe/nexe#427]
```
➜  Desktop git:(master) ✗ nexe example.js
ℹ nexe 2.0.0-rc.22
⠋ nexe 2.0.0-rc.22
RequestError: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at StdError (/Users/treggi/.nvm/versions/node/v6.8.0/lib/node_modules/nexe/node_modules/got/index.js:410:3)
    at /Users/treggi/.nvm/versions/node/v6.8.0/lib/node_modules/nexe/node_modules/got/index.js:430:3
    at ClientRequest.req.once.err (/Users/treggi/.nvm/versions/node/v6.8.0/lib/node_modules/nexe/node_modules/got/index.js:111:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
⠋ Fetching prebuilt binary
```

I have `HTTP_PROXY` and `HTTPS_PROXY` proxy set but the request to `api.github.com` does not seem to be using it. Can we update the request to use proxy globals?

**Comment by reggi** [comment]
Seems to be not supported in `got` yet? https://github.com/sindresorhus/got/issues/79

**Comment by calebboyd** [comment]
Would passing `caw()` as agent work for you?

**Comment by calebboyd** [comment]
Try `nexe@next` c1896e13a3daee113e32ca325e9fdabd093a0f5a

**Comment by calebboyd** [comment]
@reggi any luck?

**Comment by reggi** [comment]
I'm getting some weird typescript error when I run now.

```
{ Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at FileAnalysis.analyze (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/analysis/FileAnalysis.js:101:24)
    at File.makeAnalysis (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/File.js:230:23)
    at File.consume (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/File.js:295:22)
    at ModuleCollection.<anonymous> (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:192:28)
    at Generator.next (<anonymous>)
    at /Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:7:71 code: 'MODULE_NOT_FOUND' }
⠙ Fetching prebuilt binary
RequestError: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.req.once.err (/Users/treggi/Desktop/project/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
⠋ Fetching prebuilt binary
```

**Comment by reggi** [comment]
Just upgraded to `2.0.0-rc.23`

```
> project@1.0.0 make /Users/treggi/Desktop/project
> nexe ./index.js

ℹ nexe 2.0.0-rc.23
{ Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at FileAnalysis.analyze (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/analysis/FileAnalysis.js:101:24)
    at File.makeAnalysis (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/File.js:230:23)
    at File.consume (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/File.js:295:22)
    at ModuleCollection.<anonymous> (/Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:192:28)
    at Generator.next (<anonymous>)
    at /Users/treggi/Desktop/project/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:7:71 code: 'MODULE_NOT_FOUND' }
⠋ Fetching prebuilt binary
RequestError: tunneling socket could not be established, statusCode=407
    at ClientRequest.req.once.err (/Users/treggi/Desktop/project/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at ClientRequest.onConnect (/Users/treggi/Desktop/project/node_modules/tunnel-agent/index.js:168:23)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketOnData (_http_client.js:471:11)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
✔ Fetching prebuilt binary
✔ Finished in 6.998s
RequestError: tunneling socket could not be established, statusCode=407
    at ClientRequest.req.once.err (/Users/treggi/Desktop/project/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at ClientRequest.onConnect (/Users/treggi/Desktop/project/node_modules/tunnel-agent/index.js:168:23)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketOnData (_http_client.js:471:11)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
```

**Comment by reggi** [comment]
Added proxy credentials and it downloaded.

**Comment by reggi** [comment]
I just went through the same issue with https://github.com/GoogleChrome/puppeteer

https://github.com/GoogleChrome/puppeteer/pull/1508

I need `rejectUnauthorized` set.

**Comment by calebboyd** [comment]
> I need rejectUnauthorized set.

🤔  Hmm -- This should be set... https://github.com/nexe/nexe/blob/721b06f5d2b540a92976f186677005b9bca2d172/src/options.ts#L236-L239

Does that not look accurate?

Regarding the typescript issue.... Its a known issue right now with the bundler -- go ahead and install it as a dev dep alongside nexe. Eventually it will be removed.

**Comment by calebboyd** [comment]
Closing due to inactivity, This has been added
