### ISSUE TITLE
bundling sequelize+sqlite doesn't work

### ISSUE THREAD

**Issue by HarelAshwal** [nexe/nexe#440]
git clone https://github.com/grempe/pkgtest
npm install
nexe index.js
i nexe 2.0.0-rc.22
√ Compiling result
√ Entry: 'index.js' written to: pkgtest.exe
√ Finished in 18.939s

C:\projects_node\pkgtest>pkgtest.exe
module.js:529
    throw err;
    ^

Error: Cannot find module 'sequelize'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at u (C:\projects_node\pkgtest\pkgtest.exe:45:1092)
    at f (C:\projects_node\pkgtest\pkgtest.exe:45:1430)
    at c (C:\projects_node\pkgtest\pkgtest.exe:45:2520)
    at y.require (C:\projects_node\pkgtest\pkgtest.exe:45:3117)
    at Number.<anonymous> (C:\projects_node\pkgtest\pkgtest.exe:13:19)
    at c (C:\projects_node\pkgtest\pkgtest.exe:45:3333)

C:\projects_node\pkgtest>

**Comment by bakednevada** [comment]
Different (possibly related) error on OSX:

```
$ git clone https://github.com/grempe/pkgtest
$ cd pkgtest/
$ npm install
$ nexe index.js
ℹ nexe 2.0.0-rc.22
✔ Downloading...100%
✔ Entry: 'index.js' written to: pkgtest
✔ Finished in 19.751s
$ ./pkgtest
/private/tmp/pkgtest/pkgtest:22834
      throw err;
      ^

Error: pkgtest package.json is not node-pre-gyp ready:
package.json must declare these properties: 
binary.module_name
binary.module_path
binary.host
    at Object.validate_config (/tmp/pkgtest/pkgtest:68697:15)
```
