### ISSUE TITLE
express with ejs doesn't work

### ISSUE THREAD

**Issue by HarelAshwal** [nexe/nexe#441]
git clone https://github.com/passport/express-4.x-local-example.git
cd express-4.x-local-example
npm install
nexe server.js
i nexe 2.0.0-rc.22
√ Compiling result
√ Entry: 'server.js' written to: server.exe
√ Finished in 21.978s

server.exe

Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at u (C:\projects_node\nexetest\express-4.x-local-example\server.exe:31616:1092)
    at f (C:\projects_node\nexetest\express-4.x-local-example\server.exe:31616:1430)
    at c (C:\projects_node\nexetest\express-4.x-local-example\server.exe:31616:2520)
    at y.require (C:\projects_node\nexetest\express-4.x-local-example\server.exe:31616:3117)
    at new View (C:\projects_node\nexetest\express-4.x-local-example\server.exe:2177:14)
    at Function.render (C:\projects_node\nexetest\express-4.x-local-example\server.exe:849:12)
::1 - - [30/Dec/2017:17:55:10 +0000] "GET /login HTTP/1.1" 500 1018 "-" "Mozilla/5.0 (Windows NT 6.1; WO

**Comment by rzl** [comment]
Cannot find module 'jade' too

**Comment by calebboyd** [comment]
@HarelAshwal You can try to `require('ejs')` at the start of your application

@rzl same for you, `require('jade')` or `'pug'`

**Comment by rzl** [comment]
@calebboyd  thanks for your reply , 
yes~
i think it may be nexe can not analysis dependency package  from the source code;
i try require('ejs') at the start but just startup can require ejs 
the same problem show when browser open url ；
and i try the resources option pack node_module （all files）  ...... same problem

so i think may be something wrong when call require or other ... 
ejs module not have index.js will be a reason ?

uses windows7 x64 
node 6.11.0

**Comment by rzl** [comment]
@calebboyd    
i try add  require('ejs') at the  file 'node_modules\express\lib\view.js'
success...
thank you !
