### ISSUE TITLE
linux-arm-8.9.1 not available

### ISSUE THREAD

**Issue by systemmind** [nexe/nexe#451]
Hi. I am trying to run nexe on raspberry-pi. I did this several month ago and it had started to build the node.js sources but the process was interrupted due to missing memory on sd card. Now the size of sd card is bigger but I have updated the raspbian os and now I have got next error:
```bash
 ℹ nexe 2.0.0-rc.22
⠸ Fetching prebuilt binary
Error: linux-arm-8.9.1 not available, create it using the --build flag
    at NexeCompiler.<anonymous> (/home/pi/.../node_modules/nexe/lib/compiler.js:255:35)
    at step (/home/pi/.../node_modules/nexe/lib/compiler.js:46:23)
    at Object.next (/home/pi/.../node_modules/nexe/lib/compiler.js:27:53)
    at fulfilled (/home/pi/.../node_modules/nexe/lib/compiler.js:18:58)
    at <anonymous>
⠦ Fetching prebuilt binary
```
What can be the problem and how it is possible to fix it?
Thanks.

**Comment by systemmind** [comment]
@calebboyd Thanks a lot, --build argument has resolved this error.
