### ISSUE TITLE
Cannot read property 'patches' of undefined

### ISSUE THREAD

**Issue by coderfox** [nexe/nexe#457]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

**test.js**

```js
require("dotenv/config");
console.log(process.env);
```

And generate binary with:

```shell
nexe test.js -o testjs
./testjs
```

The command fails with:

```shell
var patches = process.nexe.patches;
                           ^

TypeError: Cannot read property 'patches' of undefined
    at /Users/coderfox/Dev/Golang/src/github.com/coderfox/clover/testjs:239:28
    at Object.<anonymous> (/Users/coderfox/Dev/Golang/src/github.com/coderfox/clover/testjs:282:3)
    at Module._compile (module.js:635:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at bootstrap_node.js:116:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

<br/><br/>
Please also provide:

- Platform(OS/Version): macOS 10.13.1 (17B48) Darwin 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
- Host Node Version: v8.9.1
- Target Node Version: v8.9.1
- Nexe version: 2.0.0-next.4
- Python Version: Python 2.7.10

**Comment by calebboyd** [comment]
You're using `nexe@next` so you need to pass the `--build` flag as i mentioned in #455
