### ISSUE TITLE
Cannot find module with special chars

### ISSUE THREAD

**Issue by coderfox** [nexe/nexe#458]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

**test.js**
```javascript
let data = require("reflect-metadata");
console.log(process.env);
```

**build**

```shell
cat test.js | nexe -o testjs --build
```

and produces:
```shell
$ ./testjs
module.js:538
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/coderfox/Dev/Golang/src/github.com/coderfox/clover/testjs:290:62)
    at Module._compile (module.js:635:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:620:7)
    at Function.NativeModule.require (bootstrap_node.js:565:18)
    at bootstrap_node.js:140:22
```

The same issue occurs for `dotenv/config`.

<br/><br/>
Please also provide:

- Platform(OS/Version): macOS 10.13.1 (17B48) Darwin 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
- Host Node Version: v8.9.1
- Target Node Version: v8.9.1
- Nexe version: 2.0.0-next.4
- Python Version: Python 2.7.10

**Comment by calebboyd** [comment]
Dependency resolution isn't setup to work with `stdin` in `nexe@next` at this time do `nexe test.js -o testjs --build` instead
