### ISSUE TITLE
Cannot find module 'uberproto'

### ISSUE THREAD

**Issue by lboening** [nexe/nexe#459]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other
If this is a bug report, What are the steps to reproduce?

```shell
Nexe app.js -r * -o myapp.exe

Run myapp.exe

Error
module.js:557
    throw err;
    ^
Error: Cannot find module 'uberproto'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at u (D:\Code\feathmongoose\myapp.exe:112593:1092)
    at f (D:\Code\feathmongoose\myapp.exe:112593:1430)
    at d (D:\Code\feathmongoose\myapp.exe:112593:2731)
    at b.require (D:\Code\feathmongoose\myapp.exe:112593:3327)
    at Object.<anonymous> (D:\Code\feathmongoose\myapp.exe:1165:15)
    at d (D:\Code\feathmongoose\myapp.exe:112593:3565)
```

//provide configuration here
```
Featherjs app [feathers](https://docs.feathersjs.com/)
Mongodb support
```
<br/><br/>
Please also provide:

- Platform(OS/Version): Windows 10
- Host Node Version: 9.4.0
- Target Node Version: 9.4.0
- Nexe version: 2.0.0-rc.25
- Python Version: 2.7.14 32 bit intel on Win32

**Comment by calebboyd** [comment]
Will be fixed with #418
