### ISSUE TITLE
Error: Cannot find module '~/index.js' - superagent

### ISSUE THREAD

**Issue by johnomalley** [nexe/nexe#460]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

- create package.json, entry.js, build.js in root dir of project
- run `npm install`
- run `node build`
- run binary - `./out` 
- see output below

```
package.json
********
{
  "name": "nexebug",
  "version": "1.0.0",
  "description": "reproduce nexebug",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "nexe": "~2.0.0-rc.25"
  },
  "dependencies": {
    "superagent": "~3.8.2"
  }
}

entry.js
********
require('superagent')

build.js
********
const {compile} = require('nexe')

compile({
  input: './entry.js',
  name: 'out'
}).then(() => {
  console.log('success')
})
```

```
$ ./out 
module.js:540
    throw err;
    ^

Error: Cannot find module '~/index.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at s (/Users/john/projects/corporatemodeling/nexebug/out:14594:1845)
    at d (/Users/john/projects/corporatemodeling/nexebug/out:14594:3105)
    at b.require (/Users/john/projects/corporatemodeling/nexebug/out:14594:3327)
    at Object.<anonymous> (/Users/john/projects/corporatemodeling/nexebug/out:2366:17)
    at d (/Users/john/projects/corporatemodeling/nexebug/out:14594:3565)
    at b.require (/Users/john/projects/corporatemodeling/nexebug/out:14594:3327)
```
<br/>
Please also provide:

- Platform(OS/Version): macOS 10.13.3
- Host Node Version: n/a
- Target Node Version: n/a
- Nexe version: 2.0.0-rc.25
- Python Version: 2.7.10

**Comment by calebboyd** [comment]
This is pretty strange. Thanks for reporting it!

**Comment by calebboyd** [comment]
This is pretty strange. Thanks for reporting it! #418
