### ISSUE TITLE
win10 bug

### ISSUE THREAD

**Issue by hktalent** [nexe/nexe#469]
win10

```
var socks = require('socksv5'),
	program = require('commander'),
...
```

```
nexe mySocks5.js --build mySocks5.js -o mySocks5.exe
i nexe 2.0.0-rc.26
√ Source already downloaded
- Compiling result
Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
√ Configuring node build...
√ Finished in 1.14s
Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by calebboyd** [comment]
This says you don't have python in your path. Python is required to `--build` node
