### ISSUE TITLE
Error building node from source

### ISSUE THREAD

**Issue by chrstew** [nexe/nexe#471]
This is a
 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>
If this is a bug report, What are the steps to reproduce?

1. create a hello.js file that simply has `console.log('hello world');` inside of it
2. run nexe at the command line with these parameters: `nexe -i hello.js -o hello -t tmp/ --build --verbose`

the node source starts to be compiled until:
```
  g++ '-DU_COMMON_IMPLEMENTATION=1' '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer -fno-exceptions -std=gnu++0x -frtti -MMD -MF /root/.nexe/8.11.1/out/Release/.deps//root/.nexe/8.11.1/out/Release/obj.target/icuucx/deps/icu-small/source/common/ustrenum.o.d.raw   -c -o /root/.nexe/8.11.1/out/Release/obj.target/icuucx/deps/icu-small/source/common/ustrenum.o ../deps/icu-small/source/common/ustrenum.cpp
In file included from ../deps/icu-small/source/common/unicode/unistr.h:33,
                 from ../deps/icu-small/source/common/unicode/strenum.h:16,
                 from ../deps/icu-small/source/common/ustrenum.cpp:16:
../deps/icu-small/source/common/unicode/char16ptr.h:69: error: expected ')' before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:117: error: expected ')' before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:176: error: expected unqualified-id before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:176: error: expected ')' before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:176: error: expected ';' before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:225: error: expected unqualified-id before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:225: error: expected ')' before 'p'
../deps/icu-small/source/common/unicode/char16ptr.h:225: error: expected initializer before 'p'
In file included from ../deps/icu-small/source/common/unicode/strenum.h:16,
                 from ../deps/icu-small/source/common/ustrenum.cpp:16:
../deps/icu-small/source/common/unicode/unistr.h:3051: error: expected unqualified-id before 'text'
../deps/icu-small/source/common/unicode/unistr.h:3051: error: expected ')' before 'text'
../deps/icu-small/source/common/unicode/unistr.h:3051: error: expected ';' before 'text'
../deps/icu-small/source/common/unicode/unistr.h:3107: error: expected unqualified-id before 'text'
../deps/icu-small/source/common/unicode/unistr.h:3107: error: expected ')' before 'text'
../deps/icu-small/source/common/unicode/unistr.h:3107: error: expected ';' before 'text'
../deps/icu-small/source/common/unicode/unistr.h:3202: error: expected ')' before 'buffer'
../deps/icu-small/source/common/unicode/unistr.h: In constructor 'icu_60::UnicodeString::UnicodeString(const uint16_t*)':
../deps/icu-small/source/common/unicode/unistr.h:3014: error: type 'icu_60::UnicodeString' is not a direct base of 'icu_60::UnicodeString'
../deps/icu-small/source/common/unicode/unistr.h: In constructor 'icu_60::UnicodeString::UnicodeString(const uint16_t*, int32_t)':
../deps/icu-small/source/common/unicode/unistr.h:3076: error: type 'icu_60::UnicodeString' is not a direct base of 'icu_60::UnicodeString'
../deps/icu-small/source/common/unicode/unistr.h: In constructor 'icu_60::UnicodeString::UnicodeString(uint16_t*, int32_t, int32_t)':
../deps/icu-small/source/common/unicode/unistr.h:3169: error: type 'icu_60::UnicodeString' is not a direct base of 'icu_60::UnicodeString'
../deps/icu-small/source/common/unicode/unistr.h: At global scope:
../deps/icu-small/source/common/unicode/unistr.h:3914: error: expected unqualified-id before ')' token
../deps/icu-small/source/common/unicode/unistr.h:3914: error: prototype for 'icu_60::UnicodeString::UnicodeString(...)' does not match any in class 'icu_60::UnicodeString'
../deps/icu-small/source/common/unicode/unistr.h:3375: error: candidates are: icu_60::UnicodeString::UnicodeString(const icu_60::UnicodeString&, int32_t, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3366: error:                 icu_60::UnicodeString::UnicodeString(const icu_60::UnicodeString&, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3358: error:                 icu_60::UnicodeString::UnicodeString(icu_60::UnicodeString&&)
../deps/icu-small/source/common/unicode/unistr.h:3350: error:                 icu_60::UnicodeString::UnicodeString(const icu_60::UnicodeString&)
../deps/icu-small/source/common/unicode/unistr.h:3331: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t, icu_60::UnicodeString::EInvariant)
../deps/icu-small/source/common/unicode/unistr.h:3300: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t, UConverter*, UErrorCode&)
../deps/icu-small/source/common/unicode/unistr.h:3277: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t, const char*)
../deps/icu-small/source/common/unicode/unistr.h:3258: error:                 icu_60::UnicodeString::UnicodeString(const char*, const char*)
../deps/icu-small/source/common/unicode/unistr.h:3235: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3225: error:                 icu_60::UnicodeString::UnicodeString(const char*)
../deps/icu-small/source/common/unicode/unistr.h:3168: error:                 icu_60::UnicodeString::UnicodeString(uint16_t*, int32_t, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3153: error:                 icu_60::UnicodeString::UnicodeString(char16_t*, int32_t, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3131: error:                 icu_60::UnicodeString::UnicodeString(UBool, icu_60::ConstChar16Ptr, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3075: error:                 icu_60::UnicodeString::UnicodeString(const uint16_t*, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3060: error:                 icu_60::UnicodeString::UnicodeString(const char16_t*, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3013: error:                 icu_60::UnicodeString::UnicodeString(const uint16_t*)
../deps/icu-small/source/common/unicode/unistr.h:2996: error:                 icu_60::UnicodeString::UnicodeString(const char16_t*)
../deps/icu-small/source/common/unicode/unistr.h:2984: error:                 icu_60::UnicodeString::UnicodeString(UChar32)
../deps/icu-small/source/common/unicode/unistr.h:2973: error:                 icu_60::UnicodeString::UnicodeString(char16_t)
../deps/icu-small/source/common/unicode/unistr.h:2962: error:                 icu_60::UnicodeString::UnicodeString(int32_t, UChar32, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3910: error:                 icu_60::UnicodeString::UnicodeString()
../deps/icu-small/source/common/unicode/unistr.h:3918: error: expected unqualified-id before ',' token
../deps/icu-small/source/common/unicode/unistr.h:3918: error: expected ')' before ',' token
../deps/icu-small/source/common/unicode/unistr.h:3918: error: prototype for 'icu_60::UnicodeString::UnicodeString(...)' does not match any in class 'icu_60::UnicodeString'
../deps/icu-small/source/common/unicode/unistr.h:3375: error: candidates are: icu_60::UnicodeString::UnicodeString(const icu_60::UnicodeString&, int32_t, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3366: error:                 icu_60::UnicodeString::UnicodeString(const icu_60::UnicodeString&, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3358: error:                 icu_60::UnicodeString::UnicodeString(icu_60::UnicodeString&&)
../deps/icu-small/source/common/unicode/unistr.h:3350: error:                 icu_60::UnicodeString::UnicodeString(const icu_60::UnicodeString&)
../deps/icu-small/source/common/unicode/unistr.h:3331: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t, icu_60::UnicodeString::EInvariant)
../deps/icu-small/source/common/unicode/unistr.h:3300: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t, UConverter*, UErrorCode&)
../deps/icu-small/source/common/unicode/unistr.h:3277: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t, const char*)
../deps/icu-small/source/common/unicode/unistr.h:3258: error:                 icu_60::UnicodeString::UnicodeString(const char*, const char*)
../deps/icu-small/source/common/unicode/unistr.h:3235: error:                 icu_60::UnicodeString::UnicodeString(const char*, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3225: error:                 icu_60::UnicodeString::UnicodeString(const char*)
../deps/icu-small/source/common/unicode/unistr.h:3168: error:                 icu_60::UnicodeString::UnicodeString(uint16_t*, int32_t, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3153: error:                 icu_60::UnicodeString::UnicodeString(char16_t*, int32_t, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3131: error:                 icu_60::UnicodeString::UnicodeString(UBool, icu_60::ConstChar16Ptr, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3075: error:                 icu_60::UnicodeString::UnicodeString(const uint16_t*, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3060: error:                 icu_60::UnicodeString::UnicodeString(const char16_t*, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3013: error:                 icu_60::UnicodeString::UnicodeString(const uint16_t*)
../deps/icu-small/source/common/unicode/unistr.h:2996: error:                 icu_60::UnicodeString::UnicodeString(const char16_t*)
../deps/icu-small/source/common/unicode/unistr.h:2984: error:                 icu_60::UnicodeString::UnicodeString(UChar32)
../deps/icu-small/source/common/unicode/unistr.h:2973: error:                 icu_60::UnicodeString::UnicodeString(char16_t)
../deps/icu-small/source/common/unicode/unistr.h:2962: error:                 icu_60::UnicodeString::UnicodeString(int32_t, UChar32, int32_t)
../deps/icu-small/source/common/unicode/unistr.h:3910: error:                 icu_60::UnicodeString::UnicodeString()
../deps/icu-small/source/common/unicode/unistr.h:3918: error: expected initializer before ')' token
../deps/icu-small/source/common/unicode/unistr.h:3922: error: expected ')' before ',' token
../deps/icu-small/source/common/unicode/unistr.h:3922: error: 'icu_60::int32_t' declared as an 'inline' variable
../deps/icu-small/source/common/unicode/unistr.h:3922: error: expected initializer before ')' token
../deps/icu-small/source/common/unicode/unistr.h:3934: error: 'int32_t' does not name a type
../deps/icu-small/source/common/unicode/unistr.h:3941: error: 'int32_t' does not name a type
../deps/icu-small/source/common/unicode/unistr.h:3946: error: 'int32_t' does not name a type
../deps/icu-small/source/common/unicode/unistr.h:3952: error: 'int32_t' does not name a type
../deps/icu-small/source/common/unicode/unistr.h: In member function 'const char16_t* icu_60::UnicodeString::getBuffer() const':
../deps/icu-small/source/common/unicode/unistr.h:3975: error: 'nullptr' was not declared in this scope
../deps/icu-small/source/common/unicode/unistr.h: At global scope:
../deps/icu-small/source/common/unicode/unistr.h:3987: error: 'icu_60::UnicodeString::doCompare' declared as an 'inline' variable
../deps/icu-small/source/common/unicode/unistr.h:3987: error: 'int8_t icu_60::UnicodeString::doCompare' is not a static member of 'class icu_60::UnicodeString'
../deps/icu-small/source/common/unicode/unistr.h:3987: error: expected ')' before 'start'
../deps/icu-small/source/common/unicode/unistr.h:3988: error: expected ')' before 'thisLength'
../deps/icu-small/source/common/unicode/unistr.h:3989: error: expected primary-expression before 'const'
../deps/icu-small/source/common/unicode/unistr.h:3990: error: expected ')' before 'srcStart'
../deps/icu-small/source/common/unicode/unistr.h:3991: error: expected ')' before 'srcLength'
../deps/icu-small/source/common/unicode/unistr.h:3991: error: initializer expression list treated as compound expression
../deps/icu-small/source/common/unicode/unistr.h:3991: warning: left-hand operand of comma has no effect
../deps/icu-small/source/common/unicode/unistr.h:3991: error: expected ',' or ';' before 'const'
../deps/icu-small/source/common/ustrenum.cpp:395: error: expected '}' at end of input
../deps/icu-small/source/common/ustrenum.cpp:395: error: expected '}' at end of input
../deps/icu-small/source/common/unicode/unistr.h:1755: warning: inline function 'int32_t icu_60::UnicodeString::length() const' used but never defined
make[1]: *** [/root/.nexe/8.11.1/out/Release/obj.target/icuucx/deps/icu-small/source/common/ustrenum.o] Error 1
rm 13325b3660d32481330d96cdb02330c01348373e.intermediate
make[1]: Leaving directory `/root/.nexe/8.11.1/out'
make: *** [node] Error 2
⠋ Compiling Node...
Error: make  exited with code: 2
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nexe/lib/compiler.js:201:28)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
✔ Compiling Node...
✔ Finished in 81.613s
Error: make  exited with code: 2
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nexe/lib/compiler.js:201:28)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

```

<br/><br/>
Please also provide:

- Platform(OS/Version): CentOS 6
- Host Node Version: 8.11.1
- Target Node Version: 8.11.1
- Nexe version: 2.0.0-rc.26
- Python Version: 2.6.6

Thank you in advance with your help on this problem.

**Comment by calebboyd** [comment]
Please refer to https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms

**Comment by chrstew** [comment]
Is there a command line flag to build via clang instead of gcc?

**Comment by calebboyd** [comment]
On the other hand, If you don't pass `--build` it should work just fine
