### ISSUE TITLE
Error: Cannot find module 'ms'

### ISSUE THREAD

**Issue by JaLe29** [nexe/nexe#482]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

<br/>

**package.json**
```
{
  "name": "win",
  "version": "1.0.0",
  "description": "win",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "nightmare": "^3.0.1"
  }
}

```

**index.js**
```
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })

nightmare
  .goto('https://duckduckgo.com')
  .type('#search_form_input_homepage', 'github nightmare')
  .click('#search_button_homepage')
  .wait('#r1-0 a.result__a')
  .evaluate(() => document.querySelector('#r1-0 a.result__a').href)
  .end()
  .then(console.log)
  .catch(error => {
    console.error('Search failed:', error)
  })
```

**Compile:**
```
> nexe -t x86-8.0.0
i nexe 2.0.0-rc.28
RUN
√ Downloading...100%
√ Entry: 'index.js' written to: s.exe
√ Finished in 17.967s
```

**ERROR**:
```
C:\Users\admin\Desktop\s>s.exe
module.js:487
    throw err;
    ^

Error: Cannot find module 'ms'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at u (C:\Users\admin\Desktop\s\s.exe:3883:1092)
    at f (C:\Users\admin\Desktop\s\s.exe:3883:1430)
    at c (C:\Users\admin\Desktop\s\s.exe:3883:2731)
    at b.require (C:\Users\admin\Desktop\s\s.exe:3883:3327)
    at Object.<anonymous> (C:\Users\admin\Desktop\s\s.exe:423:20)
    at c (C:\Users\admin\Desktop\s\s.exe:3883:3565)
```

<br/><br/>
- Platform(OS/Version):
Windows 10, 64b
- Host Node Version:
v8.4.0
- Target Node Version:
v.8.0.0 and v8.4.0
- Nexe version:
Last (2.0.0-rc.28)
- Python Version:
Python 3.6.2

**Comment by JaLe29** [comment]
It's look like, that it's not working for an external library linked by key 'require'.

**Comment by ramkumarc** [comment]
When will this fix be merged and released ?. Unable to use the package due to similar error on runtime. Application works fine without packaging.

**Comment by dknell** [comment]
merge it!

**Comment by calebboyd** [comment]
It isn't finished...

**Comment by JaLe29** [comment]
still not working ? :-(

**Comment by MeanwhileMedia** [comment]
Any updates on https://github.com/nexe/nexe/issues/418 ? I'd love to use nexe if possible.

**Comment by ofarukcaki** [comment]
Did anyone found the solution? I need it urgently but every attempt I tried failed
