### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by Rytiss** [nexe/nexe#483]
This is a
 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Other

I built a binary using multiple node versions, starting with 9.11.1 and going down. Binaries built using the latest few versions do not run, throwing the following:

```
path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:653:5)
    at defaultable (C:\Users\PC\Desktop\resolver.exe:226:26)
    at good (C:\Users\PC\Desktop\resolver.exe:360:19)
    at Object.<anonymous> (C:\Users\PC\Desktop\resolver.exe:1547:23)
    at c (C:\Users\PC\Desktop\resolver.exe:1931:3565)
    at b.require (C:\Users\PC\Desktop\resolver.exe:1931:3327)
    at Object.<anonymous> (C:\Users\PC\Desktop\resolver.exe:381:21)
    at c (C:\Users\PC\Desktop\resolver.exe:1931:3565)
    at b.require (C:\Users\PC\Desktop\resolver.exe:1931:3327)
```

Some older versions such as 8.11.1, throw a different error:
```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:715:5)
    at defaultable (C:\Users\PC\Desktop\resolver.exe:226:26)
    at good (C:\Users\PC\Desktop\resolver.exe:360:19)
    at Object.<anonymous> (C:\Users\PC\Desktop\resolver.exe:1547:23)
    at c (C:\Users\PC\Desktop\resolver.exe:1931:3565)
    at b.require (C:\Users\PC\Desktop\resolver.exe:1931:3327)
    at Object.<anonymous> (C:\Users\PC\Desktop\resolver.exe:381:21)
    at c (C:\Users\PC\Desktop\resolver.exe:1931:3565)
    at b.require (C:\Users\PC\Desktop\resolver.exe:1931:3327)
```
Only version 4.8.4 builds successfully, but that is too old for my purposes.

I am using the following modules:
```
        crypto: require('crypto'),
        dnsd: require('dnsd'),
        fs: require('fs'),
        http: require('http'),
        https: require('https'),
        url: require('url'),
```

- Platform(OS/Version): Windows 10 x64 1803
- Host Node Version: 10.1.0
- Target Node Version: various (9.11.1, 8.11.1)
- Nexe version: 2.0.0-rc.28
- Python Version: 2.7.10

**Comment by calebboyd** [comment]
What options are you using? Can you provide a minimal reproduction?
