### ISSUE TITLE
Cannot find module 'package.json'

### ISSUE THREAD

**Issue by leon3103** [nexe/nexe#500]
This is a
 - [x] Bug Report(?)
 - [ ] Feature Request
 - [x] Other

<br/>

```
nexe -i ./index.js -o Thumbnailer.bin -p /usr/bin/python2 --build 
```
After using nexe and trying to run my Binary i get the following Error Message: 
```
╰─$ ./Thumbnailer.bin
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at f (/home/lwolf/Projekte/Thumbnailer/Thumbnailer.bin:33356:1092)
    at u (/home/lwolf/Projekte/Thumbnailer/Thumbnailer.bin:33356:1430)
    at c (/home/lwolf/Projekte/Thumbnailer/Thumbnailer.bin:33356:2750)
    at b.require (/home/lwolf/Projekte/Thumbnailer/Thumbnailer.bin:33356:3346)
    at Object.<anonymous> (/home/lwolf/Projekte/Thumbnailer/Thumbnailer.bin:8401:26)
    at c (/home/lwolf/Projekte/Thumbnailer/Thumbnailer.bin:33356:3584)

```

in the index.js i do only require:
```const puppeteer = require('puppeteer');```

<br/><br/>
Please also provide:

- Platform(OS/Version): Manajro 17
- Host Node Version: 10.4
- Target Node Version: 10.4
- Nexe version: 2.0.0-rc.30
- Python Version: 2

**Comment by umutc** [comment]
hi
is this problem fixed or anyone have in idea?

**Comment by leon3103** [comment]
Did not get any respond and fixed it by using zeit/pkg.

**Comment by leon3103** [comment]
wow... instead of trying to fix it you only close the ticket because i used another solution..

**Comment by JamesMGreene** [comment]
It should be a non-issue in the upcoming release (i.e. if you use the `@next` branches). I'm building two complex apps with that just fine.

**Comment by rraallvv** [comment]
I'm getting the error "Cannot find module", I thought nexe could detect the dependencies from `require`, is that the case?
