### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by iterprise** [nexe/nexe#502]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [ x] Other

<br/>

```
calculate / # npm i nexe -g
/usr/bin/nexe -> /usr/lib/node_modules/nexe/index.js

> node-sass@4.9.2 install /usr/lib/node_modules/nexe/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib64/node_modules/nexe/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/lib64/node_modules/nexe/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/usr/lib64/node_modules/nexe/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib64/node_modules/nexe/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib64/node_modules/nexe/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/lib64/node_modules/nexe/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib64/node_modules/nexe/node_modules/node-sass/vendor' }

> node-sass@4.9.2 postinstall /usr/lib/node_modules/nexe/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /usr/lib64/node_modules/nexe/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib64/node_modules/nexe/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.7.0
gyp info using node@8.11.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/nexe/node_modules/node-sass/.node-gyp"
gyp verb command install [ '--node_gyp_internal_noretry', '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.11.1
gyp verb ensuring nodedir is created /usr/lib/node_modules/nexe/node_modules/node-sass/.node-gyp/8.11.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.11.1' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/nexe/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.11.1
gyp verb remove removing development files for version: 8.11.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.11.1' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/nexe/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.11.1
gyp verb remove removing development files for version: 8.11.1
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/nexe/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.14.52-calculate
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/nexe/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib64/node_modules/nexe/node_modules/node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/nexe/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-12T14_35_47_769Z-debug.log

```

<br/><br/>
Please also provide:

- Platform(OS/Version):
Calculate linux
- Host Node Version:
v8.11.1
- Target Node Version:
- Nexe version:
latest
- Python Version:
Python 2.7.14

**Comment by iterprise** [comment]
I fix it. Sorry.

**Comment by RisoriTofa** [comment]
You can solve it in Ubuntu by running it as a `sudo` command.
