### ISSUE TITLE
Unable to compile node app with nexe 2.0.0-rc-34

### ISSUE THREAD

**Issue by danielb2** [nexe/nexe#520]
**Is this a BUG or a FEATURE REQUEST?:** 

**What happened:**
tried to compile the simpliest script of them all. console.log('test')

**What you expected to happen:**

I expected to get a binary that I can execute

**How to reproduce it (as minimally and precisely as possible):**

```
[~/w/s/s/scripts]$ cat foo.js
console.log('test');
[daniel@sanji]-(09:27:32)-(0.0s)
[~/w/s/s/scripts]$ nexe foo.js -o foo
ℹ nexe 2.0.0-rc.34

/Users/daniel/.nvm/versions/node/v6.14.3/lib/node_modules/nexe/node_modules/fuse-box/Utils.js:68
function uglify(contents, { es6 = false, ...opts } = {}) {
                                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/daniel/.nvm/versions/node/v6.14.3/lib/node_modules/nexe/node_module
s/fuse-box/CacheBreaker.js:5:17)
✔ nexe 2.0.0-rc.34
✔ Finished in 0.036s
(node:51235) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): SyntaxE
rror: Unexpected token ...
[daniel@sanji]-(09:27:34)-(0.7s)
[~/w/s/s/scripts]$ node --version
v6.14.3
[daniel@sanji]-(09:27:42)-(0.0s)
[~/w/s/s/scripts]$ uname -a
Darwin sanji 18.0.0 Darwin Kernel Version 18.0.0: Sun Jul 22 20:25:45 PDT 2018; root:xnu-4903.200.327
~38/RELEASE_X86_64 x86_64
```

**Comment by stoffern** [comment]
I am new to nexe, but this looks like a spread operator to me, and the node running in nexe dont read it. 
Make sure you use babel to transcode it.

**Comment by danielb2** [comment]
You can see from node version that spread operator is supported (6)

**Comment by calebboyd** [comment]
@danielb2 Object spread is in Node 8. The active LTS.

**Comment by danielb2** [comment]
I missed that it was an object. So does this mean that this library doesn't work for node < 8 ? If so, maybe there should be a check pretty early in the process instead of a confusing message

**Comment by calebboyd** [comment]
@danielb2 This code was from a dependency, `nexe@next` should work on node 6+
