### ISSUE TITLE
log4js additional appender (rabbitMQ)

### ISSUE THREAD

**Issue by nmalinin** [nexe/nexe#535]
**Is this a BUG or a FEATURE REQUEST?:** 
I think it is more feature request.

**What happened:**
I would like to use rabbitMQ appender that can be attached to log4js: https://github.com/log4js-node/rabbitmq

My test file is:
test.js
`let main = require('./main.js');`
`require('@log4js-node/rabbitmq/lib/index.js');`
`let log4js = require('log4js')`
`log4js.configure({`
`    appenders: main.loggerAppenders,`
`    categories: main.loggerCategories`
`});`
`let logger = log4js.getLogger('orders');`
    `logger.info('Cheese is Comté.');`
    `logger.warn('Cheese is quite smelly.');`
`log4js.shutdown(()=>{});`

After compiling result of start executalble file is:
Error: Cannot find module 'amqplib'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at f (C:\infocl_project\infocl\1x\dev\infocl.exe:12906:1092)
    at u (C:\infocl_project\infocl\1x\dev\infocl.exe:12906:1430)
    at c (C:\infocl_project\infocl\1x\dev\infocl.exe:12906:2750)
    at b.require (C:\infocl_project\infocl\1x\dev\infocl.exe:12906:3346)
    at Object.<anonymous> (C:\infocl_project\infocl\1x\dev\infocl.exe:172:17)
    at c (C:\infocl_project\infocl\1x\dev\infocl.exe:12906:3584):

I inserted this module into package.json and tried to add require('amqplib') in my code. It didn't help. 

**What you expected to happen:**
I would like to use this feature of log4js with nexe. Could you tell me how this proble can be solved?
Thank you!

**Environment**

- Platform(OS/Version): Win7x64
- Host Node Version: 8.9.4
- Target Node Version: 8x or later
- Nexe version: nexe 2.0.0-rc.34
- Python Version: 2.7

**Comment by calebboyd** [comment]
try `npm i nexe@next`

**Comment by nmalinin** [comment]
> try npm i nexe@next
#### This version
##### test.js (the same):
```js
let main = require('./main.js');
require('@log4js-node/rabbitmq/lib/index.js');
require('amqplib');
let log4js = require('log4js');
log4js.configure({
    appenders: main.loggerAppenders,
    categories: main.loggerCategories
});
let logger = log4js.getLogger('orders');

logger.trace('Entering cheese testing');
logger.debug('Got cheese.');
logger.info('Cheese is Comté.');
logger.warn('Cheese is quite smelly.');
logger.error('Cheese is too ripe!');
logger.fatal('Cheese was breeding ground for listeria.');
log4js.shutdown(()=>{});
``` 
##### compiling:
```
nexe test.js --o test.exe
i nexe 3.0.0-beta.1
√ Compiling result
√ Entry: 'test.js' written to: test.exe
√ Finished in 6.708s
```
##### starting test.exe:
```js

C:\edu>.\test.exe
C:\edu\test.exe:253
    var patches = process.nexe.patches || {};
                               ^

TypeError: Cannot read property 'patches' of undefined
    at shimFs (C:\edu\test.exe:253:32)
    at C:\edu\test.exe:311:1
    at Object.<anonymous> (C:\edu\test.exe:311:25)
    at Module._compile (module.js:643:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at bootstrap_node.js:116:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by calebboyd** [comment]
you'll need to run it once with the `--clean` option

**Comment by nmalinin** [comment]
It works. Thank you!
