### ISSUE TITLE
Firebase fails

### ISSUE THREAD

**Issue by danielmhanover** [nexe/nexe#544]
Using nexe@next on Windows 10, with Node v8.12.0 and firebase@5.5.2.

Attempting `nexe index.js` fails if `index.js` is simply `var firebase = require("firebase");` with the error:

`Error! Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'`

Attempting to build with an earlier version of nexe will succeed but fail at runtime.

**Comment by carbonfish** [comment]
Encountering the similar error with node v10.15.3 on windows 7 professional. My code doesn't have firebase.

**Comment by yasserf** [comment]
Yeah I get this: 

```
(node:1076) UnhandledPromiseRejectionWarning: Error: Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
    at ChildProcess.<anonymous> (C:\projects\deepstream-io\node_modules\resolve-dependencies\lib\worker.js:28:31)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by slachtar** [comment]
Same error on windows 10 64, node v10.15.3
`(node:12944) UnhandledPromiseRejectionWarning: Error: Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
`

**Comment by lord22shark** [comment]
Same error on Windows 7 Ultimate running as administrator, node v8.12.0:

`
Error: Error: EBUSY: resource busy or locked, lstat 'F:\pagefile.sys'
    at ChildProcess.<anonymous> (---\node_modules\resolve-dependencies\lib\worker.js:28:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`

**Comment by slachtar** [comment]
Here's a fix that worked for me:
Well, it seems it's nexe problem, trying for unknown reason to access C:\hiberfil.sys and pagefile.sys, those files are only accessible by system user, the first if used for hibernation (when windows enters in deep sleep mode), the second is the swap file.
I disabled the first file via this command:
`powercfg -h off`
you need to run it from a command prompt as Administrator.
For the second file, you need to disable virtual memory, you may follow this simple instructions https://www.trishtech.com/2014/11/disable-virtual-memory-in-windows-10/

then reboot

and execute your commands as Administrator.
