### ISSUE TITLE
Unexpected string in JSON at position 1106

### ISSUE THREAD

**Issue by jchernin4** [nexe/nexe#561]
For some reason when I node the file bot.js I get this error. Also, in brackets I get a JSLint error "Expected an identifier and instead saw "const" and a ESLint error "ERROR: Parsing error: The keyword 'const' is reserved"
https://drive.google.com/file/d/1gsYjnTE3EW7tRzEdsqnt-W29jyKA8CCY/view?usp=sharing

Oh whoops also forgot the actual file itself: `{
  "username": "TradrBOT1",
  "password": "Cant show this",
  "botname": "TradrBOT1",
  "identitySecret": "or this",
  "sharedSecret": "or this",
  "adminIDs": ["76561198277808760","99999999999999999"],
  "options": {
    "apikey":"",
    "appid": "730",
    "minimumprice": 0.03,
    "acceptRandomFriendRequests": true,
    "priceRefreshInterval": 30,
    "confirmationInterval": 30,
    "percentamount": 0.95,
    "minPricePerItem": 0.03,
    "chatResponse": {
      "donation": "Thanks for donating to the bot :) have a nice day",
      "junk": "The trade you sent was too cheap for me to accept",
      "tradeDeclined": "Sorry :/ your trade did not have enough overpay for me to accept it. I value my items at 100% and value yours at 95%",
      "tradeAccepted": "Thanks For trading with CMD_Fyre'S Bot. Hope you have fun with your new skins",
      "newFriend": "Hey thanks for adding my bot",
      "unknownCommand": "Unknown command.",
      "adminTrade": "Hey admin im giving my items now",
      "commands": {
        "!test": "this is a test command"
        "!yeet": "Yeet!"
      }
    }
  }
}`

 at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:707:27)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Desktop\CSGO-Overpay-Bot-master\bot.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)

**Comment by jchernin4** [comment]
Nevermind I added !yeet the wrong way XD
