### ISSUE TITLE
Error with Eslint with Nexe compiled executable

### ISSUE THREAD

**Issue by jimdou** [nexe/nexe#569]
Also posted as an issue to EsLint https://github.com/eslint/eslint/issues/11190
**Is this a BUG or a FEATURE REQUEST?:** 
Bug
**What happened:**

I have created a CLI application on node js, it has Eslint as a dependency.
I built it using nexe, I get an error when I try to use my function to lint from the executable:

```js
var CLIEngine = require("eslint").CLIEngine;
eslintCli.executeOnFiles(jsFiles).results
```
with nexe 2.0.0-rc.34 :
```bash
const ruleReplacements = require("../conf/replacements").rules;
                                                        ^

TypeError: Cannot read property 'rules' of null
    at Object.<anonymous> (executable:39640:57)
    at c (executable:220866:3584)
    at b.require (executable:220866:3346)
    at Object.<anonymous> (executable:29912:13)
    at c (executable:220866:3584)
    at b.require (executable:220866:3346)
    at Object.<anonymous> (executable:29862:16)
    at c (executable:220866:3584)
    at b.require (executable:220866:3346)
    at Object.<anonymous> (executable:1365:17)

```

with nexe 3.0.0 using nexe@next:
```bash
Error during CommitAttempt creation.
{ Error: ENOENT: no such file or directory, scandir 'executable/node_modules/eslint/lib/rules'
    at Object.readdirSync (fs.js:783:3)
    at Object.readdirSync (executable:168:50)
    at module.exports (executable/node_modules/eslint/lib/load-rules.js:40:8)
    at Rules.load (executable/node_modules/eslint/lib/rules.js:83:26)
    at new Rules (executable/node_modules/eslint/lib/rules.js:63:14)
    at new Linter (executable/node_modules/eslint/lib/linter.js:887:22)
    at new CLIEngine (executable/node_modules/eslint/lib/cli-engine.js:442:23)
    at createCommitAttempt.then.body (executable/utils/linter.js:266:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path:
   'executable/node_modules/eslint/lib/rules' }
```

Note the function still woks when called from the script with node index.js,

In both case the error seems linked with the path for rules in node_modules/eslint/lib/rules.js (line 14)

```js
 const ruleReplacements = require("../conf/replacements").rules;
```

**What you expected to happen:**
That the executable can use the node_modules depencies when built

**How to reproduce it (as minimally and precisely as possible):**
Take a node js using Eslint API, built it and call a function using Eslint API (which call the linter node_modules files)

**Anything else we need to know?:**
The bug appeared when I added Eslint as a depency, it was working beforehand.

**Environment**

- Platform(OS/Version): MacOs High Sierra
- Host Node Version: v10.14.1
- Eslint verion: 5.9.0
- Nexe version: 2.0.0-rc.34 and V3.0.0

**Comment by accozi** [comment]
I have a same issue.

CODE:
var framework = require(path.join(rcPath, 'core-framework', 'index.js'));
framework.initialize(configs.framework);


ERROR:
D:\develop\development\tgos_hcr\servers\x-svc\bin\x-svc.exe:263
framework.initialize(configs.framework);
          ^

TypeError: Cannot read property 'initialize' of null
    at Object.<anonymous> (D:\develop\development\tgos_hcr\servers\x-svc\bin\x-svc.exe:263:11)
    at c (D:\develop\development\tgos_hcr\servers\x-svc\bin\x-svc.exe:331:3584)
    at Function.r.import (D:\develop\development\tgos_hcr\servers\x-svc\bin\x-svc.exe:331:4190)
    at p (D:\develop\development\tgos_hcr\servers\x-svc\bin\x-svc.exe:328:15)
    at Object.<anonymous> (D:\develop\development\tgos_hcr\servers\x-svc\bin\x-svc.exe:331:1)
    at Module._compile (module.js:653:30)
    at _third_party_main.js:45:20
    at NativeModule.compile (bootstrap_node.js:613:7)
    at Function.NativeModule.require (bootstrap_node.js:558:18)
    at bootstrap_node.js:133:22


I don't know why framework variable has null.
no problem when running source codes before Nexe compiled.

Is it a bug?
please help me if anyone have a solution for this issue.

**Comment by calebboyd** [comment]
I'm on holiday, but will look when I return

**Comment by jimdou** [comment]
Thank you

**Comment by calebboyd** [comment]
@jimdou If you update from v2 to v3 you'll need to run your command once with the `--clean` option to avoid using an outdated binary.

I think this should solve your problem.

**Comment by jimdou** [comment]
Hello, thank you for your answer, I have tried but i get the same error:

```bash
Error during CommitAttempt creation.
{ Error: ENOENT: no such file or directory, scandir '/example10/node_modules/eslint/lib/rules'
    at Object.readdirSync (fs.js:783:3)
    at Object.readdirSync (/executable165:50)
    at module.exports (/example10/node_modules/eslint/lib/load-rules.js:40:8)
    at Rules.load (/example10/node_modules/eslint/lib/rules.js:84:26)
    at new Rules (/example10/node_modules/eslint/lib/rules.js:64:14)
    at new Linter (/example10/node_modules/eslint/lib/linter.js:887:22)
    at new CLIEngine (example10/node_modules/eslint/lib/cli-engine.js:442:23)
    at createCommitAttempt.then.body (/example10/utils/linter.js:351:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/example10/node_modules/eslint/lib/rules' }
```

**Comment by jimdou** [comment]
This comment https://github.com/eslint/eslint/issues/11190#issuecomment-449643086 gives more insight

**Comment by calebboyd** [comment]
Looks like it was caused by a [bug that has been fixed but  is not yet published.](https://github.com/kevva/dir-glob/issues/7).

The latest nexe@next should work, it is depending on a fork
