### ISSUE TITLE
Nexe hangs in Travis-CI

### ISSUE THREAD

**Issue by garbados** [nexe/nexe#573]
**Is this a BUG or a FEATURE REQUEST?:** Bug? Maybe? Potentially PEBKAC?

**What happened:** Attempting to build binaries using Nexe in a [Travis-CI](https://travis-ci.com/) causes the process to hang. Here is a log excerpt from a build that failed in this way:

```
> DEBUG=* nexe -i bin.js -t linux-x64 -o $NEXE_OUT

- Starting...
ℹ nexe 3.0.0-beta.9

No output has been received in the last 10m0s, this potentially
indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-
out-because-no-output-was-received

The build has been terminated
```

When run locally, Nexe is able to build the binaries in about ten seconds. It is possible the issue is to do with Travis and not Nexe, but absent any debugging information from Nexe I am unable to determine this.

**What you expected to happen:** I expected Nexe to build the binaries, and short of that, to produce useful debug information.

**How to reproduce it (as minimally and precisely as possible):** Here is an example `.travis.yml` directive which will replicate the relevant portions of my setup:

```
after_success:
- DEBUG=* npx nexe@3.0.0-beta.9 -i $NEXE_IN -t linux-x64 -o $NEXE_OUT
```

**Anything else we need to know?:** Not that I can think of :woman_shrugging: 

**Environment**

- Platform(OS/Version): Linux, Ubuntu 14.04
- Host Node Version: Linux x64
- Target Node Version: `linux-x64`, `mac-x64`, `windows-x64`
- Nexe version: 3.0.0-beta.9
- Python Version: 2.7

**Comment by calebboyd** [comment]
I think this is fixed in a later version. Can you update and try again?

**Comment by garbados** [comment]
That did it! Well, almost: the Windows build appears to be missing, and I get this error for each build (including Windows):

```
> npx nexe@latest ...

npx: installed 498 in 8.765s
ℹ nexe 2.0.0-rc.34
Acorn error: Unexpected character '#' (1:0)
File: /home/garbados/code/$PROJECT/bin.js

1  #!/usr/bin/env node
2  'use strict'
3  
4  /*
5  


✔ Compiling result
✔ Entry: 'bin.js' written to: build/$PROJECT-windows-x64.exe
✔ Finished in 0.803s
```

None of the produced executables (Linux, Mac) function. They throw this error:

```
$ ./build/$PROJECT-linux-x64 --help
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'default/bin.js'
```

Tried with `nexe@next` too, but it was unable to produce any of the binaries.

**Comment by calebboyd** [comment]
Sorry I shouldve specified nexe@next

What do you mean it was unable to produce any?

**Comment by garbados** [comment]
> What do you mean it was unable to produce any?

Sorry, I should have been more specific. I meant it encountered a fatal error before producing any artifacts. Here is the full log from using `next@next` in the release process:

```
$ npm run release

> $PROJECT@0.0.0-development prerelease /home/$USER/code/$PROJECT
> mkdir -p build


> $PROJECT@0.0.0-development release /home/$USER/code/$PROJECT
> npm run release:linux && npm run release:windows && npm run release:mac


> $PROJECT@0.0.0-development release:linux /home/$USER/code/$PROJECT
> npx nexe@next -i bin.js -t linux-x64 -o build/$PROJECT-linux-x64

npx: installed 296 in 3.286s
ℹ nexe 3.0.0-beta.11
✔ nexe 3.0.0-beta.11
✔ Finished in 8.314s

Parsing Error:
Can't resolve 'tap' in '/home/$USER/code/$PROJECT/node_modules/require-main-filename'
Can't resolve 'ava' in '/home/$USER/code/$PROJECT/node_modules/check-disk-space'
Error parsing file: "/home/$USER/code/$PROJECT/node_modules/charenc/README.js"
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:2769:13)
    at Parser.pp.unexpected (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:680:8)
    at Parser.pp$3.parseExprAtom (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:2229:10)
    at Parser.pp$3.parseExprSubscripts (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:2074:19)
    at Parser.pp$3.parseMaybeUnary (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:2051:17)
    at Parser.pp$3.parseExprOps (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:1993:19)
    at Parser.pp$3.parseMaybeConditional (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:1976:19)
    at Parser.pp$3.parseMaybeAssign (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:1951:19)
    at Parser.pp$3.parseExpression (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:1916:19)
    at Parser.pp$1.parseStatement (/home/$USER/.npm/_npx/32011/lib/node_modules/nexe/node_modules/acorn/dist/acorn.js:848:45)
Can't resolve 'tape' in '/home/$USER/code/$PROJECT/node_modules/caseless'
Can't resolve 'tape' in '/home/$USER/code/$PROJECT/node_modules/is-typedarray'
Can't resolve './parse' in '/home/$USER/code/$PROJECT/node_modules/qs/dist'
Can't resolve 'test' in '/home/$USER/code/$PROJECT/node_modules/jison/tests/parser'
Can't resolve './formats' in '/home/$USER/code/$PROJECT/node_modules/qs/dist'
Can't resolve './readable-stream-1.0/' in '/home/$USER/code/$PROJECT/node_modules/isstream'
Can't resolve './stringify' in '/home/$USER/code/$PROJECT/node_modules/qs/dist'
Can't resolve './utils' in '/home/$USER/code/$PROJECT/node_modules/qs/dist'
Can't resolve 'tape' in '/home/$USER/code/$PROJECT/node_modules/isstream'
Can't resolve './readable-stream-1.1/' in '/home/$USER/code/$PROJECT/node_modules/isstream'
Can't resolve 'test' in '/home/$USER/code/$PROJECT/node_modules/jison/tests'
Can't resolve './test/auth/index' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './aesprim' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve './parser' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve '_process' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve './slice' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve '..' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve './handlers' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve 'util/' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve '../generated/parser' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve 'benchmark' in '/home/$USER/code/$PROJECT/node_modules/asynckit'
Can't resolve './dict' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve './grammar' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve './support/isBuffer' in '/home/$USER/code/$PROJECT/node_modules/jsonpath'
Can't resolve 'json-diff' in '/home/$USER/code/$PROJECT/node_modules/jsonpath/node_modules/esprima/test'
Can't resolve '../setup' in '/home/$USER/code/$PROJECT/node_modules/ebnf-parser/tests'
Can't resolve 'test' in '/home/$USER/code/$PROJECT/node_modules/jison-lex/tests'
Can't resolve 'test' in '/home/$USER/code/$PROJECT/node_modules/ebnf-parser/tests'
Can't resolve 'test' in '/home/$USER/code/$PROJECT/node_modules/lex-parser/tests'
Can't resolve 'tape' in '/home/$USER/code/$PROJECT/node_modules/safer-buffer'
Can't resolve 'benchmark' in '/home/$USER/code/$PROJECT/node_modules/fast-json-stable-stringify/benchmark'
Can't resolve 'gulp-bump' in '/home/$USER/code/$PROJECT/node_modules/estraverse'
Can't resolve 'gulp-git' in '/home/$USER/code/$PROJECT/node_modules/estraverse'
Can't resolve 'gulp-tag-version' in '/home/$USER/code/$PROJECT/node_modules/estraverse'
Can't resolve 'gulp' in '/home/$USER/code/$PROJECT/node_modules/estraverse'
Can't resolve 'gulp-filter' in '/home/$USER/code/$PROJECT/node_modules/estraverse'
Can't resolve './data/rules.json' in '/home/$USER/code/$PROJECT/node_modules/psl/dist'
Can't resolve 'tap' in '/home/$USER/code/$PROJECT/node_modules/core-util-is'
Can't resolve '/tools/entry-point.js' in '/home/$USER/code/$PROJECT/node_modules/escodegen'
Can't resolve './chai/assertion' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './chai/interface/should' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './addLengthGuard' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './proxify' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './inspect' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './objDisplay' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './test' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './addMethod' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './addChainableMethod' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './getOwnEnumerableProperties' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './getProperties' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './chai/config' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './chai/interface/expect' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './config' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './flag' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './isProxyEnabled' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './getActual' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './getMessage' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './addProperty' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './overwriteMethod' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './compareByInspect' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './isNaN' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve '../config' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './chai/utils' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './chai/core/assertions' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './chai/interface/assert' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve '../../chai' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './transferFlags' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './getOwnEnumerablePropertySymbols' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './expectTypes' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './overwriteProperty' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './overwriteChainableMethod' in '/home/$USER/code/$PROJECT/node_modules/chai'
Can't resolve './getEnumerableProperties' in '/home/$USER/code/$PROJECT/node_modules/chai'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! $PROJECT@0.0.0-development release:linux: `npx nexe@next -i bin.js -t linux-x64 -o build/$PROJECT-linux-x64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the $PROJECT@0.0.0-development release:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/$USER/.npm/_logs/2018-12-21T05_28_24_507Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! $PROJECT@0.0.0-development release: `npm run release:linux && npm run release:windows && npm run release:mac`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the $PROJECT@0.0.0-development release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/$USER/.npm/_logs/2018-12-21T05_28_24_517Z-debug.log
```

**Comment by calebboyd** [comment]
I'm fairly certain we can ignore parsing errors from node_modules...

Try `npx nexe@3.0.0-beta.12`

**Comment by xshadowlegendx** [comment]
I was having the same problem as @garbados. The ``nexe@3.0.0-beta.12`` fixed it. But it does not package the app instead and did not shows any error or log with ``--verbose``.

The was the stdout

    // packing and dokerizing the app
    // other install stuff inside...

    - Starting...
    ℹ nexe 3.0.0-beta.12
    - nexe 3.0.0-beta.12
    ✔ Bundling Resources...
    - Including file: dist/typedefs/hello.graphql
    ✔ Including file: dist/typedefs/hello.graphql
    - Including file: dist/typedefs/other.graphql
    ✔ Including file: dist/typedefs/other.graphql
    - Including file: dist/typedefs/response.graphql
    ✔ Including file: dist/typedefs/response.graphql
    - Including file: dist/typedefs/user.graphql
    ✔ Including file: dist/typedefs/user.graphql
    - Including file: dist/emails/email_verification/html.ejs
    ✔ Including file: dist/emails/email_verification/html.ejs
    - Including file: dist/emails/password_reset/html.ejs
    ✔ Including file: dist/emails/password_reset/html.ejs
    - Included 6 file(s). 0.004 MB

    // nexe ends there
    // other stuff going on not related to packing...

My command to package the app are ``npm run pack:rollup``, running the command not in docker works as expected

**Comment by garbados** [comment]
@xshadowlegendx Presently on holiday. I'll get around to it next week.

**Comment by garbados** [comment]
Works! Closing this issue.
