### ISSUE TITLE
python build error

### ISSUE THREAD

**Issue by tbhaxor** [nexe/nexe#575]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG Report
**What happened:**
Python Build Error
**What you expected to happen:**
It should build the exe
**How to reproduce it (as minimally and precisely as possible):**
nexe index.js --build linux-x64-10.0.0 --verbose 
**Anything else we need to know?:**
Yes, here is the verbose log
```
ℹ nexe 2.0.0-rc.34
✔ Downloading Node.js source from: https://nodejs.org/dist/v11.3.0/node-v11.3.0.tar.gz
✔ Source already downloaded
✔ Compiling result
  Configuring node build: --dest-cpu=x64
Please use either Python 2.6 or 2.7:

  /usr/bin/python2 ./configure --dest-cpu=x64
⠋ Configuring node build: --dest-cpu=x64
Error: python ./configure --dest-cpu=x64 exited with code: 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nexe/lib/compiler.js:205:28)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
✔ Configuring node build: --dest-cpu=x64
✔ Finished in 1.889s
Error: python ./configure --dest-cpu=x64 exited with code: 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nexe/lib/compiler.js:205:28)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

In arch linux
```
$ python --version
Python 3.7.1

$ python3 --version
Python 2.7.15
```

**What i tried beyond nexe previous issue**
```
$ alias python=python2
```

**Environment**

- Platform(OS/Version): Arch Linux 4.19
- Host Node Version:  v11.3.0
- Target Node Version: 10.0.0
- Nexe version: 2.0.0-rc.34
- Python Version: 3.7.1

**Comment by tbhaxor** [comment]
OK new thing

It working with
```
$ sudo mv /usr/bin/python2 /usr/bin/python
```

But not with

```
$ alias python=python2
```

Any comments ?
