### ISSUE TITLE
Nexe spews a bunch of errors running with and without arguments applied

### ISSUE THREAD

**Issue by theNurky** [nexe/nexe#581]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG

**What happened:**
Nexe fails to do anything on execution

**What you expected to happen:**
Compiled binary from my .JS file

**How to reproduce it (as minimally and precisely as possible):**
Install latest Node.JS 11.7.0 version, run `npm i nexe -g`, when you're back at the command prompt, run `nexe` and this should come up:
```
C:\Users\Nurky>nexe
(node:9220) UnhandledPromiseRejectionWarning: Error: No entry file found
    at resolveEntry (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\options.js:135:15)
    at Object.normalizeOptions (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\options.js:150:21)
    at Object.<anonymous> (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\nexe.js:57:41)
    at step (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\nexe.js:32:23)
    at Object.next (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\nexe.js:13:53)
    at C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\nexe.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\nexe.js:3:12)
    at Object.compile (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\lib\nexe.js:52:12)
    at Object.<anonymous> (C:\Users\Nurky\AppData\Roaming\npm\node_modules\nexe\index.js:13:10)
(node:9220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\Users\Nurky>
```

**Anything else we need to know?:**
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\nexe\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
Maybe this has to do something about it

**Environment**

- Platform(OS/Version): Windows 10 Enterprise 64-Bit (Build: 17763.253)
- Host Node Version: 11.7.0
- Target Node Version: 11.7.0
- Nexe version: 2.0.0-rc.34
- Python Version:

What am I missing here? Do I need python? What is going on!?
![image](https://user-images.githubusercontent.com/25286768/51491740-92bf3e80-1daf-11e9-9777-2efc1a9176df.png)

**Comment by calebboyd** [comment]
`Error: No entry file found`

you should provide an input.

The extra stack trace issues have been fixed in v3 (available via `npm i nexe@next`
