### ISSUE TITLE
Nexe binary not working if source contains bcrypt (may be related to node-gyp)?

### ISSUE THREAD

**Issue by giridharangm** [nexe/nexe#586]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG

**What happened:**  
Built an express app (w/ a dependency to `bcrypt`) and tried to run on a machine (without a node installation). It failed execute.  

**What you expected to happen:**  
It should execute and start the express server without any problems.

**How to reproduce it (as minimally and precisely as possible):**  
It looks like `express` is not the problem here. So, to produce a minimal package, install `bcrypt` and invoke `bcrypt.hash()` or any other `bcrypt`'s functions.

**Anything else we need to know?:**  
```sh
internal/modules/cjs/loader.js:777
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\user\node_modules\bcrypt\lib\binding\bcrypt_lib.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:777:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\anju\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\anju\Desktop\routes\auth.js:6:34)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Environment**

- Platform(OS/Version): Windows 10 1809
- Host Node Version: `11.8.0`
- Target Node Version: `NA`
- Nexe version: `3.0.0-beta.15`
- Python Version: `2.7.15`

**Comment by bwin** [comment]
You can distribute your exe with a barebones `node_modules` directory (only containing the `.node`-files of native modules in the right subfolder).
E.g. for bcrypt: `node_modules/bcrypt/lib/binding/bcrypt_lib.node`

Sure, this messes with the whole distribute-just-one-file concept, but maybe it's acceptable in some cases.

**Comment by meteorsnows** [comment]
Still haven learning Native Module much...
Anyone different if our dependencies using Native Module vs N-API? In Node.JS there is 2 or more ways to build native module?
