### ISSUE TITLE
Compile node on Windows

### ISSUE THREAD

**Issue by 3kynox** [nexe/nexe#594]
Hello!

As the other issue is closed: https://github.com/nexe/nexe/issues/499

And it does not permitted me to resolve my problem, I post it here.

I can build with linux, not with Windows.
I previously installed VS17 + Build tools and NASM using @TundraFizz explanations on the previous issue.
Python is 2.7.16 - Both NASM and Python on env.

The result here looks like the one just above.

```
nexe --build -o bitRage-gui-server -r "./config/**/*" -r "./public/**/*" --verbose
i nexe 3.0.0-beta.15
√ Bundling Resources...
√ Including file: ./config/default.json
√ Including file: ./config/production.json
√ Including file: ./config/test.json
√ Including file: ./public/favicon.ico
√ Including file: ./public/index.html
√ Included 5 file(s). 0.020 MB
√ Downloading Node.js source from: https://nodejs.org/dist/v10.15.1/node-v10.15.1.tar.gz
√ Source already downloaded
√ Compiling result
  Configuring node build...
creating icu_config.gypi
* Using ICU in deps/icu-small
WARNING: Using floating patch "tools/icu/patches/62/source/i18n/decimfmt.cpp" from "tools/icu"
creating icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'build_v8_with_gn': 'false',
                 'coverage': 'false',
                 'debug_nghttp2': 'false',
                 'enable_lto': 'false',
                 'enable_pgo_generate': 'false',
                 'enable_pgo_use': 'false',
                 'force_dynamic_crt': 0,
                 'host_arch': 'x64',
                 'icu_data_in': '..\\..\\deps/icu-small\\source/data/in\\icudt62l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '62',
                 'nasm_version': '2.14',
                 'node_byteorder': 'little',
                 'node_debug_lib': 'false',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 64,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_nghttp2': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_target_type': 'executable',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'true',
                 'node_use_large_pages': 'false',
                 'node_use_openssl': 'true',
                 'node_use_pch': 'false',
                 'node_use_perfctr': 'true',
                 'node_use_v8_platform': 'true',
                 'node_with_ltcg': 'false',
                 'node_without_node_options': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.64',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_enable_inspector': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_promise_internal_field_count': 1,
                 'v8_random_seed': 0,
                 'v8_trace_maps': 0,
                 'v8_typed_array_max_size_in_heap': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating config.gypi
creating config.status
creating config.mk
running:
    python tools/gyp_node.py --no-parallel -f msvs -G msvs_version=auto
Warning: Missing input files:
deps\v8\gypfiles\..\src\parsing\preparse-data-format.h
√ Configuring node build...
  Compiling Node with arguments: nosign,release,x64
Note: vcbuild no longer signs by default. "nosign" is redundant.
Looking for Python 2.x
Looking for NASM
Looking for Visual Studio 2017
calling: "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Found MSVS version 15.0
configure  --with-ltcg --dest-cpu=x64
creating icu_config.gypi
* Using ICU in deps/icu-small
WARNING: Using floating patch "tools/icu/patches/62/source/i18n/decimfmt.cpp" from "tools/icu"
creating icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'build_v8_with_gn': 'false',
                 'coverage': 'false',
                 'debug_nghttp2': 'false',
                 'enable_lto': 'false',
                 'enable_pgo_generate': 'false',
                 'enable_pgo_use': 'false',
                 'force_dynamic_crt': 0,
                 'host_arch': 'x64',
                 'icu_data_in': '..\\..\\deps/icu-small\\source/data/in\\icudt62l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '62',
                 'nasm_version': '2.14',
                 'node_byteorder': 'little',
                 'node_debug_lib': 'false',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 64,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_nghttp2': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_target_type': 'executable',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'true',
                 'node_use_large_pages': 'false',
                 'node_use_openssl': 'true',
                 'node_use_pch': 'false',
                 'node_use_perfctr': 'true',
                 'node_use_v8_platform': 'true',
                 'node_with_ltcg': 'true',
                 'node_without_node_options': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.64',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_enable_inspector': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_promise_internal_field_count': 1,
                 'v8_random_seed': 0,
                 'v8_trace_maps': 0,
                 'v8_typed_array_max_size_in_heap': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating config.gypi
creating config.status
creating config.mk
running:
    python tools/gyp_node.py --no-parallel -f msvs -G msvs_version=auto
Warning: Missing input files:
deps\v8\gypfiles\..\src\parsing\preparse-data-format.h
Project files generated.
  gtest.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\gtest.lib
  http_parser.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\http_parser.lib
  cares.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\cares.lib
  libuv.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\libuv.lib
  nghttp2.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\nghttp2.lib
  Assemble
  v8_libbase.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\v8_libbase.lib
  v8_libplatform.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\v8_libplatform.lib
  v8_libsampler.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\v8_libsampler.lib
  zlib.vcxproj -> C:\Users\Thierry PROST\.nexe\10.15.1\Release\lib\zlib.lib
  Assemble
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:780: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:800: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:821: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:842: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:987: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:998: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1002: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1005: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1008: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1011: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1014: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1017: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1020: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1023: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1127: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1139: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1151: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1163: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1175: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1187: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1199: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1211: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1228: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1230: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1232: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1234: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1236: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1238: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1240: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1242: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1268: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1288: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1309: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1330: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1475: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1492: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1497: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1501: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1503: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1506: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1508: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1511: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1513: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1516: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1518: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1520: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1522: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1524: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1526: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1528: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1530: error: operation size not specified
  config\archs\VC-WIN64A\asm\crypto\aes\aesni-mb-x86_64.asm:1532: error: operation size not specified
C:\Users\Thierry PROST\.nexe\10.15.1\deps\openssl\openssl.targets(28,5): error MSB3721: La commande "call nasm.exe "-f win64" "-DNEAR" "-Ox" "-g" "-o" "Release\obj\openssl\aesni-mb-x86_64.obj" "config\archs\VC-WIN64A\asm\crypto\aes\aesn
i-mb-x86_64.asm"" s'est arrêtée avec le code 1. [C:\Users\Thierry PROST\.nexe\10.15.1\deps\openssl\openssl.vcxproj]
√ Compiling Node with arguments: nosign,release,x64
√ Node binary compiled
- Writing result to fileevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Thierry PROST\.nexe\10.15.1\Release\node.exe'
Emitted 'error' event at:
    at MultiStream.destroy (C:\Users\Thierry PROST\AppData\Roaming\npm\node_modules\nexe\node_modules\multistream\index.js:64:17)
    at ReadStream.onError (C:\Users\Thierry PROST\AppData\Roaming\npm\node_modules\nexe\node_modules\multistream\index.js:132:10)
    at Object.onceWrapper (events.js:277:13)
    at ReadStream.emit (events.js:189:13)
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

Thanks for help

**Comment by calebboyd** [comment]
Hi @3kynox unfortunately I can't offer much guidance in terms of setting up your machine to build node. All nexe does during the build step is execute the command as documented in node's [BUILDING.md](https://github.com/nodejs/node/blob/master/BUILDING.md#windows-1)

Here is a look at what nexe's own build is doing (in AppVeyor). It may help.
https://github.com/nexe/nexe/blob/c5cdbd93805532868421d86657b1f1a48401c9ca/appveyor.yml#L15-L17
