### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type boolean

### ISSUE THREAD

**Issue by GiuseppeCesarano** [nexe/nexe#604]
This is a:
- [x] Bug Report 
- [ ] Feature Request
- [ ] Other  

I'm trying to build a binary but keep getting this error:
```
nexe -i main.js -o main --build --python 
ℹ nexe 3.0.1
✔ Already downloaded...
✔ Configuring node build: --dest-cpu=x64
✔ Finished in 33.06s
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type boolean
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:414:3)
    at Object.spawn (child_process.js:553:16)
    at /usr/lib/node_modules/nexe/lib/compiler.js:246:29
    at new Promise (<anonymous>)
    at NexeCompiler._runBuildCommandAsync (/usr/lib/node_modules/nexe/lib/compiler.js:245:16)
    at NexeCompiler._configureAsync (/usr/lib/node_modules/nexe/lib/compiler.js:270:21)
    at NexeCompiler.<anonymous> (/usr/lib/node_modules/nexe/lib/compiler.js:281:51)
    at step (/usr/lib/node_modules/nexe/lib/compiler.js:62:23)
    at Object.next (/usr/lib/node_modules/nexe/lib/compiler.js:43:53)
```  

My project's dependencies:
```
    "@postlight/mercury-parser": "^2.0.0",
    "jsdom": "^14.0.0",
    "nodemailer": "^6.0.0"
 ```

Host Machine:
* **Platform(OS/Version):** Manjaro 18.0.4 Illyria (x86-64)
* **Host Node Version:** 11.13.0
* **Nexe version:** 3.0.1
* **Python2 Version:** 2.7.16

**Comment by calebboyd** [comment]
The python argument takes a string if you use it, You probably don't need it if all you have installed on your machine is python 2

https://github.com/nexe/nexe#python-string
