### ISSUE TITLE
--ico isn't work well

### ISSUE THREAD

**Issue by zhaojunlike** [nexe/nexe#628]
PS E:\workspace\socket.io-tpl\lb.socket.io> node .\index.js
i nexe 3.0.1
√ Already downloaded...
√ Configuring node build...
√ Finished in 12.908s
Error: python configure.py exited with code: 1
    at new NexeError (E:\workspace\socket.io-tpl\lb.socket.io\node_modules\nexe\lib\compiler.js:83:28)
    at ChildProcess.<anonymous> (E:\workspace\socket.io-tpl\lb.socket.io\node_modules\nexe\lib\compiler.js:263:28)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

- Platform(OS/Version): win10
- Host Node Version: 10.x
- Target Node Version: 10.x
- Nexe version: 3.0.1
- Python Version: python2.7

**Comment by zhaojunlike** [comment]
index.js

```
const {compile} = require('nexe');

compile({
    input: './build/index.js',
    output: './release/app.exe',
    build: true, //required to use patches
    // resources: ['./config/**/*'],
    ico: './config/logo.ico',
    target: {},
    rc: {
        CompanyName: "ACME Corp",
        PRODUCTVERSION: "17,3,0,0",
        FILEVERSION: "1,2,3,4"
    },
    // build: true
}).then(() => {
    console.log('success')
}).catch(e => {
    console.log(e);
});

```

**Comment by calebboyd** [comment]
This should be fixed now
