### ISSUE TITLE
Is it possible to use a local source file?

### ISSUE THREAD

**Issue by ctlkkc** [nexe/nexe#656]
```
$ nexe dashboard.js -t linux-x64 --build --sourceUrl /home/ctlkkc/install/source/node-v8.9.3-source.tar.gz                                      â
 ¹ nexe 3.3.2
â Downloading Node.jssource from: /home/ctlkkc/install/source/node-v8.9.3-source.tar.gz
â Finished in 10.45s
RequestError: Protocol "http:" not supported. Expected "https:"
    at EventEmitter.cacheReq.on.err (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/download/node_modules/got/index.js:156:22)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at makeRequest (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/cacheable-request/src/index.js:96:9)
    at Promise.resolve.then.then.cacheEntry (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/cacheable-request/src/index.js:104:14)
    at <anonymous>
```

Can someone tell me if using a local file is possible? I am a user that cannot access external sites from sandbox. 
Thanks

**Comment by calebboyd** [comment]
Its not possible at this time. I'll leave this issue open for tracking the option for a URL or filepath via a `--source` option. (deprecating --sourceUrl)

In the meantime, you can always extract your local source tar.gz to ~/.nexe/8.9.3
and use `--build -t 8.9.3` options

**Comment by ctlkkc** [comment]
Thanks @calebboyd 
 I got the following issues using v8.9.3, v10.15.3, and v8.16.0. Did I miss any option? What is the recommended source version? 
```
$ nexe dashboard.js --build -t x64-8.9.3
â
 ¹ nexe 3.3.2
â Already downloaded...
â Finished in 10.748s
Error: ENOENT: no such file or directory, open '/home/ctlkkc/.nexe/8.9.3/lib/_third_party_main.js'

$ nexe dashboard.js --build -t x64-10.15.3
â
 ¹ nexe 3.3.2
â Already downloaded...
â Finished in 10.435s
SyntaxError: Invalid regular expression: /(?<!void )ProcessArgv\(/: Invalid group
    at /home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:55:51
    at step (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:32:23)
    at Object.next (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:13:53)
    at /home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:3:12)
    at disableNodeCli (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:40:12)
    at tryInvokeMiddleware (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/app-builder/lib/compose.js:23:59)
    at /home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/app-builder/lib/compose.js:34:16
    at next (/home/ctlkkc/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/app-builder/lib/compose.js:33:71)

$ nexe dashboard.js --build -t x64-10.16.0
â
 ¹ nexe 3.3.2
â Already downloaded...
â Finished in 28.744s
SyntaxError: Invalid regular expression: /(?<!void )ProcessArgv\(/: Invalid group
    at /home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:55:51
    at step (/home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:32:23)
    at Object.next (/home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:13:53)
    at /home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:3:12)
    at disableNodeCli (/home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/lib/patches/disable-node-cli.js:40:12)
    at tryInvokeMiddleware (/home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/app-builder/lib/compose.js:23:59)
    at /home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/app-builder/lib/compose.js:34:16
    at next (/home/kcharl/install/npm/node-v8.9.3-linux-x64/lib/node_modules/nexe/node_modules/app-builder/lib/compose.js:33:71)
```

**Comment by vexorian** [comment]
This is an absolute showstopper to those looking to do continuos integration using nexe. Even the latest beta version claims to have this feature but it still doesn't allow the file:// protocol.

**Comment by calebboyd** [comment]
FWIW you can point it at temp directory where it will attempt to resolve the file first.
`nexe --temp TEMP -t alpine-x86-12.10.0`

Looks for the file first, at: 

`TEMP/alpine-x86-12.10.0`

**Comment by vexorian** [comment]
Thank you! I could finally speed up all my processes
