### ISSUE TITLE
Node child_process.spawn doesn't work as expected

### ISSUE THREAD

**Issue by codan84** [nexe/nexe#664]
**What happened**:
I have a simple app that I want to package with nexe into a standalone library. The problem is - the app uses nodes `child_process.spawn` to spawn a copy of itself. This seems not to work very well.  
Calling
```
cp.spawn(
    './myapp',
    ['slave'],
    {
      cwd: appDir,
      detached: true,
      stdio: ['inherit', 'inherit', 'inherit', 'ipc']
    }
  )
```
Would give an error like:
```
module.js:540
    throw err;
    ^

Error: Cannot find module 'slave'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at Object.<anonymous> (/Users/gruszd01/workspace/nexe-test/dist/myapp:352:30)
    at Module._compile (module.js:643:30)
    at _third_party_main.js:37:36
    at NativeModule.compile (bootstrap_node.js:613:7)
    at Function.NativeModule.require (bootstrap_node.js:558:18)
    at bootstrap_node.js:133:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

**What you expected to happen**:
When running `child_process.spawn` with a command set to the packaged binary itself, the binary starts correctly.

**How to reproduce it (as minimally and precisely as possible)**:
```
npm init -y
npm install --save-dev nexe
touch index.js
```

Add this script to `package.json`:
```
"build": "npx nexe -t x64-8.9.4 index.js -o dist/myapp"
```

Add this to `index.js`:
```
const cp = require('child_process')

const { dirname } = require('path')

console.log('Hey there captain!')
console.log(process.argv)

const appDir = dirname(process.argv[0])

const runSlave = () => {
  setInterval(() => {
    console.log('Running slave...')
  }, 500)
}

const runMaster = () => {
  console.log('Starting a slave...')
  const slave = cp.spawn(
    './myapp',
    ['slave'],
    {
      cwd: appDir,
      detached: true,
      stdio: ['inherit', 'inherit', 'inherit', 'ipc']
    }
  )
  slave.on('exit', () => {
    console.log('Slave died!')
  })
  setInterval(() => {
    console.log('Running master...')
  }, 500)
}

switch (process.argv[2]) {
  case 'slave':
    runSlave()
    break
  case 'master':
  default:
    runMaster()
}
```

Then:
```
npm run build
./dist/myapp
```

**Anything else we need to know?**:
Initially I found an issue after building the binary in ubuntu docker. But same thing happens on the latest OSX.

**Environment**:
- Platform(OS/Version): OSX 10.14.3 (same issue on Ubuntu)
- Host Node Version: v10.16.2
- Target Node Version: v8.9.4
- Nexe version: 3.3.2
- Python Version: 2.7.15

**Comment by codan84** [comment]
Interesting, running spawn like so:
```
cp.spawn(
    './myapp',
    [join(appDir, 'index.js'), 'slave'],
    {
      cwd: appDir,
      detached: true,
      stdio: ['inherit', 'inherit', 'inherit', 'ipc']
    }
  )
```
Seem to do the trick. This is counterintuitive tho, seeing as running the script directly from bash doesn't require the path to `index.js`

**Comment by kayahr** [comment]
I have the same problem with [pkg](https://www.npmjs.com/package/@yao-pkg/pkg) so maybe this is not a nexe issue but a special thing in Node.js.

I created two example binaries. The first one calls the second one and the second one calls the first one. This works without any problems. But as soon as the binary calls itself, I get the `Cannot find module 'first-param'` error. It looks to me as if Node.js does some optimization here. When argv0 of the spawned process matches the current argv0 then the process seems to be created differently (maybe just forked) and the module name (the JS file packaged into the binary) is required as first parameter.

**Comment by codan84** [comment]
Wow, over 5 years old and not even a comment from code owners, hopeless
