### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by kanso-git** [nexe/nexe#678]
Trying to build a node app that uses node-native-printer.
As you might know node-native-printer needs edge , so I have installed a pre-compiled version of edge "edge-js".
when I run my app it prints a simple text 'hellow world" 
code is below :
`import express, { Request, Response } from 'express'
const printer = require('node-native-printer')

const app = express()

const printerName = 'EPSON'
printer.setPrinter(printerName)

printer.printText('hello world nexe...')
const PORT = 3700

app.listen(PORT, () => {
  console.log('server is up and runing on port ' + PORT)
})
`
the problem is when I tried to ship it with nexe, the build was ok  but when I run the .exe i've got the following issue 

```
C:\playground\nexe-build\node-printer>node-printer.exe
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\playground\nexe-build\node-printer\node_modules\edge-js\lib\edge.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

anyone can help me to solve this issue .
many thanks in advance

**Comment by RajanZhan** [comment]
when the author fix this bug?

**Comment by Abhishek150995** [comment]
I have an application that interacts with C# Dll using 'edge-js'. Earlier I used electron to package the application so I used 'electron-edge-js' node modules, it worked perfectly fine. But now I want to switch to nexe packaging, but its generating error that it cannot find the 'edge-js' module at a particular location

Error: The specified module could not be found.
\?\C:\Users..\Desktop.............\xyz\node_modules\edge-js\lib\native\win32\x64\12.13.0\edge_nativeclr.node

And when I explicitly place the node_modules at the location it generates different error

Error: Module did not self-register.

Please suggest!

**Comment by Abhishek150995** [comment]
@kanso-git Did you find any solution for the same?

Please suggest. Thanks in advance.
