### ISSUE TITLE
Is worker_threads supported?

### ISSUE THREAD

**Issue by pacop** [nexe/nexe#680]
**What happened**:
worker_threads throws a MODULE_NOT_FOUND

```
user@/tmp$ ./main
main.js

events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module '/tmp/children.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:139:25)
    at MessagePort.emit (events.js:210:5)
    at MessagePort.onmessage (internal/worker/io.js:70:8)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:176:10)
    at Worker.[kOnMessage] (internal/worker.js:186:37)
    at MessagePort.<anonymous> (internal/worker.js:118:57)
    at MessagePort.emit (events.js:210:5)
    at MessagePort.onmessage (internal/worker/io.js:70:8) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**What you expected to happen**:
When running as just plain nodejs script everything justo works fine

**How to reproduce it (as minimally and precisely as possible)**:

main.js
```javascript
const {Worker} = require('worker_threads');

new Worker('./children.js', {workerData: 'Data from parent'});

console.log('main.js');
```

children.js
```javascript
const {
  isMainThread, parentPort, workerData
} = require('worker_threads');

console.log('b.js isMainThread', isMainThread);
console.log('workerData: 'workerData);
```
Running nexe as: `nexe --build -r children.js main.js`

**Anything else we need to know?**:
I have checked [#557](https://github.com/nexe/nexe/issues/557) where @calebboyd assigns as milestone for 3.0, but for me it doesn't work.

**Environment**:
- Platform(OS/Version): Botn Windows 7 32 bits and Ubuntu 18.04 64 bits
- Host Node Version: checked on 12.2.0 and 12.11.1
- Target Node Version:
- Nexe version: 3.3.2
- Python Version: 2.7.15+

**Comment by calebboyd** [comment]
They're not supported at this time. The Worker object is created from a file url passed to the internal worker c++ class - the virtual file system only exists in JS at this time. So files loaded from C++ are not loaded from the included bundle.

PRs welcome!

**Comment by Gawran** [comment]
Neat thing about worker threads is the eval option. If you really need to run something in a separate process you can always fetch a js file via fs.readFile() and pass it to the worker thread as a string.

```
const fs  = require("fs");
const { Worker, SHARE_ENV, isMainThread } = require('worker_threads');

//first way via readFile
const workerFile = fs.readFileSync('some/path/someWorkerFile.js').toString(); 
//sencond way via inline script in multiline string
const workerScript = `
    const { Worker, SHARE_ENV } = require('worker_threads');
    proccess.env.SET_IN_WORKER_STR = 'Hello from inline script';
    process.exit();
`;
if (isMainThread) {
    new Worker(workerFile', { eval: true, env: SHARE_ENV })
      .on('exit', () => {
        console.log(process.env.SET_IN_WORKER); 
      });
    new Worker(workerScript', { eval: true, env: SHARE_ENV })
  .    on('exit', () => {
        console.log(process.env.SET_IN_WORKER_STR);  // Prints 'Hello from inline script'
    });
}

```

**Comment by sergiz** [comment]
Adding to the @Gawran's idea, you can simply use require to run your script. This way you avoid manually loading the file source beforehand and it feels less hacky to me.

`new Worker('require(\'./some/path/someWorkerFile.js\')', { eval: true })`

**Comment by Julusian** [comment]
I'm trying to do the way @sergiz suggests, but the require is failing for me as the worker_thread doesn't appear to have the VFS mounted.
Even electron doesn't have this solved, the `new Worker(...)` call won't read a file from inside the asar, and it doesn't mount the VFS either. But there is a npm library to [mount an asar](https://www.npmjs.com/package/asar-node) which can be used to make it work. A similar library here would be a sufficient for now. 
This does look like it will be made simpler by https://github.com/nexe/nexe/pull/741 too

**Comment by yapsang** [comment]
has there been any developement with worker_threads?
