### ISSUE TITLE
Nexe binary not finding file on filesystem

### ISSUE THREAD

**Issue by wilmardo** [nexe/nexe#709]
**What happened**:

The app does not start properly when compiled with nexe:
```console
/zwave2mqtt # ./zwave2mqtt
  z2m:App Application path:/zwave2mqtt +0ms
/zwave2mqtt/lib/jsonStore.js:50
  if (storage_helper.store[model.file]) { return storage_helper.store[model.file] } else { throw Error('Requested file not present in store: ' + model.file) }
                                                                                           ^

Error: Requested file not present in store: /config/settings.json
    at StorageHelper.get (/zwave2mqtt/lib/jsonStore.js:50:98)
    at startGateway (/zwave2mqtt/app.js:41:28)
    at Object.<anonymous> (/zwave2mqtt/app.js:201:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**What you expected to happen**:

The same behaviour as npm start. The binary hasn't been moved so all the system libs and node_modules are still in the expected place.

```console
/zwave2mqtt # npm start

> zwave2mqtt@2.0.6 start /zwave2mqtt
> node bin/www

  z2m:Store nodes.json not found +0ms
  z2m:Store scenes.json not found +4ms
  z2m:App Application path:/zwave2mqtt +0ms
Initialising OpenZWave 1.6.992 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/local/etc/openzwave/
        User settings path : /data
        Option Overrides : --Logging undefined --ConsoleOutput undefined --QueueLogLevel 6 --DriverMaxAttempts 9999 --SaveConfiguration false --PollInterval 1000 --NetworkKey 0xC7,0xC1,0x2C,0xBD,0x8E,0x0B,0xE2,0x66,0x05,0xA0,0x2A,0x06,0xA0,0x72,0x61,0x8D --AssumeAwake true
  z2m:Zwave Connecting to /dev/ttyACM0 +0ms
2019-12-18 13:33:08.630 Error, Cannot find a path to the configuration files at /usr/local/etc/openzwave/, Using config/ instead...
2019-12-18 13:33:08.631 Warning, Failed to Parse config/options.xml: Failed to open file
2019-12-18 13:33:08.631 Warning, Failed to Parse /data/options.xml: Failed to open file
```
**How to reproduce it (as minimally and precisely as possible)**:

Steps to reproduce (docker needed):

```
git clone --branch nexe-bug-report https://github.com/LANsible/docker-zwave2mqtt.git
cd docker-zwave2mqtt
docker build --build-arg ARCHITECTURE=amd64 -t test . --no-cache
docker run -it test
# ./zwave2mqtt
```

**Anything else we need to know?**:

I straced (`strace -fff -e trace=open,close,read,write,connect,accept,stat ./zwave2mqtt`) the binary and the errors seems to relate to `body-parser`. It can't find the qs file:

```console
[pid    13] write(19, "  \33[35;1mz2m:App \33[0mApplication"..., 64  z2m:App Application path:/zwave2mqtt +0ms
) = 64
[pid    13] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs", 0x7ffc1c40f330) = -1 ENOENT (No such file or directory)
[pid    13] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.js", 0x7ffc1c40f260) = -1 ENOENT (No such file or directory)
[pid    13] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.json", 0x7ffc1c40f260) = -1 ENOENT (No such file or directory)
[pid    13] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.node", 0x7ffc1c40f260) = -1 ENOENT (No such file or directory)
[pid    13] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.mjs", 0x7ffc1c40f260) = -1 ENOENT (No such file or directory)
/zwave2mqtt/lib/jsonStore.js:50
  if (storage_helper.store[model.file]) { return storage_helper.store[model.file] } else { throw Error('Requested file not present in store: ' + model.file) }
                                                                                           ^

Error: Requested file not present in store: /config/settings.json
    at StorageHelper.get (/zwave2mqtt/lib/jsonStore.js:50:98)
    at startGateway (/zwave2mqtt/app.js:41:28)
    at Object.<anonymous> (/zwave2mqtt/app.js:201:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

I tried to symlinking the qs file the location:
```
ln -sf /zwave2mqtt/node_modules/qs /zwave2mqtt/node_modules/body-parser/node_modules/qs
```

```console
[pid   252] write(19, "  \33[35;1mz2m:App \33[0mApplication"..., 64  z2m:App Application path:/zwave2mqtt +0ms
) = 64
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.js", 0x7fff9be92a50) = -1 ENOENT (No such file or directory)
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.json", 0x7fff9be92a50) = -1 ENOENT (No such file or directory)
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.node", 0x7fff9be92a50) = -1 ENOENT (No such file or directory)
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs.mjs", 0x7fff9be92a50) = -1 ENOENT (No such file or directory)
[pid   252] open("/zwave2mqtt/node_modules/body-parser/node_modules/qs/package.json", O_RDONLY|O_CLOEXEC) = 20
[pid   252] close(20)                   = 0
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs/lib/index.js", {st_mode=S_IFREG|0644, st_size=211, ...}) = 0
[pid   252] stat("/zwave2mqtt/node_modules/body-parser/node_modules/qs", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
/zwave2mqtt/lib/jsonStore.js:50
  if (storage_helper.store[model.file]) { return storage_helper.store[model.file] } else { throw Error('Requested file not present in store: ' + model.file) }
                                                                                           ^

Error: Requested file not present in store: /config/settings.json
    at StorageHelper.get (/zwave2mqtt/lib/jsonStore.js:50:98)
    at startGateway (/zwave2mqtt/app.js:41:28)
    at Object.<anonymous> (/zwave2mqtt/app.js:201:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

This solves the file not being found but not the issue we are trying to fix.
Then I found #639 and #639 I suspect this being an issue with Nexe but the issue doesn't seem to be the same since this isn't related to native modules.

Added some debug in the startup code but the file is present at the location:
```javascript
const find = require('shelljs').find;
debug(find('/config').slice(0));
```

```console
/zwave2mqtt # ./zwave2mqtt
  z2m:App [ '/config', '/config/settings.json' ] +17ms
  z2m:App Application path:/zwave2mqtt +6ms
/zwave2mqtt/lib/jsonStore.js:50
  if (storage_helper.store[model.file]) { return storage_helper.store[model.file] } else { throw Error('Requested file not present in store: ' + model.file) }
                                                                                           ^

Error: Requested file not present in store: /config/settings.json
    at StorageHelper.get (/zwave2mqtt/lib/jsonStore.js:50:98)
    at startGateway (/zwave2mqtt/app.js:45:28)
    at Object.<anonymous> (/zwave2mqtt/app.js:205:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Environment**:
- Platform(OS/Version): Alpine:edge (Docker)
- Host Node Version: v12.13.1
- Target Node Version: v12.13.1
- Nexe version: 4.0.0-beta.3
- Python Version: 3.8.0

Related: #635? #639

Please let me know if I can provide some more information or help developing a fix ❤️

**Comment by wilmardo** [comment]
Fixed this, the app doesn't use app.js as npm start command but bin/www.
Now when running nexe with bin/www instead of app.js it works!
