### ISSUE TITLE
Build option on ARM detects arch incorrectly

### ISSUE THREAD

**Issue by nmarus** [nexe/nexe#724]
**What happened**:
Running with build option on Raspberry Pi detects arch as `arm7l` however configure.py does not accept `arm7l` as a valid assignment to `--dest-cpu`. However, when running configure.py directly with `--dest-cpu=arm` it works. Everything works fine on x64 arch.

**What you expected to happen**:
Detect `dest-cpu` as `arm` or translate `arm7l` detection.

**How to reproduce it (as minimally and precisely as possible)**:

**Code Snippet:**

```js
await nexe.compile({
    build: (os.arch() !== 'x64'),
    input: path.join(dist, 'bootloader/launcher-cli.js'),
    output: path.join(bin, 'launcher'),
    resources: [
      path.join(dist, 'bootloader/**/*'),
      path.join(dist, 'utils/**/*'),
      path.join(dist, 'logger/**/*'),
    ],
  });
```

**Error:**

```
NexeError: python ./configure.py --dest-cpu=arm7l exited with code: 2
    at new NexeError (/home/pi/test/node_modules/nexe/lib/compiler.js:83:28)
    at ChildProcess.<anonymous> (/home/pi/test/node_modules/nexe/lib/compiler.js:274:28)
    at Object.onceWrapper (events.js:313:26)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Testing:**

```
$ cd ~/.nexe/12.14.1
$ python ./configure.py --dest-cpu=arm7l
Usage: configure.py [options]

configure.py: error: option --dest-cpu: invalid choice: 'arm7l' (choose from 'arm', 'arm64', 'ia32', 'mips', 'mipsel', 'mips64el', 'ppc', 'ppc64', 'x32', 'x64', 'x86', 'x86_64', 's390x')

$ echo $?
2
```

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Raspian an Raspberry PI 3
- Host Node Version: 12.14.1
- Target Node Version: 12.14.1
- Nexe version: 3.3.2
- Python Version: 2.7.13

**Comment by nmarus** [comment]
This might be related to https://github.com/nexe/nexe/issues/424#issuecomment-523523630
