### ISSUE TITLE
Nexe can’t find (staticly required) sub-modules of a particular module

### ISSUE THREAD

**Issue by aral** [nexe/nexe#748]
## To reproduce

On latest Node LTS (Node v12.16.2):

```sh
git clone https://source.small-tech.org/site.js/app.git site.js
cd site.js
git checkout a4fd1c2
npm i
npm run install-locally
site --version
```

## What should happen

Site.js should run and show its version number.

## What actually happens

The following error is shown:

```
Error: Cannot find module '@small-tech/auto-encrypt'
Require stack:
- /usr/local/bin/node_modules/@small-tech/https/index.js
- /usr/local/bin/index.js
- /usr/local/bin/bin/commands/version.js
- /usr/local/bin/bin/site.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/bin/node_modules/@small-tech/https/index.js:6:30)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/bin/node_modules/@small-tech/https/index.js',
    '/usr/local/bin/index.js',
    '/usr/local/bin/bin/commands/version.js',
    '/usr/local/bin/bin/site.js'
  ]
}
```

## Workaround

To implement the workaround (following on from previous instructions):

```sh
git checkout master
npm run install-locally
site --version
```

Now you should see Site.js run properly and display its version.

The difference between the two commits is this:

```diff
diff --git a/bin/build.js b/bin/build.js
index 34ace67..72f9375 100755
--- a/bin/build.js
+++ b/bin/build.js
@@ -110,8 +110,13 @@ if (platform === 'linux' && cpuArchitecture === 'arm') { currentPlatformBinaryPa
 
 // Common resources.
 const resources = [
-  'package.json',   // Used to get the app’s version at runtime.
-  'bin/commands/*', // Conditionally required based on command-line argument.
+  'package.json',                              // Used to get the app’s version at runtime.
+  'bin/commands/*',                            // Conditionally required based on command-line argument.
+
+  'node_modules/@small-tech/auto-encrypt/**/*' // This *should not* be necessary, given that the @small-tech/https
+                                               // module has a static require for @small-tech/auto-encrypt (just like
+                                               // it does for auto-encrypt-localhost, which doesn’t require explicit
+                                               // bundling). Assuming that it’s a bug in Nexe.
 ]
 
 const input = 'bin/site.js'
```

So I’ve had to manually specify the @small-tech/auto-encrypt module [that is statically required by the @small-tech/https.module](https://source.small-tech.org/site.js/lib/https/-/blob/master/index.js#L6), which itself [is statically required by Site.js](https://source.small-tech.org/site.js/app/-/blob/master/index.js#L21).

### Oddities:

  - There are no dynamic requires
  - The issue does not manifest for the @small-tech/auto-encrypt-localhost module, which is required by the @small-tech/https module in the same way
  - The issue also manifests for modules required by @small-tech/auto-encrypt (e.g., ocsp).

I’m sorry I haven’t had a chance to reproduce the error more simply. I hope this gives you something to go on.

## Environment

- Platform(OS/Version): Pop!_OS 19.10 (~Ubuntu 19.10)
- Host Node Version: 12.16.2
- Target Node Version: 12.16.2
- Nexe version: 3.3.2
- Python Version: 2.7.17 & 3.7.5

**Comment by calebboyd** [comment]
Interesting! This is probably a bug in https://github.com/nexe/resolve-dependencies

**Comment by aral** [comment]
Hmm, interesting – thanks for the pointer. So I just popped this into the root directory of Site.js (in a file called test-dependencies.js):

```js
const { resolve } = require('resolve-dependencies')

;(async () => {
  const { entries, files } = await resolve({ entries: './index.js', loadContent: false })
  console.log(Object.keys(files))
})()
```

And ran:

```sh
node test-dependencies.js | grep auto-encrypt
```

And it’s finding the auto-encrypt module. So possibly this is not the issue?

```
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt-localhost/index.js',
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt-localhost/lib/mkcertBinaryForThisMachine.js',
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt/index.js',
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt/lib/util/Pluralise.js',
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt/package.json',
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt/lib/LetsEncryptServer.js',
  '/home/aral/small-tech/site.js/app/node_modules/@small-tech/auto-encrypt-localhost/lib/installCertutil.js',
```

**Comment by calebboyd** [comment]
LMK if this can be closed!

**Comment by aral** [comment]
Thanks again :) Fixed in nexe@next :partying_face:
