### ISSUE TITLE
Publish prebuild of node 14

### ISSUE THREAD

**Issue by ricardopolo** [nexe/nexe#754]
**What would you like to be added**:
Pre build binaries for node 14

**Why is this needed**:
Node 14 is the current version and fixes important issues regading memory management (RAM).  A prebuild version makes the usage of nexe much easier.

**Comment by FabianTe** [comment]
Hi, just out of curiosity: Why is there a prebuild node 14 for windows but not for linux?

I'd like to migrate to Nexe from zeit/pkg because pkg doesn't even support node 12. But for that I need node 14 on linux.

**Comment by calebboyd** [comment]
It looks like the build is currently broken for node 14 in CI (and I believe even the windows builds are not working based on the issues i've seen come in. Once node 14 hits LTS later this month I should have some time to look at it.

**Comment by jaubourg** [comment]
@calebboyd any update on this?

**Comment by aral** [comment]
In case it helps, my Nexe base build with Node 14.15.0 on Linux with my beta-6 fork completes but fails with the following error on launch:

```
internal/modules/cjs/loader.js:1003
  callbackMap.set(compiled.cacheKey, {
              ^

TypeError: Cannot read property 'set' of undefined
    at wrapSafe (internal/modules/cjs/loader.js:1003:15)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at internal/bootstrap/pre_execution.js:122:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:123:3)
    at internal/main/repl.js:19:1
```

(I’m now trying it with beta-14 as I type this. Will report back. But something’s changed between beta-6 and beta-14 where my resources aren’t being included so I have to debug that also – will open a separate issue if it’s not a known breaking change once I’ve narrowed it down.)

**Comment by calebboyd** [comment]
I had planned to look into this once it hit LTS but I'm also taking some much needed time away so I won't have time for a few weeks. Thanks for digging @aral !

**Comment by aral** [comment]
Of course, @calebboyd, no rush. Maybe when you’re back and tackling it, if you can share your process, I’d be happy to try and help with future Node upgrades :)

**Comment by Numenorean** [comment]
any news? i still get Error: https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-12.19.0 is not available

**Comment by baparham** [comment]
@calebboyd if you perhaps shared sort of architecture design overview file it would let would-be contributors help support this project so you aren't the only one who has to spent their free time fixing other peoples' problems. :-)

as @aral mentioned, I'd also be interested in helping, but it was a bit daunting trying to fully grasp how `nexe` works under the hood by just reading the src alone.

**Comment by calebboyd** [comment]
Here are some issues that might help
#850 
#741 
https://github.com/nexe/nexe/issues/733#issuecomment-753737232

**Comment by cspotcode** [comment]
@baparham @calebboyd should we start a Github Discussion thread or sub-forum to discuss nexe's architecture, or would you prefer to keep everything in issues?

**Comment by calebboyd** [comment]
Sounds like an excellent use of a new feature. I'll make one

**Comment by lihue** [comment]
Is there a workaround for using Node 14?
