### ISSUE TITLE
cannot read property 'length' on undefined

### ISSUE THREAD

**Issue by OSG-Proj** [nexe/nexe#756]
**What happened**:
root@localhost:~/nodeApp# nexe .
/usr/local/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader-pool.js:73
var cpus = require('os').cpus().length;                                                ^
                                                        TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader-pool.js:73:32)                                                     at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)     at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)                     at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)                   at Object.<anonymous> (/usr/local/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/index.js:58:21)
    at Module._compile (module.js:652:30)

**What you expected to happen**:
just work
**How to reproduce it (as minimally and precisely as possible)**:
idk
**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Ubuntu Latest
- Host Node Version: Latest
- Target Node Version: Latest
- Nexe version: Latest
- Python Version: no python installed

**Comment by calebboyd** [comment]
what happens if you do this: `node -p "require('os').cpus().length"`

**Comment by calebboyd** [comment]
Can't reproduce, not enough information in report.
