### ISSUE TITLE
TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by bernzrdo** [nexe/nexe#768]
I compiled my Node.JS script and when I ran the executable it displayed this error:

    internal/modules/cjs/loader.js:1122

        throw err;
        ^

    TypeError: Cannot read property 'set' of undefined
    [90m    at Object.compileFunction (vm.js:375:17)[39m
    [90m    at wrapSafe (internal/modules/cjs/loader.js:1106:15)[39m
    [90m    at Module._compile (internal/modules/cjs/loader.js:1140:27)[39m
    [90m    at internal/bootstrap/pre_execution.js:118:36[39m
    [90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)[39m
    [90m    at internal/main/repl.js:18:1[39m

1. Downloaded nexe (via npm)
2. nexe main.js (in the project folder)
3. main.exe
4. **ERROR**

My script only uses these dependencies:
- `http`
- `fs`
- `child_process`

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version: v14.1.0
- Target Node Version: v14.1.0
- Nexe version: 3.3.2
- Python Version: Python 2.7.18

**Comment by Mrgove10** [comment]
+1

**Comment by vectronic** [comment]
I'm getting this as well:

* Platform(OS/Version): macOS Catalina
* Host Node Version: v12.11.1
* Target Node Version: v12.11.1
* Nexe version: 3.3.2 (and @next)

I am using {{--experimental-modules}} and a bunch of node modules.

**Comment by LoLei** [comment]
It happens even with a minimal example.
```
$ cat index.js
console.log('hello world', process.version)

$ nexe --python python --build index.js
ℹ nexe 4.0.0-beta.6
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: nexe-test
✔ Finished in 0.229s

$ file python
python: symbolic link to /usr/bin/python2

$ ./nexe-test
internal/modules/cjs/loader.js:1140
  callbackMap.set(compiled.cacheKey, {
              ^

TypeError: Cannot read property 'set' of undefined
    at wrapSafe (internal/modules/cjs/loader.js:1140:15)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at internal/bootstrap/pre_execution.js:118:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)
    at internal/main/repl.js:18:1
```

**Comment by lkrazy** [comment]
@LoLei 
downgrade to node v12.16.3 solved this issue

**Comment by EricMCornelius** [comment]
Looks like it originates from this PR to me: https://github.com/nodejs/node/commit/80c0b89bbbed26eca955f4f70922fa288b664c68

I don't understand the structure of how nexe is initialized quite well enough to understand why the cjs loader is getting invoked during the boot-nexe.js patch content.

The lib/internal/bootstrap/pre_execution.js initialization of the callbackMap now happens here: https://github.com/nodejs/node/blob/master/lib/internal/bootstrap/pre_execution.js#L401

Which is after the boot-nexe.js content that gets inserted here: https://github.com/nodejs/node/blob/master/lib/internal/bootstrap/pre_execution.js#L50

**Comment by calebboyd** [comment]
@EricMCornelius Thanks for tracking that down looks like it landed in 13. I'll see if I can get it resolved.

**Comment by EricMCornelius** [comment]
@calebboyd - looks like that's not the only thing which is non-functional to me - just patched it to insert `internalBinding("module_wrap").callbackMap = new SafeWeakMap();` before `initializePolicy()` and to replace the existing initialization with the same, and now the my build boots to the node command line.

But at least it's a bit of a start.

Is there a quicker way to rebuild nexe when all you're doing is tweaking the embedded javascript resources? A full rebuild seems excessive each time, but I'm unclear on what the procedure is to just patch the js files and rebundle the modified node binary.

**Comment by calebboyd** [comment]
Not if you need patches (as far as I know). If you just delete the resource (node binary) and use `-j<CORES>` in `make` its usually pretty quick

**Comment by EricMCornelius** [comment]
Ah gotcha - I'd been using `clean: true` in the nexe wrapper around make, and that's been triggering a full rebuild, instead of just codegen and a relink.

Much faster to tinker now.

**Comment by calebboyd** [comment]
Ahh Sorry, yeah, that option is aggressive.

**Comment by EricMCornelius** [comment]
This is new as well: https://github.com/nodejs/node/blob/master/lib/internal/modules/run_main.js

And the CLI starting appears to be because `first_arg` here is an empty string now when running the nexe build: `https://github.com/nodejs/node/blob/master/src/node.cc#L476`

I'm guessing this is something to do with the restructuring, as when I run the nexe built binary (which launches the CLI due to the second boolean check here https://github.com/nodejs/node/blob/master/src/node.cc#L506):

`process.argv` in the cli still has my entrypoint script as the second argument.

So my guess now is they've tweaked something about how the node.js "env->argv" works, and it is no longer being read in the node.js startup, after being manually set in the pre_execution.js patch?

**Comment by EricMCornelius** [comment]
After manually setting `std::string first_arg = "entrypoint.js";` here: https://github.com/nodejs/node/blob/master/src/node.cc#L475

The nexe build works as expected.

So, I'm not sure exactly where to go from here, but hopefully at least it'll narrow down how to modify the Environment object before the main switch block is invoked.

**Comment by Barkole** [comment]
Same problem with
* Windows 10
* Node: v12.18.0
* nexe: 3.3.2

```txt
internal/modules/cjs/loader.js:1078
  callbackMap.set(compiled.cacheKey, {
              ^

TypeError: Cannot read property 'set' of undefined
    at wrapSafe (internal/modules/cjs/loader.js:1078:15)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at internal/bootstrap/pre_execution.js:118:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)
    at internal/main/run_main_module.js:7:1
```

**Comment by Krzysztof-Dziardziel** [comment]
Any workaround on that? When I try: nexe -t windows-x64-12.16.3 or nexe -b windows-x64-12.16.3, I'm getting the error:
```
i nexe 3.3.2
√ Already downloaded...
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 2.089s

Error: vcbuild.bat nosign release x64 exited with code: 1
```
