### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by Yuuki-Sakura** [nexe/nexe#779]
**What happened**:
Error with compiling

```
i nexe 3.3.2
√ Node source extracted to: C:\Users\admin\.nexe\12.18.0
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 747.334s
NexeError: vcbuild.bat nosign release x64 exited with code: 1
    at new NexeError (E:\Project\Node\excel2txt\node_modules\_nexe@3.3.2@nexe\lib\compiler.js:83:28)
    at ChildProcess.<anonymous> (E:\Project\Node\excel2txt\node_modules\_nexe@3.3.2@nexe\lib\compiler.js:274:28)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```
```
PS C:\Users\admin\.nexe\12.18.0> .\vcbuild release nosign
Note: vcbuild no longer signs by default. "nosign" is redundant.
Looking for Python
Python 2 found in E:\IDE\Python\Python27\\python.exe
Looking for NASM
Looking for Visual Studio 2017
calling: "E:\IDE\Visual Studio 2017\VC\\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.24
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Found MSVS version 15.0
configure  --with-ltcg --dest-cpu=x64
Warning: Missing input files:
tools\v8_gypfiles\..\..\deps\v8\src\regexp\regexp-special-case.h
[1m[32mINFO[0m: configure completed successfully
Project files generated.
  uvwasi.vcxproj -> ..\..\out\Release\lib\uvwasi.lib
  v8_libplatform.vcxproj -> ..\..\out\Release\lib\v8_libplatform.lib
  zlib.vcxproj -> ..\..\out\Release\lib\zlib.lib
  http_parser.vcxproj -> ..\..\out\Release\lib\http_parser.lib
  llhttp.vcxproj -> ..\..\out\Release\lib\llhttp.lib
  cares.vcxproj -> ..\..\out\Release\lib\cares.lib
  libuv.vcxproj -> ..\..\out\Release\lib\libuv.lib
  histogram.vcxproj -> ..\..\out\Release\lib\histogram.lib
  nghttp2.vcxproj -> ..\..\out\Release\lib\nghttp2.lib
  brotli.vcxproj -> ..\..\out\Release\lib\brotli.lib
  openssl.vcxproj -> ..\..\out\Release\lib\openssl.lib
  icutools.vcxproj -> ..\..\out\Release\lib\icutools.lib
  icustubdata.vcxproj -> ..\..\out\Release\lib\icustubdata.lib
  openssl-cli.vcxproj -> ..\..\out\Release\\openssl-cli.exe
  icui18n.vcxproj -> ..\..\out\Release\lib\icui18n.lib
  icuucx.vcxproj -> ..\..\out\Release\lib\icuucx.lib
  v8_libsampler.vcxproj -> ..\..\out\Release\lib\v8_libsampler.lib
  icupkg.vcxproj -> ..\..\out\Release\\icupkg.exe
  genrb.vcxproj -> ..\..\out\Release\\genrb.exe
  genccode.vcxproj -> ..\..\out\Release\\genccode.exe
  torque_base.vcxproj -> ..\..\out\Release\lib\torque_base.lib
  iculslocs.vcxproj -> ..\..\out\Release\\iculslocs.exe
  v8_libbase.vcxproj -> ..\..\out\Release\lib\v8_libbase.lib
  bytecode_builtins_list_generator.vcxproj -> ..\..\out\Release\\bytecode_builtins_list_generator.exe
  torque.vcxproj -> ..\..\out\Release\\torque.exe
  icudata.vcxproj -> ..\..\out\Release\lib\icudata.lib
  v8_compiler.vcxproj -> ..\..\out\Release\lib\v8_compiler.lib
  v8_nosnapshot.vcxproj -> ..\..\out\Release\lib\v8_nosnapshot.lib
  v8_init.vcxproj -> ..\..\out\Release\lib\v8_init.lib
  gen-regexp-special-case.vcxproj -> ..\..\out\Release\\gen-regexp-special-case.exe
  v8_initializers.vcxproj -> ..\..\out\Release\lib\v8_initializers.lib
  v8_base_without_compiler.vcxproj -> ..\..\out\Release\lib\v8_base_without_compiler.lib
  mksnapshot.vcxproj -> ..\..\out\Release\\mksnapshot.exe
  v8_snapshot.vcxproj -> ..\..\out\Release\lib\v8_snapshot.lib
  node_js2c
  node.cc
  node_javascript.cc
c:\users\admin\.nexe\12.18.0\src\node.cc(770): error C2059: 语法错误:“)” [C:\Users\admin\.nexe\12.18.0\libnode.vcxproj]
c:\users\admin\.nexe\12.18.0\src\node.cc(778): error C2059: 语法错误:“)” [C:\Users\admin\.nexe\12.18.0\libnode.vcxproj]
c:\users\admin\.nexe\12.18.0\src\node.cc(945): warning C4244: “参数”: 从“int64_t”转换到“int”，可能丢失数据 [C:\Users\admin\.nexe\12.18.0\libnode
.vcxproj]
PS C:\Users\admin\.nexe\12.18.0>
```
**Environment**:
- Platform(OS/Version): Windows 10 2004 19041.329
- Host Node Version: v12.18.0
- Target Node Version: v12.18.0
- Nexe version: 3.3.2
- Python Version: 2.7&3.8

**Comment by s-a** [comment]
Pretty weird, but I work around with 
- install NASM (Netwide Assembler) as administrator
- use node 12.18.1 as target

**Comment by calebboyd** [comment]
Take a look at https://github.com/nodejs/node/blob/master/BUILDING.md

Nexe (when building) is just a passthrough for executing the documented build steps on a nexe modified source
