### ISSUE TITLE
3.3.6 fails on alpine/musl

### ISSUE THREAD

**Issue by hermanbanken** [nexe/nexe#789]
**What happened**:
Crash while resolving dependencies.

**What you expected to happen**:
Work like before.

**How to reproduce it (as minimally and precisely as possible)**:
Update from nexe 3.3.3 to 3.3.6.

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): docker/alpine
- Host Node Version: docker `node:12-alpine`
- Target Node Version: x86 linux 12.16.2
- Nexe version: 3.3.6
- Python Version: default of docker `node:12-alpine`

```
$ nexe dist/bundle.js -t linux-x64-12.16.2 -o build/hue-cli-linux-x64
 - Starting...
 ℹ nexe 3.3.6
 ✔ nexe 3.3.6
 - Finished in 1.43s
 ✔ Finished in 1.43s
 Error: Error: Path /lib/ld-musl-x86_64.so.1 is not in cwd /workspace/node_modules/csv-stringify
     at ensureAbsolutePathForCwd (/workspace/node_modules/resolve-dependencies/node_modules/globby/gitignore.js:53:9)
     at /workspace/node_modules/resolve-dependencies/node_modules/globby/gitignore.js:60:55
     at /workspace/node_modules/resolve-dependencies/node_modules/globby/index.js:135:47
     at Array.filter (<anonymous>)
     at Object.module.exports [as default] (/workspace/node_modules/resolve-dependencies/node_modules/globby/index.js:135:30)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async expand (/workspace/node_modules/resolve-dependencies/lib/node-loader.js:67:19)
     at async Object.load (/workspace/node_modules/resolve-dependencies/lib/node-loader.js:114:13)
     at async process.<anonymous> (/workspace/node_modules/resolve-dependencies/lib/worker-runtime.js:29:22)
     at ChildProcess.<anonymous> (/workspace/node_modules/resolve-dependencies/lib/worker.js:16:31)
     at ChildProcess.emit (events.js:315:20)
     at emit (internal/child_process.js:876:12)
     at processTicksAndRejections (internal/process/task_queues.js:85:21)
 events.js:292
       throw er; // Unhandled 'error' event
       ^
 Error: write EPIPE
     at process.target._send (internal/child_process.js:806:20)
     at process.target.send (internal/child_process.js:677:19)
     at process.<anonymous> (/workspace/node_modules/resolve-dependencies/lib/worker-runtime.js:34:9)
 Emitted 'error' event on process instance at:
     at internal/child_process.js:810:39
     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
   errno: 'EPIPE',
   code: 'EPIPE',
   syscall: 'write'
 }
 events.js:292
       throw er; // Unhandled 'error' event
       ^
 Error: write EPIPE
     at process.target._send (internal/child_process.js:806:20)
     at process.target.send (internal/child_process.js:677:19)
     at process.<anonymous> (/workspace/node_modules/resolve-dependencies/lib/worker-runtime.js:34:9)
 Emitted 'error' event on process instance at:
     at internal/child_process.js:810:39
     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
   errno: 'EPIPE',
   code: 'EPIPE',
   syscall: 'write'
 }
 events.js:292
       throw er; // Unhandled 'error' event
       ^
 Error: write EPIPE
     at process.target._send (internal/child_process.js:806:20)
     at process.target.send (internal/child_process.js:677:19)
     at process.<anonymous> (/workspace/node_modules/resolve-dependencies/lib/worker-runtime.js:34:9)
 Emitted 'error' event on process instance at:
     at internal/child_process.js:810:39
     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
   errno: 'EPIPE',
   code: 'EPIPE',
   syscall: 'write'
 }
 events.js:292
       throw er; // Unhandled 'error' event
       ^
[...]
```

**Comment by calebboyd** [comment]
fixed on 3.3.7. via https://github.com/nexe/resolve-dependencies/commit/27f3783bf84de2e586206e4adad153a91f6c6b6f
