### ISSUE TITLE
Any one now about this error help me out....

### ISSUE THREAD

**Issue by Chetna12312** [nexe/nexe#802]
Package.json file
{
  "name": "myproject",
  "version": "1.0.0",
  "description": "\"This is my first Sample  project\"",
  "main": "Server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "Main",
    "WEb"
  ],
  "author": "Chetna",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "mongoose": "^5.9.28"
  }
}

Error:-
(node:14696) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Server is listening on port 800
Successfuly connected to the database
SyntaxError: Unexpected string in JSON at position 25
    at JSON.parse (<anonymous>)
    at parse (E:\nodejs\myproject\node_modules\body-parser\lib\types\json.js:89:19)
    at E:\nodejs\myproject\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (E:\nodejs\myproject\node_modules\raw-body\index.js:224:16)
    at done (E:\nodejs\myproject\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (E:\nodejs\myproject\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by calebboyd** [comment]
Do you have a reproduction? what Does the app do?

**Comment by AndyClausen** [comment]
So.. Does this work without nexe? How did you build the package? How did you run it? The error doesn't tell us anything 😕
