### ISSUE TITLE
Error executing nexe executable with pm2

### ISSUE THREAD

**Issue by ilclaudio** [nexe/nexe#806]
Hi,
I've used Nexe to get an executable from a Node.js program.
If I execute the program in this way:
`  ./ServicesMonitor > ServicesMonitor.log &`
it works well.

But If I use pm2 to start the executable it fails with this error:

`TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:462:15)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:629:20)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at Object.<anonymous> (/home/geostech/GeostechServices/ServicesMonitor:352:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at _third_party_main.js:38:36
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at process.nextTick (internal/bootstrap/node.js:249:22)
internal/modules/cjs/loader.js:462
  if (request.length < 2 ||
              ^
`

I'm starting the Node.js program in this way:
`pm2 start ./ServicesMonitor `

Is this a known error?

Thank you very much

cld

**Comment by Louis-Tian** [comment]
I am having the same issue. Even with executable compiled from an empty js file. 
```
0|test     | internal/validators.js:124
0|test     |     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
0|test     |     ^
0|test     | 
0|test     | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
0|test     |     at validateString (internal/validators.js:124:11)
0|test     |     at Object.resolve (path.js:139:9)
0|test     |     at resolveMainPath (internal/modules/run_main.js:12:40)
0|test     |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
0|test     |     at internal/main/run_main_module.js:17:47 {
0|test     |   code: 'ERR_INVALID_ARG_TYPE'
0|test     | }
```

**Comment by JeffJassky** [comment]
Having the same issue here.

**Comment by paranic** [comment]
```internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
     ^
 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at resolveMainPath (internal/modules/run_main.js:12:40)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
 }```

same issue here when i try to run throu pm2 start
