### ISSUE TITLE
trying to load a .node module

### ISSUE THREAD

**Issue by celevra** [nexe/nexe#811]
Hi,

i'm trying to load a .node module, i have put it in the same path and in the given path from the error message:

```
C:\Users\xxx\Desktop>zAgent.exe
internal/modules/cjs/loader.js:1188
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\xxx\Desktop\node_modules\iohook\builds\node-v72-win32-x64\build\Release\iohook.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\xxx\Desktop\node_modules\iohook\index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

C:\Users\xxx\Desktop>
```

what am i doing wrong?

regards

celevra

**Comment by Ayzrian** [comment]
Hi, @celevra !
First of all, you need to add your files to resources during the build. You can use either a flag or a `resources` parameter of `compile` funciton. 
Then you need to put the files relative to the .exe you built. For instance, `-r  /res/**/*/` will enable your app to access the res folder that resides near your `.exe` file.

**Comment by calebboyd** [comment]
See #639
