### ISSUE TITLE
Handling dependencies for exports maps?

### ISSUE THREAD

**Issue by aral** [nexe/nexe#834]
**What would you like to be added**:

Support for including dependencies when an exports map is used.

**Why is this needed**:

I just added a library to my app that uses an exports map to specify ESM and CommonJS versions of the library:

```json
  "exports": {
    ".": [
      {
        "import": "./index.mjs",
        "require": "./build/index.cjs"
      },
      "./build/index.cjs"
    ]
  },
```

When I compile the app using Nexe, I get the following error when I run it:

```
Error: Cannot find module 'string-width'
Require stack:
- /usr/local/bin/node_modules/cliui/build/index.cjs
…
```

The required modules are included at the end of the `index.cjs` file:

```js
…
// Bootstrap cliui with CommonJS dependencies:
const stringWidth = require('string-width');
const stripAnsi = require('strip-ansi');
const wrap = require('wrap-ansi');
…
```

**Comment by calebboyd** [comment]
Shoot. Yeah Surprisingly there are not a lot of packages that publish filenames other than js...

The mjs was an experimental current node version...I wish tagging the module format in in the extension had not caught on 😩

**Comment by aral** [comment]
@calebboyd The whole CommonJS → ESM debacle almost makes IPv4 → IPv6 seem tame in comparison :)

**Comment by calebboyd** [comment]
Should be working now if you're on a version using 6.x of resolve-dependencies
https://github.com/nexe/resolve-dependencies/blob/085bf86e9ab844a9b5b980668f4e8afae33cf273/src/resolve.spec.ts#L84

**Comment by aral** [comment]
You’re a star, Caleb, thank you so much. Will test (I think I’m still on my fork due to some issue or other. Will also look into that and make sure I have issues filed/chase up.) Hope you’re well and having a lovely weekend.

**Comment by ralphskie** [comment]
Im thinking my issue is also related to this, im using [objection.js](https://github.com/Vincit/objection.js) which has a dependency on [knex.js](https://github.com/knex/knex)

here is a stacktrace 
```
Error: Cannot find module './dialects/mysql/index.js'
Require stack:
- D:\my_project_path\dist\node_modules\knex\lib\knex.js
- D:\my_project_path\dist\node_modules\knex\lib\index.js
- D:\my_project_path\dist\node_modules\knex\knex.js
- D:\my_project_path\dist\configs\knex.js
- D:\my_project_path\dist\models\batching_plants.js
- D:\my_project_path\dist\controller.js
- D:\my_project_path\dist\routes.js
- D:\my_project_path\dist\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Knex (D:\my_project_path\dist\node_modules\knex\lib\knex.js:44:15)
    at Object.<anonymous> (D:\my_project_path\dist\configs\knex.js:4:33)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```
#### Workaround
currently im including **"node_modules/knex"** folder with the .exe file generated by nexe.

#### Tested on nexe version
 3.3.7 and 4.0.0-beta.15

**Comment by calebboyd** [comment]
@ralphskie Can you try reinstalling nexe (beta)? Some transient dependencies affecting package resolution were updated.

**Comment by ralphskie** [comment]
Hi, Ive tried it on different nexe versions and window platform but **still the same problem** when running after compile.
below are the details:

Compile using win7 using versions:
@latest
@beta (4.0.0-beta.15)
@3.3.3
@3.3.2

Compile using win10 using versions:
@latest
@beta (4.0.0-beta.15)

This is how I issue the command
nexe server.js -o dist/myApp.exe -t windows-x64-12.0.0 --verbose

**Comment by DataTables** [comment]
I've just hit this with Knex as well (in my case using the `pg` drive). Presumably the issue is that this is a dynamic import and Nexe can't resolve that, since it could be literally anything at runtime.

I think I've resolved it locally (although running into a different include issue now) by just putting a require into my code for the files that I knex will dynamically require:

```
const knexPg = require('knex/lib/dialects/postgres');
```

Nexe then adds them to the bundle, and since it doesn't do dead code elimination it the files are present when Knex wants them.

Hope this helps someone else who hits this issue.
