### ISSUE TITLE
Unable to build binary with Node v8.4.0

### ISSUE THREAD

**Issue by fumblehool** [nexe/nexe#837]
**What happened**:
* I installed nexe@3.3.7 using node v8.4.0
* nexe requires node version >=8
* When I try to build a binary, I'm getting a TypeError:
```ubuntu@testServer:~/code(master)$ ./node_modules/.bin/nexe -t x64-8.4.0 Server/serverStart.js
/home/ubuntu/code/intangles/Backend/node_modules/resolve-dependencies/lib/node-loader.js:13
const readFile = fs_1.promises.readFile;
                              ^

TypeError: Cannot read property 'readFile' of undefined
    at Object.<anonymous> (/home/ubuntu/code/intangles/Backend/node_modules/resolve-dependencies/lib/node-loader.js:13:31)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/code/intangles/Backend/node_modules/resolve-dependencies/lib/resolve.js:6:23)
```

**What you expected to happen**:
* It should write Binary to `serverStart.js`

**How to reproduce it (as minimally and precisely as possible)**:
* Create a sample node server using node v8.4.0.
* Install nexe v3.3.7 (`npm i nexe@3.3.7`)
* Run command: `./node_modules/.bin/nexe -t x64-8.4.0 server.js`, the build breaks.
* If node version is changed to `10.22.0` it builds successfully.

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Ubuntu 18.04.5 LTS
- Host Node Version: 8.4.0
- Target Node Version: 8.4.0
- Nexe version: 3.3.7 (tried 3.3.6, 3.0.0 but got same error)
- Python Version: 2

**Comment by calebboyd** [comment]
Closing as Node 8 is EOL
