### ISSUE TITLE
\x00 in filepath breaks build

### ISSUE THREAD

**Issue by OmgImAlexis** [nexe/nexe#865]
**What happened**:
```
root@Devon:/usr/local/bin/node/unraid-api# ./node_modules/.bin/nexe ./dist/index.js 
ℹ nexe 4.0.0-beta.17
✔ nexe 4.0.0-beta.17
✔ Finished in 7.989s
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/usr/local/bin/node/unraid-api/node_modules/es5-ext/string/\x00#/contains/index.js'
    at Object.openSync (fs.js:458:10)
    at readFileSync (fs.js:369:35)
    at Object.load (/usr/local/bin/node/unraid-api/node_modules/resolve-dependencies/lib/node-loader.js:111:25)
    at Loader.load (/usr/local/bin/node/unraid-api/node_modules/resolve-dependencies/lib/loader.js:45:29)
    at /usr/local/bin/node/unraid-api/node_modules/resolve-dependencies/lib/loader.js:79:48
    at Array.map (<anonymous>)
    at Loader.load (/usr/local/bin/node/unraid-api/node_modules/resolve-dependencies/lib/loader.js:78:14)
    at /usr/local/bin/node/unraid-api/node_modules/resolve-dependencies/lib/loader.js:79:48
    at Array.map (<anonymous>)
    at Loader.load (/usr/local/bin/node/unraid-api/node_modules/resolve-dependencies/lib/loader.js:78:14)
```

**What you expected to happen**:
Build to complete.

**How to reproduce it (as minimally and precisely as possible)**:
Honestly not sure what's causing this at the moment, I'll try and work on a repro though.

**Anything else we need to know?**:
Changing these lines fixed the issue.
https://github.com/nexe/resolve-dependencies/blob/4cb15f6307fd067af722a71068753328febc5f41/src/node-loader.ts#L113-L116

```ts
  file.absPath = absPath.replace('\x00', '');

  if (isJs || absPath.endsWith('json')) {
    file.contents = readFileSync(file.absPath, 'utf-8')
```

**Environment**:
- Platform(OS/Version): Unraid 6.9.0-rc2c
- Host Node Version: v14.13.0
- Target Node Version: v14.13.0
- Nexe version: 4.0.0-beta.17
- Python Version: Python 2.7.17

**Comment by wilmardo** [comment]
Related:
https://github.com/nexe/resolve-dependencies/issues/10

**Comment by wilmardo** [comment]
Just tested with a project where I had this problem previous, and 100% fixed with beta18
