### ISSUE TITLE
Missing download version v3.3.3/windows-x64-14.16.0

### ISSUE THREAD

**Issue by lindsaythurmond** [nexe/nexe#867]
**What happened**:
Sometime in the last couple of hours, builds without any code changes are failing to download https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-14.16.0

```
i nexe 3.3.7
- nexe 3.3.7
âˆš Downloading pre-built Node.js
- Finished in 3.406s
âˆš Finished in 3.406s
[WARN] Executable build error:  NexeError: https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-14.16.0 is not available, create it using the --build flag
    at new NexeError (c:\jbld\workspace\ild_mobent-cli-admin-win_develop\node_modules\nexe\lib\compiler.js:83:28)
    at c:\jbld\workspace\ild_mobent-cli-admin-win_develop\node_modules\nexe\lib\steps\download.js:83:31
    at step (c:\jbld\workspace\ild_mobent-cli-admin-win_develop\node_modules\nexe\lib\steps\download.js:32:23)
    at Object.throw (c:\jbld\workspace\ild_mobent-cli-admin-win_develop\node_modules\nexe\lib\steps\download.js:13:53)
    at rejected (c:\jbld\workspace\ild_mobent-cli-admin-win_develop\node_modules\nexe\lib\steps\download.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**What you expected to happen**:
Can the missing dependency be added back?

**How to reproduce it (as minimally and precisely as possible)**:
My package.json file is importing version "nexe": "^3.3.7"

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version):  Windows Server 2016
- Host Node Version: 14.16.0
- Target Node Version:
- Nexe version: 3.3.7
- Python Version: 3.8

**Comment by lindsaythurmond** [comment]
Although it would be nice to have the newer version, what actually happened is one of my teammates updated the node version on the build server without telling anyone, so it's not that existing binaries were deleted, it's that they were never created.  Closing accordingly.
