### ISSUE TITLE
fs.readdirSync is not working properly when compiled

### ISSUE THREAD

**Issue by OmgImAlexis** [nexe/nexe#872]
**What happened**:
```
v14.15.0
[ 'x.js' ]
```

**What you expected to happen**:
```
v14.15.0
[
  Dirent { name: 'x.js', [Symbol(type)]: 1 }
]
```

**How to reproduce it (as minimally and precisely as possible)**:
```
console.log(process.version);
console.log(
    require('fs').readdirSync('.', { withFileTypes: true })
);
```

**Anything else we need to know?**:
Same issue as https://github.com/vercel/pkg/issues/813

**Environment**:
- Platform(OS/Version): macOS
- Host Node Version: v14.15.0
- Target Node Version: v14.15.0
- Nexe version: 4.0.0-beta.18
- Python Version: 2.7.16

**Comment by OmgImAlexis** [comment]
```
/usr/local/bin/node/_/node_modules/@nodelib/fs.walk/out/readers/sync.js:41
        throw error;
        ^

TypeError: entry.dirent.isSymbolicLink is not a function
    at /usr/local/bin/node/_/node_modules/@nodelib/fs.scandir/out/providers/sync.js:23:26
    at Array.map (<anonymous>)
    at readdirWithFileTypes (/usr/local/bin/node/_/node_modules/@nodelib/fs.scandir/out/providers/sync.js:17:20)
    at Object.read (/usr/local/bin/node/_/node_modules/@nodelib/fs.scandir/out/providers/sync.js:10:16)
    at SyncReader.scandirSync [as _scandir] (/usr/local/bin/node/_/node_modules/@nodelib/fs.scandir/out/index.js:17:17)
    at SyncReader._handleDirectory (/usr/local/bin/node/_/node_modules/@nodelib/fs.walk/out/readers/sync.js:28:34)
    at SyncReader._handleQueue (/usr/local/bin/node/_/node_modules/@nodelib/fs.walk/out/readers/sync.js:23:18)
    at SyncReader.read (/usr/local/bin/node/_/node_modules/@nodelib/fs.walk/out/readers/sync.js:15:14)
    at SyncProvider.read (/usr/local/bin/node/_/node_modules/@nodelib/fs.walk/out/providers/sync.js:11:29)
    at ReaderSync.walkSync [as _walkSync] (/usr/local/bin/node/_/node_modules/@nodelib/fs.walk/out/index.js:19:21)
    ```

**Comment by OmgImAlexis** [comment]
Duplicate of https://github.com/nexe/nexe/issues/711
