### ISSUE TITLE
Node 14.x not works

### ISSUE THREAD

**Issue by liudonghua123** [nexe/nexe#875]
**What happened**: I tried to package a simple demo, if targeted to 14.x, then it did not work as expected.

**What you expected to happen**: work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
D:\code\deno>cat index.js
console.info('hello');

D:\code\deno>nexe --verbose -t 12.9.1 index.js -o index-nexe-12.9.1.exe
i nexe 4.0.0-beta.18
√ Downloading pre-built Node.js
√ Already downloaded...
√ Compiling result
√ Writing result to file
√ Entry: 'index.js' written to: index-nexe-12.9.1.exe
√ Finished in 0.544s

D:\code\deno>nexe --verbose -t 14.0.0 index.js -o index-nexe-14.0.0.exe
i nexe 4.0.0-beta.18
√ Downloading pre-built Node.js
√ Already downloaded...
√ Compiling result
√ Writing result to file
√ Entry: 'index.js' written to: index-nexe-14.0.0.exe
√ Finished in 0.634s

D:\code\deno>nexe --verbose -t 14.5.0 index.js -o index-nexe-14.5.0.exe
i nexe 4.0.0-beta.18
√ Downloading pre-built Node.js
√ Already downloaded...
√ Compiling result
√ Writing result to file
√ Entry: 'index.js' written to: index-nexe-14.5.0.exe
√ Finished in 0.419s

D:\code\deno>index-nexe-12.9.1.exe
hello

D:\code\deno>index-nexe-14.0.0.exe
internal/modules/cjs/loader.js:1125
  callbackMap.set(compiled.cacheKey, {
              ^

TypeError: Cannot read property 'set' of undefined
    at wrapSafe (internal/modules/cjs/loader.js:1125:15)
    at Module._compile (internal/modules/cjs/loader.js:1149:27)
    at internal/bootstrap/pre_execution.js:118:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)
    at internal/main/repl.js:18:1

D:\code\deno>index-nexe-14.5.0.exe
Welcome to Node.js v14.5.0.
Type ".help" for more information.
>
(To exit, press ^C again or ^D or type .exit)
>

D:\code\deno>
```

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Microsoft Windows [Version 10.0.19042.844]
- Host Node Version: 15.2.0
- Target Node Version: 14.x
- Nexe version: 4.0.0-beta.18
- Python Version: Python 3.8.6/2.7.15

**Comment by pguardiario** [comment]
I get the same thing. I'm looking for the latest good one.

**Comment by tsibg** [comment]
Any update on this?
Still reproducible with version: `4.0.0-beta.19`
For me it is crucial as versions 14.x are the latest listed in the releases note. Also version 13.x is missing from your list, therefore I cannot target any version with ES6 support, without the `--build` flag.

**Comment by ofarukcaki** [comment]
I have the same problem in 2022

**Comment by chenamy2017** [comment]
> D:\code\deno>index-nexe-14.5.0.exe
> Welcome to Node.js v14.5.0.
> Type ".help" for more information.
> >
> (To exit, press ^C again or ^D or type .exit)
> >
I have the same problem in 2023.
Environment:
Platform(OS/Version): Redhat 6.4 
How to reproduce it：
1. Download the nodejs v12 source code && build it
2. nexe -i test.js -o test-t linux-x64-12.0.0 --build
3.  ./test
Welcome to Node.js v12.0.0.
Type ".help" for more information.
> 
(To exit, press ^C again or ^D or type .exit)
>

**Comment by liudonghua123** [comment]
It's almost 2024, now I use node v20 lts already. :crying_cat_face:
