### ISSUE TITLE
bhttp/errors modules: no such file or directory, open '/node_modules/errors/lib/static/error.css'

### ISSUE THREAD

**Issue by Bacto** [nexe/nexe#890]
Hi,

First, thanks for Nexe, it is a very useful tool :)

I have an issue when I import the module "bhttp" (https://www.npmjs.com/package/bhttp, cc @joepie91).
I don't know if it is a bug on Nexe, bhttp or errors (https://www.npmjs.com/package/errors, cc @bodenr).

When I import bhttp, it seems that the module somewhere tries to load the file "node_modules/errors/lib/static/error.css" (and error.html) on the local file system directly and not in the binary generated by Nexe.

The error is this one:
```
/test # ./test
fs.js:127
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/test/node_modules/errors/lib/static/error.css'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:350:35)
    at Object.readFileSync (/test/test:239:55)
    at Object.<anonymous> (/test/node_modules/errors/lib/errors.js:767:15)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/test/node_modules/errors/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/test/node_modules/errors/lib/static/error.css'
}
```

Here is a way to reproduce the bug:
```
docker run -it alpine:3.13.5

apk --no-cache add nodejs nodejs-npm yarn
yarn global add nexe

mkdir test
cd test

echo "{}" > package.json
yarn add bhttp
echo "const bhttp = require('bhttp');" > test.js
nexe -t alpine-x64-12.9.1 -i test.js -o test
# Works because the binary "test" can load the files /test/node_modules/errors/lib/static/error.css and error.html
./test

# If we remove the node_module directory, it doesn't work anymore
# Error: ENOENT: no such file or directory, open '/test/node_modules/errors/lib/static/error.css'
rm -fr node_modules
./test
```

If I manually add these 2 files to the required resources, it works then:
`nexe -t alpine-x64-12.9.1 --resource=./node_modules/errors/lib/static/error.css --resource=./node_modules/errors/lib/static/error.html -i test.js -o test`

Shouldn't Nexe detect automatically and add these files to the binary?

Best,
Adrien

**Comment by joepie91** [comment]
The problem is caused by `errors`, though I'd say it probably qualifies as a nexe bug. The issue in the following code ([source](https://github.com/bodenr/errors/blob/master/lib/errors.js#L814-L815)):

```js
errorCss = fs.readFileSync(__dirname + '/static/error.css', 'utf8');
errorHtml = fs.readFileSync(__dirname + '/static/error.html', 'utf8');
```

This uses a runtime filesystem operation to load some files relative to the `errors` module's path; tools like [brfs](https://www.npmjs.com/package/brfs) detect and handle the simple cases like this properly, but apparently nexe doesn't.

There's nothing I can do about this on the bhttp side, unfortunately, aside from switching to a different error library that doesn't load any local files. That *is* on the to-do list, but I haven't gotten around to it yet - and it wouldn't solve the broader problem of "nexe doesn't package files with a `__dirname`-relative path" anyway.

**Comment by Bacto** [comment]
I know this bug is special and not really anybody's "fault". Just a set of circumstances that trigger this issue.

Many thanks for your reply @joepie91 :)
