### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by zhex900** [nexe/nexe#905]
Hi,

My node app uses `aws-crt`. `nexe` builds fine, `exe` is produced. 

When I run it I get this error:

````
PS C:\Code\mir-kiosk-electron\windowsSockets> nexe --verbose --build .\dist\windowsSockets\src\index.js
i nexe 4.0.0-beta.18
√ Downloading Node.jssource from: https://nodejs.org/dist/v14.17.0/node-v14.17.0.tar.gz
√ Already downloaded...
√ Compiling result
√ Writing result to file
√ Entry: 'dist\windowsSockets\src\index.js' written to: windowsSockets.exe
√ Finished in 0.656s
PS C:\Code\mir-kiosk-electron\windowsSockets> .\windowsSockets.exe
internal/modules/cjs/loader.js:1127
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Code\mir-kiosk-electron\windowsSockets\node_modules\aws-crt\dist\bin\native\aws-crt-nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Code\mir-kiosk-electron\windowsSockets\node_modules\aws-crt\dist\native\binding.js:55:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
`````

````
//node_modules\aws-crt\dist\native\binding.js:55
for (const path of search_paths) {
    if (path && fs_1.existsSync(path + '.node')) {
        binding = require(path); // line 55
        break;
    }
}
````
This path is correct 

```
PS C:\Code\mir-kiosk-electron\windowsSockets> ls .\node_modules\aws-crt\dist\bin\native\


    Directory: C:\Code\mir-kiosk-electron\windowsSockets\node_modules\aws-crt\dist\bin\native


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        18/06/2021  12:36 PM         864768 aws-crt-nodejs.node
-a----        18/06/2021  12:36 PM         864768 aws-crt-nodejs.node.bak
````

**Comment by pipobscure** [comment]
There seem to be 2 issues here.

1) the *.node* binary isn’t included in the binary, so it won’t be found when searching for it; 
and 2) even if you included it with `-r` it couldn’t be loaded because `dlopen` requires it to be an actual file on disk.

A solution may be to include it in the binary with `-r` and then have code executed before anything is required/included that overwrites `process.dlopen` with something that gets that resource file and writes it to disk as a temp-file as well as changing the path to the path of the tempfile and then passing through to the original `dlopen`.
