### ISSUE TITLE
Cannot find module "..." when running .exe

### ISSUE THREAD

**Issue by zzmichalqq** [nexe/nexe#920]
**What happened**: I have a single-file application in Node.js. I build the project into .exe with nexe, but the resulted .exe is not working when executed from different location than it was built in.

**What you expected to happen**: I expect the app to run normally in any directory.

**How to reproduce it (as minimally and precisely as possible)**: Build the project -> move the .exe into another folder.

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Win 10
- Host Node Version: v14.15.3
- Target Node Version: v14.15.3
- Nexe version: 4.0.0-beta.18
- Python Version: -

The file I compile is called manual.js using `pkg .`, if I execute manual.exe in the same folder as manual.js, the application works fine. If I move manual.exe to ./dist/manual.exe and execute it there, I get this error:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\_code\register-cli\dist\manual.js' imported from D:\_code\register-cli\dist\
Did you mean to import D:/_code/register-cli/dist/manual.js?`

**Comment by tony-gutierrez** [comment]
node 14 support doesnt work yet. Search other issues.

**Comment by calebboyd** [comment]
@tony-gutierrez Node 14 should work fine it just doesn't have many prebuilt binaries.

@zzmichalqq You don't appear to be using nexe in your example. 

Do you have a valid reproduction? 

eg. If I do the following on Windows 10 Powershell I'm unable to reproduce your issue.

```
mkdir test
cd test 
npm init -y
npm i uuid -S
npm i nexe rimraf -D
echo "console.log(require('uuid').v4(), process.version)" > manual.js
echo "require('./manual.js')" > index.js
npx nexe index.js -t 14.15.3 -o my-app
npx rimraf node_modules
./my-app.exe
```
`ba5283b5-fa69-4a96-8da9-987366dc1f80 v14.15.3`

**Comment by coltmeister** [comment]
I am also encountering this issue when running `nexe --build` on my Windows 10 machine.

nodeversion: v14.18.0
nexe version: 4.0.0-beta.19

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@ethersproject/bignumber'
Require stack:
- C:\Users\colto\source\repos\mpunks-miner-controller\bin\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\colto\source\repos\mpunks-miner-controller\bin\index.js:15:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\colto\\source\\repos\\mpunks-miner-controller\\bin\\index.js'
  ]
}

```

**Comment by coltmeister** [comment]
Ah, I found the issue. The `bin/` directory within my git repository was checked into source control, and was originally populated on a unix machine. After wiping `bin/` on the Windows machine and running `npm install` and `npm build`, `nexe --build` produced a binary that runs successfully!
