### ISSUE TITLE
Error: python ./configure.py

### ISSUE THREAD

**Issue by yanickrochon** [nexe/nexe#926]
A simple source file :

```js
console.log("Hello world");
```
Trying this module, I get this :
```
$ npx nexe src/index.js --build --verbose
ℹ nexe 4.0.0-beta.19
✔ Downloading Node.jssource from: https://nodejs.org/dist/v16.4.2/node-v16.4.2.tar.gz
✔ Already downloaded...
✔ Compiling result
  Configuring node build: --dest-cpu=x64
Traceback (most recent call last):
  File "./configure.py", line 36, in <module>
    from gyp.common import GetFlavor
  File "tools/gyp/pylib/gyp/__init__.py", line 188
    return f"{opt}={value}"
                          ^
SyntaxError: invalid syntax
✔ Configuring node build: --dest-cpu=x64
✔ Finished in 0.073s

Error: python ./configure.py --dest-cpu=x64 exited with code: 1

See nexe -h for usage..
```
What version of python should it be running?

**Comment by bruce-one** [comment]
As of v16 (I think) Node requires Python3, rather than Python2

So, hopefully, `npx nexe src/index.js --build --verbose --python python3` should work (assuming you have Python3 installed)

(It did for me after replicating your former issue)

**Comment by fmoo** [comment]
Python 2 has been end-of-lifed since 2020-01-01. Is this worth tracking as a bug?

**Comment by calebboyd** [comment]
@fmoo I don't think there is an issue -- nexe uses `python` which varies in system and time. If you need to use a differently named executable you can set
`PYTHON=/my/correct/python nexe ....` or use the `--python` flag as @bruce-one pointed out.

**Comment by OptimBro** [comment]
> As of v16 (I think) Node requires Python3, rather than Python2
> 
> So, hopefully, `npx nexe src/index.js --build --verbose --python python3` should work (assuming you have Python3 installed)
> 
> (It did for me after replicating your former issue)

--python python3 fixed the issue for me on node 16
