### ISSUE TITLE
exe is runnable within project folder but got Cannot find module 'app-builder' when running outside

### ISSUE THREAD

**Issue by ALexander4295502** [nexe/nexe#956]
I include the compile function in my js file which wants to be compiled to exe:
```
...
   compile({
        input: "./main.temp.js",
        output: "./DataAnalyzer.exe",
        targets: ["win32-x86-10.13.0"]
    }).then(() => {
        console.log("DataAnalyzer.exe generated!");
        cleanUpAndExit();
    }).catch((e) => {
        console.log(e);
        exitHelper();
    })
...
```

And after compile it into exe and ran it in the current project folder, there is no error. But if I move it outside of the current project folder I got:
```
C:\Users\yuanz\Downloads\DataAnalyzerGenerator_v2.0.0>DataAnalyzerGenerator.exe
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'app-builder'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\yuanz\Downloads\DataAnalyzerGenerator_v2.0.0\node_modules\nexe\lib\nexe.js:13:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
``` 

I suspect it is due to the module `app-builder` is not bundled into the exe. Any steps I missed?

**Comment by please-rewrite** [comment]
look at `resources` in the documentation.

**Comment by calebboyd** [comment]
@ALexander4295502 Can you run your app outside the project folder with the `DEBUG=nexe:require` environment variable set?. Or even better if you can provide a small reproduction/example repo?

**Comment by ALexander4295502** [comment]
> look at `resources` in the documentation.

`app-builder` is not used in my app anywhere except `nexe#compile` which I think is rely on that. In that case, it doesn't make too much sense for me to include it as an additional resource for my app. Also I am not sure if it can be picked up correctly when running `nexe#compile`

**Comment by calebboyd** [comment]
Yeah, That's super odd! If you use the debug flag we may be able to track down why that's being included!

**Comment by ALexander4295502** [comment]
> @ALexander4295502 Can you run your app outside the project folder with the `DEBUG=nexe:require` environment variable set?. Or even better if you can provide a small reproduction/example repo?

Hi @calebboyd, sorry but I am not sure if you mean add this env var when I run my app in windows. here is what I got:
```
C:\Users\yuanz\Downloads\>DEBUG=nexe:require DataAnalyzerGenerator.exe
'DEBUG' is not recognized as an internal or external command,
operable program or batch file.
```

Here is the gist for `DataAnalyzerGenerator.js`: https://gist.github.com/ALexander4295502/4e0247250dc372417d9cb52f2988bb84

The only difference is everytime before I use nexe to make this js file into exe I will replace 
```js
const encodedJSFileContent = "BASE64";
```
with the actual js file content encoded in base64, but I don't think it can make any difference here.
