### ISSUE TITLE
Packaging into EXE completes, but fails to run when using package.json

### ISSUE THREAD

**Issue by chassy33** [nexe/nexe#962]
I have several programs that I wrote that all utilize nexe to package into standalone executables. the command that I am running is 
 ```nexe main.js -n Circuit_Generator_v0.0.3 -r "./git_secret.js" -r "./_Lib/**" -r "./node_modules/**"``` Recently, I ran it and it packaged fine, (or so I thought) but when I went and ran it it failed with the following error:

c:\MyPrograms\JavaScript\Circuit_Generator\run.exe:1
Y�H�Y�H�Y�H�X�H�X�H�X�H�X�H�X�I�X�I�W�B�I�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�=�>�?�B�L�c�R�q�S�q�T�r�U�s�U�s�W�s�Y�u�Y�u�[�u�\�v�]�w�^�w�_�x�`�y�a�y�a�x�b�x�b�w�b�w�c�w�c�v�c�v�d�u�d�t�d�t�c�t�b�r�b�r�b�r�b�q�a�p�a�p�`�o�`�n�`�n�_�m�_�m�^�k�^�k�]�j�]�i�]�i�\�h�\�h�[�g�[�f�Z�f�Z�e�X�c�W�a�V�_�T�]�S�\�Q�Y�P�X�O�V�M�T�L�R�J�P�I�N�G�L�F�K�E�I�D�G�B�E�A�C�?�A�>�@�>�@�G�K�J�O�J�N�I�N�H�M�H�M�H�M�H�L�H�M�H�L�J�OH�M

SyntaxError: Invalid or unexpected token
[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)[39m
[90m    at internal/bootstrap/pre_execution.js:133:36[39m
[90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:134:3)[39m
[90m    at internal/main/run_main_module.js:7:1[39m

After doing some digging, I renamed the "package.json" file to "package2.json" in order for nexe to ignore it and it packaged and ran exactly how it should, but for some reason when I change it back to package.json, it fails. I do not see anything that would cause this within the file.

```
{
  "name": "circuit_generator",
  "version": "0.0.1",
  "description": "This is a all in one tool for configuring and maintaining circuits in KFN. Currently this tool will do the following:",
  "main": "main",
  "dependencies": {
    "asn1": "^0.2.6",
    "compare-versions": "^3.6.0",
    "github-directory-downloader": "^1.3.6",
    "needle": "^2.8.0",
    "net-snmp": "^3.5.2",
    "pdf-parse": "^1.1.1",
    "ping": "^0.4.1",
    "readline-sync": "^1.4.10",
    "recursive-copy": "^2.0.14",
    "ssh2shell": "^1.9.4",
    "sz-iptools": "^1.9.0",
    "winattr": "^3.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
I am relatively new to this so not sure if this is a bug or issue with my code. Any help is appreciated!

Windows 10 1903
Node v14.15.3
NPM v6.14.9
nexe 4.0.0-beta.19

**Comment by calebboyd** [comment]
This is Interesting! I can't seem to replicate it though, with that package.json.

index.js
```javascript
require("asn1");
require("compare-versions");
require("github-directory-downloader");
require("needle");
require("net-snmp");
require("pdf-parse");
require("ping");
require("readline-sync");
require("recursive-copy");
require("ssh2shell");
require("sz-iptools");
require("winattr");

console.log('loaded')
```
and
```bash
nexe index.js -t 14.15.3 -o out
mv out.exe ~/Desktop/out.exe
cd ~/Desktop
./out.exe 
loaded
```

**Comment by chassy33** [comment]
Thank you for the quick response! I am not completely sure how nexe uses the package.json file or why that would make it fail. Is there any additional debugging I can enable/ complete on my end to help?
