### ISSUE TITLE
[NodeJs 16.14.0] vcbuild.bat nosign release x64 exited with code: 1

### ISSUE THREAD

**Issue by gabrielfu** [nexe/nexe#968]
**What happened**:
Trying to build .exe on Windows but encountered this error.

I have read #799 already and have the following installed:
- Python 3.8.7
- Visual Studio 2019
- NASM 2.15.04

Also, I looked into `node.gyp`, which is a zero length empty file.

Is it because of my Node JS version (16.14.0) ?

```
i nexe 4.0.0-beta.19
√ Downloading Node.jssource from: https://nodejs.org/dist/v16.14.0/node-v16.14.0.tar.gz
√ Already downloaded...
√ Compiling result
√ Configuring node build...
  Compiling Node with arguments: nosign,release,x64
Note: vcbuild no longer signs by default. "nosign" is redundant.
Looking for Python
Python found in C:\Python\Python38\\python.exe
Looking for NASM
Looking for Visual Studio 2022
Looking for Visual Studio 2019
calling: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.3
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Found MSVS version 16.0
configure  --with-ltcg --dest-cpu=x64
Node.js configure: Found Python 3.8.7...
Traceback (most recent call last):
  File "configure", line 27, in <module>
    import configure
  File "C:\Users\Gabriel\.nexe\16.14.0\configure.py", line 2053, in <module>
    run_gyp(gyp_args)
  File "tools\gyp_node.py", line 48, in run_gyp
    rc = gyp.main(args)
  File "tools\gyp\pylib\gyp\__init__.py", line 654, in main
    return gyp_main(args)
  File "tools\gyp\pylib\gyp\__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "tools\gyp\pylib\gyp\__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "tools\gyp\pylib\gyp\input.py", line 3009, in Load
    LoadTargetBuildFile(
  File "tools\gyp\pylib\gyp\input.py", line 400, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(
  File "tools\gyp\pylib\gyp\input.py", line 237, in LoadOneBuildFile
    build_file_data = eval(build_file_contents, {"__builtins__": {}}, None)
  File "node.gyp", line 0

    ^
SyntaxError: unexpected EOF while parsing
Failed to create vc project files.
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 5.54s

Error: vcbuild.bat nosign release x64 exited with code: 1

See nexe -h for usage..
```

**What you expected to happen**:
Build the application

**How to reproduce it (as minimally and precisely as possible)**:
Ran this command:
```
nexe --verbose --build -t windows -i main.js -o main.exe
```

**Environment**:
- Platform(OS/Version): Windows 10
- Host Node Version: 16.14.0
- Target Node Version: 16.14.0
- Nexe version: 4.0.0-beta.19
- Python Version: 3.8.7

**Comment by hugodecasta** [comment]
Same configuration here, tried with all sources available (14.0.0, 15.0.0 even mine on 16.14.2). VScode 2019 and 2022 installed with CC+ build tools and the latest NASM release (included in the PATH):

```
> cat index.js | nexe -o test.exe --build --verbose
i nexe 4.0.0-rc.1
√ Downloading Node.jssource from: https://nodejs.org/dist/v16.13.1/node-v16.13.1.tar.gz
√ Already downloaded...
√ Compiling result
√ Configuring node build...
  Compiling Node with arguments: nosign,release,x64
Note: vcbuild no longer signs by default. "nosign" is redundant.
Looking for Python
Python found in C:\Python38\\python.exe
Looking for NASM
Looking for Visual Studio 2022
calling: "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.2.1
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Found MSVS version 17.0
configure  --with-ltcg --dest-cpu=x64
Node.js configure: Found Python 3.8.6...
ERROR: Did not find a new enough assembler, install one or build with
       --openssl-no-asm.
       Please refer to BUILDING.md
Failed to create vc project files.
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 7.521s

Error: vcbuild.bat nosign release x64 exited with code: 1

See nexe -h for usage..
```

Please help

**Comment by hugodecasta** [comment]
> Same configuration here, tried with all sources available (14.0.0, 15.0.0 even mine on 16.14.2). VScode 2019 and 2022 installed with CC+ build tools and the latest NASM release (included in the PATH):
> 
> ```
> > cat index.js | nexe -o test.exe --build --verbose
> i nexe 4.0.0-rc.1
> √ Downloading Node.jssource from: https://nodejs.org/dist/v16.13.1/node-v16.13.1.tar.gz
> √ Already downloaded...
> √ Compiling result
> √ Configuring node build...
>   Compiling Node with arguments: nosign,release,x64
> Note: vcbuild no longer signs by default. "nosign" is redundant.
> Looking for Python
> Python found in C:\Python38\\python.exe
> Looking for NASM
> Looking for Visual Studio 2022
> calling: "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\\Auxiliary\Build\vcvarsall.bat" amd64
> **********************************************************************
> ** Visual Studio 2022 Developer Command Prompt v17.2.1
> ** Copyright (c) 2022 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64'
> Found MSVS version 17.0
> configure  --with-ltcg --dest-cpu=x64
> Node.js configure: Found Python 3.8.6...
> ERROR: Did not find a new enough assembler, install one or build with
>        --openssl-no-asm.
>        Please refer to BUILDING.md
> Failed to create vc project files.
> √ Compiling Node with arguments: nosign,release,x64
> √ Finished in 7.521s
> 
> Error: vcbuild.bat nosign release x64 exited with code: 1
> 
> See nexe -h for usage..
> ```
> 
> Please help

After trying to debug the node compiler (using the node repo and playing with the compilation scripts vcbuild and pyhton configure) i found out that **python was reading the nasm in my system32 folder** which was an old 2.07 nasm (although the PATH indicated the program files nasm anw powershell knew which one to pick)

The fix as to permanantly delete the system32 nasm so that Python had no choice but to go find the one in Program files

**Comment by amiralam0** [comment]
```
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,1): fatal error C1001: Internal compi
ler error. [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
  (compiler file 'msc1.cpp', line 1693)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(50,35): message : while evaluating const
expr function 'v8::internal::CallInterfaceDescriptor::DefaultRegisterArray' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gy
pfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,46): message : while evaluating const
expr function 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::registers' [C:\Users\k
abutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(61): message : while compiling class tem
plate member function 'void v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::Initializ
e(v8::internal::CallInterfaceDescriptorData *)' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors.h(1792): message : see reference to class temp
late instantiation 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>' being compiled [C
:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
  INTERNAL COMPILER ERROR in 'D:\hih\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,1): fatal error C1001: Internal compi
ler error. [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
  (compiler file 'msc1.cpp', line 1693)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(50,35): message : while evaluating const
expr function 'v8::internal::CallInterfaceDescriptor::DefaultRegisterArray' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gy
pfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,46): message : while evaluating const
expr function 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::registers' [C:\Users\k
abutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(61): message : while compiling class tem
plate member function 'void v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::Initializ
e(v8::internal::CallInterfaceDescriptorData *)' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors.h(1792): message : see reference to class temp
late instantiation 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>' being compiled [C
:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
  INTERNAL COMPILER ERROR in 'D:\hih\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
  machine-operator-reducer.cc
  js-typed-lowering.cc
  libnode.vcxproj -> out\Release\lib\libnode.lib
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,1): fatal error C1001: Internal compi
ler error. [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
  (compiler file 'msc1.cpp', line 1693)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(50,35): message : while evaluating const
expr function 'v8::internal::CallInterfaceDescriptor::DefaultRegisterArray' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gy
pfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,46): message : while evaluating const
expr function 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::registers' [C:\Users\k
abutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(61): message : while compiling class tem
plate member function 'void v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::Initializ
e(v8::internal::CallInterfaceDescriptorData *)' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors.h(1792): message : see reference to class temp
late instantiation 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>' being compiled [C
:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_compiler.vcxproj]
  INTERNAL COMPILER ERROR in 'D:\hih\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
  Assembling ..\..\deps\v8\src\heap\base\asm\x64\push_registers_masm.S...
  deoptimized-frame-info.cc
  baseline-compiler.cc
  interface-descriptors.cc
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,1): fatal error C1001: Internal compi
ler error. [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
  (compiler file 'msc1.cpp', line 1693)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(50,35): message : while evaluating const
expr function 'v8::internal::CallInterfaceDescriptor::DefaultRegisterArray' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gy
pfiles\v8_base_without_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,46): message : while evaluating const
expr function 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::LookupBaselineDescriptor>::registers' [C:\User
s\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(61): message : while compiling class tem
plate member function 'void v8::internal::StaticCallInterfaceDescriptor<v8::internal::LookupBaselineDescriptor>::Initia
lize(v8::internal::CallInterfaceDescriptorData *)' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_co
mpiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors.cc(89): message : see reference to function te
mplate instantiation 'void v8::internal::StaticCallInterfaceDescriptor<v8::internal::LookupBaselineDescriptor>::Initial
ize(v8::internal::CallInterfaceDescriptorData *)' being compiled [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_b
ase_without_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors.h(809): message : see reference to class templ
ate instantiation 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::LookupBaselineDescriptor>' being compiled
[C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
  INTERNAL COMPILER ERROR in 'D:\hih\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
  deoptimize-reason.cc
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,1): fatal error C1001: Internal compi
ler error. [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
  (compiler file 'msc1.cpp', line 1693)
  deoptimizer.cc
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(50,35): message : while evaluating const
expr function 'v8::internal::CallInterfaceDescriptor::DefaultRegisterArray' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gy
pfiles\v8_base_without_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(64,46): message : while evaluating const
expr function 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::registers' [C:\Users\k
abutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors-inl.h(61): message : while compiling class tem
plate member function 'void v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>::Initializ
e(v8::internal::CallInterfaceDescriptorData *)' [C:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compi
ler.vcxproj]
C:\Users\kabutar\.nexe\16.15.0\deps\v8\src\codegen\interface-descriptors.h(1792): message : see reference to class temp
late instantiation 'v8::internal::StaticCallInterfaceDescriptor<v8::internal::I64ToBigIntDescriptor>' being compiled [C
:\Users\kabutar\.nexe\16.15.0\tools\v8_gypfiles\v8_base_without_compiler.vcxproj]
  INTERNAL COMPILER ERROR in 'D:\hih\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
  materialized-object-store.cc
  translated-state.cc
√ Compiling Node with arguments: nosign,release,x64
√ Finished in 38.558s
```

I am getting this

**Comment by MdRonyAhmed** [comment]
vcbuild.bat nosign release x64 exited
