### ISSUE TITLE
Unable to build binary for Node.js 17.6.0 (or 14.5 or 12.9.1)

### ISSUE THREAD

**Issue by CyberGen49** [nexe/nexe#969]
As the title describes, Nexe runs into an error while trying to build a binary for Node.js 17.6.0, even after using `--clean`, and directing `--python` to a fresh installation of Python 2.7, just in case.

The output is as follows:
```
D:\Users\Cyber\Desktop\test-app>nexe main.js
i nexe 4.0.0-beta.19
√ Downloading pre-built Node.js
√ Finished in 0.943s

Error: https://github.com/nexe/nexe/releases/download/v3.3.3/windows-x64-17.6.0 is not available, create it using the --build flag

See nexe -h for usage..

D:\Users\Cyber\Desktop\test-app>nexe --build --clean
i nexe 4.0.0-beta.19
√ Deleted contents at: C:\Users\Cyber\.nexe\17.6.0
√ Finished in 4.27s

D:\Users\Cyber\Desktop\test-app>nexe --build
i nexe 4.0.0-beta.19
√ Node source extracted to: C:\Users\Cyber\.nexe\17.6.0
√ Finished in 72.153s
SyntaxError: Line 204, column 38: Unexpected token '?'
    at constructError (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:5625:21)
    at report (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:5664:7)
    at parseAndClassifyIdentifier (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:5356:11)
    at parsePrimaryExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3390:22)
    at parseMemberExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3130:63)
    at parseLeftHandSideExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3117:13)
    at parseUpdateExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3055:26)
    at parseUnaryExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3029:13)
    at parseBinaryExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:2950:72)
    at parseConditionalExpression (C:\Users\Cyber\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:2920:20)

D:\Users\Cyber\Desktop\test-app>nexe --build --python C:\Python27
[Same output]
```

I noticed that the releases currently have up to Node 14, but that seems pretty far back from what I'm using, so I'm not sure if I should downgrade.

Versions:
* Node.js 17.6.0
* nexe 4.0.0-beta.19
* Windows 11 21H2

### Edit
I've confirmed that the exact same issue also occurs on Ubuntu 20.04 (via Windows Subsystem for Linux)
```
cyber@Ideacentre:/mnt/d/Users/Cyber/Desktop/test-app$ nexe --build
ℹ nexe 4.0.0-beta.19
✔ Node source extracted to: /home/cyber/.nexe/17.6.0
✔ Finished in 93.4s
SyntaxError: Line 204, column 38: Unexpected token '?'
    at constructError (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:5625:21)
    at report (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:5664:7)
    at parseAndClassifyIdentifier (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:5356:11)
    at parsePrimaryExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:3390:22)
    at parseMemberExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:3130:63)
    at parseLeftHandSideExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:3117:13)
    at parseUpdateExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:3055:26)
    at parseUnaryExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:3029:13)
    at parseBinaryExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:2950:72)
    at parseConditionalExpression (/usr/local/lib/node_modules/nexe/node_modules/cherow/dist/umd/cherow.js:2920:20)
```

And a different issue when trying to build Node 14.5 or 12.9.1:
```
cyber@Ideacentre:/mnt/d/Users/Cyber/Desktop/test-app$ nexe --build --targ
et windows-x64-14.5.0
ℹ nexe 4.0.0-beta.19
✔ Node source extracted to: /home/cyber/.nexe/14.5.0
✔ Configuring node build: --dest-cpu=x64
✔ Finished in 69.162s
Error: spawn python EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by bmaupin** [comment]
It seems that starting with Node 16, Python 2 support was removed: https://nodejs.org/en/blog/release/v16.0.0/#toolchain-and-compiler-upgrades

In my own experience, on Ubuntu 20.04 I had to use Python 3 to build Node 14+, e.g.

```
nexe hello.js --build --make=-j5 --python=$(which python3) --verbose
```

(I highly recommend `--verbose` for better build output)

Or:

```
sudo apt install python-is-python3
```
