### ISSUE TITLE
Node 16 removed support for Python 2

### ISSUE THREAD

**Issue by bmaupin** [nexe/nexe#970]
The README explicitly mentions Python 2, but Node 16 removed support for Python 2: https://nodejs.org/en/blog/release/v16.0.0/#toolchain-and-compiler-upgrades

Thankfully it's pretty easy to do the build with `--python`:

```
nexe hello.js --build --python=$(which python3) ...
```

In my case, building Node 12+ worked with Python 3 and Node <= 10 required Python 2. But given that Node 10 is EOL, maybe Python 3 should be the new default?

**Comment by calebboyd** [comment]
The readme could be updated! PR's welcome.
I'm not sure I agree with python3 being the new default. `python --version` IME is python 3 on most systems today.
I suppose it could be detected.

**Comment by calebboyd** [comment]
With respect to the steps you have for small binary sizes, you can make the base build more succinct with --no-mangle

1) `npx nexe app.js --no-mangle -o base.bin --build --configure='--with-intl=small-icu' --verbose`
(no mangle will esstially copy the build artifact (3 and 4)
2) `strip base.bin`
3) `upx base.bin`
4) `npx nexe app.js -a base.bin -o app.bin`

**Comment by bmaupin** [comment]
> The readme could be updated! PR's welcome

:+1: 

> I'm not sure I agree with python3 being the new default. `python --version` IME is python 3 on most systems today.

That hasn't been my experience, but my experience is pretty limited:

- The `node:16` docker image (based on Debian buster) has `python` pointing to `python2`:

  ```
  $ docker run --rm -it node:16 sh -c 'ls -l $(which python)'
  lrwxrwxrwx 1 root root 7 Mar  4  2019 /usr/bin/python -> python2
   ```

- Alpine Linux doesn't have a `python` binary at all when Python 3 is installed:

  ```
  $ docker run --rm -it alpine sh -c 'apk add python3; ls -l /usr/bin/python*'
  ...
  lrwxrwxrwx    1 root     root             9 Mar 16 19:16 /usr/bin/python3 -> python3.9
  ```

- Same for Ubuntu:

  ```
  docker run --rm -it ubuntu:20.04 sh -c 'apt update; apt -y install python3; ls -l /usr/bin/python*'
  ...
  lrwxrwxrwx 1 root root       9 Mar 13  2020 /usr/bin/python3 -> python3.8
  ```

> I suppose it could be detected.

That seems like it would be ideal. At any rate it's not urgent or anything given that it's easily worked around.

Thanks!

**Comment by bmaupin** [comment]
> With respect to the steps you have for small binary sizes, you can make the base build more succinct with --no-mangle

Thanks for the tip! It's far from my area of expertise but I've been super impressed with `nexe`, especially when seeing how much more flexible it is than `pkg`, despite pkg having commercial backing.

**Comment by bmaupin** [comment]
I did some quick tests regarding the feasibility of making Python 3 the default:

| Node version | Python 2 build | Python 3 build | [Supported](https://nodejs.org/en/about/releases/) |
| --- | --- | --- | --- | 
| 16.14.1| fail | pass | yes |
| 14.19.0 | pass | pass | yes; end of life 2023-04-30 |
| 12.22.10 | pass | pass | yes; end of life 2022-04-30 |
| 10.24.1 | pass | fail | no; end of life 2021-04-30 |

Given that as of today all supported versions of Node.js build with Python 3, it seems like it would be a reasonable default. But if nothing else I'll see about a PR for minimal changes to the readme.

Just for reference, here's the specific error that I got when trying to build Node 10 with Python 3:

```
$ docker run --rm node:16 sh -c 'npm install -g nexe; echo "console.log('"'"'Hello world'"'"');" > hello.js; nexe hello.js --build --target linux-x64-10.24.1 --make=-j4 --python=$(which python3) --verbose'
...
Traceback (most recent call last):
  File "./configure.py", line 28, in <module>
    from gyp.common import GetFlavor
  File "tools/gyp/pylib/gyp/__init__.py", line 37
    print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
                         ^
SyntaxError: invalid syntax
```

Likewise, when trying to build Node 16 with Python 2:

```
$ docker run --rm node:16 sh -c 'npm install -g nexe; echo "console.log('"'"'Hello world'"'"');" > hello.js; nexe hello.js --build --target linux-x64-16.14.1 --make=-j4 --python=$(which python2) --verbose
...
Traceback (most recent call last):
  File "./configure.py", line 30, in <module>
    from gyp.common import GetFlavor
  File "tools/gyp/pylib/gyp/__init__.py", line 188
    return f"{opt}={value}"
                          ^
SyntaxError: invalid syntax
```
