### ISSUE TITLE
Unable to build node 16.15.0

### ISSUE THREAD

**Issue by m-rousse** [nexe/nexe#985]
# Description

When trying to bundle a project with `linux-x64-16.15.0` as a target, I get the following output:

```
> yarn nexe input.js -t linux-x64-16.15.0 --build --make="-j16" -o /tmp/output

ℹ nexe 4.0.0-beta.19
✔ Already downloaded...
✔ Finished in 0.039s
SyntaxError: Line 180, column 38: Unexpected token '?'
    at constructError (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:5625:21)
    at report (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:5664:7)
    at parseAndClassifyIdentifier (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:5356:11)
    at parsePrimaryExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:3390:22)
    at parseMemberExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:3130:63)
    at parseLeftHandSideExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:3117:13)
    at parseUpdateExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:3055:26)
    at parseUnaryExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:3029:13)
    at parseBinaryExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:2950:72)
    at parseConditionalExpression (/Users/mathieu.rousse/go/src/github.com/DataDog/synthetics-worker/node_modules/cherow/dist/umd/cherow.js:2920:20)
```

The `input.js` file contains a simple `console.log`:

```javascript
console.log("Test")
```

## Expected output

I expect `nexe` to properly compile node and bundle the project.

## Quick investigation

As it seems to be tied to `cherow` failing to parse a file, I followed the code, leading to `cherow` being used to load the node bootstrap file, and failing at this line: https://github.com/nodejs/node/blob/e24328201344d58044bd34710ae1479a644ffa6f/lib/internal/bootstrap/pre_execution.js#L180

I suppose `cherow` does not support the `??=` syntax.

**Comment by calebboyd** [comment]
Looks like your analysis is correct. I'll see if we can get that replaced and a new version cut!

**Comment by calebboyd** [comment]
@m-rousse I was able to fix it in #986. If you give it a spin via `nexe@next` I'll publish it as latest

**Comment by m-rousse** [comment]
Hey @calebboyd, it worked correctly both on mac and windows (for windows I had to install python in a path without space because of this bug https://github.com/nodejs/node/pull/42810, though totally unrelated to the issue you fixed)

Many thanks!

**Comment by amiralam0** [comment]
the bug is still here
