### ISSUE TITLE
SyntaxError: Line 232, column 38: Unexpected token '?'

### ISSUE THREAD

**Issue by AceKiron** [nexe/nexe#990]
Trying to build nexe with `nexe --build` on a x64 Windows machine with NodeJS v18.0.0, but it's giving me this error.
```
i nexe 4.0.0-beta.19
√ Already downloaded...
√ Finished in 3.421s
SyntaxError: Line 232, column 38: Unexpected token '?'
    at constructError (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:5625:21)
    at report (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:5664:7)
    at parseAndClassifyIdentifier (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:5356:11)
    at parsePrimaryExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3390:22)
    at parseMemberExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3130:63)
    at parseLeftHandSideExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3117:13)
    at parseUpdateExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3055:26)
    at parseUnaryExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:3029:13)
    at parseBinaryExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:2950:72)
    at parseConditionalExpression (C:\Users\kiron\AppData\Roaming\npm\node_modules\nexe\node_modules\cherow\dist\umd\cherow.js:2920:20)
```

**Comment by AceKiron** [comment]
Turns out I had to build with the rc version instead of beta...

**Comment by amiralam0** [comment]
i am getting this issue too

**Comment by AceKiron** [comment]
> i am getting this issue too

@amiralam0 Try using installing `nexe@next` instead of `nexe`, it's a different version which for me happened to work.

**Comment by amiralam0** [comment]
> > i am getting this issue too
> 
> @amiralam0 Try using installing `nexe@next` instead of `nexe`, it's a different version which for me happened to work.

can you tell me the version number of nexe i should use?

**Comment by AceKiron** [comment]
> > > i am getting this issue too
> > 
> > 
> > @amiralam0 Try using installing `nexe@next` instead of `nexe`, it's a different version which for me happened to work.
> 
> can you tell me the version number of nexe i should use?

4.0.0-rc.1 is the one I'm using.
